### ISSUE TITLE
Modifier Key conflicts: Shift & Alt Keys

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10007]
| Bugzilla |  |
|----------|----------|
| ID | BZ14382 |
| Reported | 2021-04-12 14:16:00 +0200 |
| Modified | 2021-04-17 19:52:34 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | 3.5.5 |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Mark Benson](mailto:markben61@gmail.com) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |
| See Also | http://www.vassalengine.org/tracker/show_bug.cgi?id=14396 |

#### [Mark Benson](mailto:markben61@gmail.com) 2021-04-12 14:16:36 +0200
<pre>Note: This information is based on behaviour on the Mac and has not been compared with Windows or Linux.

Introduction:
Shift+Left-Click has a standard role for cumulative selection of objects. It is similar to the MacOS Vassal Command+Left-Click key except that will also de-select.

Shift+Left-Click is also an option for the Does Not Stack trait to select a piece. 

The only modifier key alternative on the Does Not Stack trait is Alt+Left-Click. 

Issue:
When used for Does Not Stack, Shift+Left-Click, pieces so selected are added to the group select. This can create confusion/overhead for the user.  The alternative, Alt+Left-Click, will trigger a Flare by default.

Considerations:

1a) Are two types of Select command key really needed? It makes sense for list-based commands, where Shift is creating a group in list-mode and Command (on Mac) is creating a group in an arbitrary order. Pieces on a board, don't have a list order.

1b) If the ambiguous role of Shift were removed, the user could be given control of group select because the Select modifier should layer on top of whatever function is being used. e.g. the Does Not Stack select key.

2) Should the Flare function be standardised; configured through map and global options but always working from a standard key command combination ?  The standard function should be chosen that does not conflict with OS or existing Vassal functions; perhaps Fn+Left-Click or Shift+Alt+Left-Click.</pre>

#### [Mark Benson](mailto:markben61@gmail.com) 2021-04-16 16:09:46 +0200
<pre>See also this discussion concerning the Flare command key in general: http://www.vassalengine.org/forum/viewtopic.php?f=5&t=13184</pre>

**Comment by Cattlesquat** [comment]
@riverwanderer Checking back on this one too

**Comment by riverwanderer** [comment]
I would suggest Meta+Main Mouse Button (ie Cmd+LeftClick on Mac) as a Select option for the Does Not Stack trait. Any more than that seems like too many choices. Personally, I would prefer a less used combo like this was the default for Flare but perhaps that ship has sailed (that would make Alt+LeftClick viable again as a Select option for the Does Not Stack trait).

Another useful option would be the ability to configure specific modifiers to control whether a Does Not Stack piece can be moved, separately from whether it is selected or not. At the moment, if I want to have a normally immovable piece selectable _without a modifier key_ then either that piece has to be hard-and-fast immobile OR effectively not immobile at all.

Perhaps, in the Does Not Stack trait, the same modifiers that are available for Select could also be available directly on the Move option. viz...
Always
Never
When Selected
When Shift key is pressed
When Alt key is pressed

With this Move when-key-pressed option, a piece could be selected but still immobile, yet could (e.g. for scenario building) be moved into position using the modifier key.
