### ISSUE TITLE
Refresh Decks (Dev Build): Send to Deck not respecting new deck's parameters

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10025]
| Bugzilla |  |
|----------|----------|
| ID | BZ14404 |
| Reported | 2021-04-19 21:48:00 +0200 |
| Modified | 2021-04-19 21:48:38 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | unspecified |
| Platform | All |
| OS | Mac OS |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | major |
| Milestone | --- |
| Reporter | [Mark Benson](mailto:markben61@gmail.com) |
| Assignee | [Claudio Ciardelli](mailto:claudio.ciardelli@gmail.com) |
| See Also | http://www.vassalengine.org/tracker/show_bug.cgi?id=13159 |

#### [Mark Benson](mailto:markben61@gmail.com) 2021-04-19 21:48:17 +0200
<pre>Using: VASSAL-3.6.0-SNAPSHOT-ca50a79-13159

A new deck was added to a module, with similar parameters to an existing draw deck.
Specifically, Face Down Always and Max card to display = 10 (i.e. default settings)

An existing deck was updated to add "Include a command to send entire deck to another deck" (the new deck, Ctrl+T hotkey).

When refreshed, the hotkey sends all cards from the existing deck to the new deck.

However, the entire stack of cards is displayed face up in the new deck.

To reproduce,

1) run this demo module and select pre-set scenario TEST2, connect as observer...
https://www.dropbox.com/s/deo5i9n9mut8hry/ccn%20v4-0a59XVassal%2036.vmod?dl=0

2) Refresh Counters  (Optionally, save the game here and restart, loading the refreshed game file)

3) Press Ctrl+T ... observe the blue deck of cards has disappeared (moved)

4) Press F2 to bring up the Special Window (where the new deck is located)... observe the same deck of cards, now showing in full stack, face up</pre>

**Comment by riverwanderer** [comment]
Is Refreshing of decks included in V3.6 ? If not, this bug report is moot. However, if it is included, then I will try to re-create a test case. In future, I will upload all test cases to Vassalengine.org, assuming that is allowed.

**Comment by Cattlesquat** [comment]
Ah. It's not presently included, but it's still "out there" as an ongoing project. Thanks for the clarification this item probably deserves to remain open.

Please do, yes, create a test case. You can either attach it here in a comment or put it on Vassalengine.org if that seems easier (I can't think of a reason that wouldn't be okay -- just mark each file clearly e.g. Bug10025TestCase.vmod)
