### ISSUE TITLE
Make Deck  dependent on Module Config, not saved file Config. Split out Deck Key Commands

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10027]
| Bugzilla |  |
|----------|----------|
| ID | BZ14406 |
| Reported | 2021-04-20 08:00:00 +0200 |
| Modified | 2021-06-14 08:01:23 +0200 |
| Product | VASSAL |
| Component | Editor |
| Version | 3.5.5 |
| Platform | All |
| OS | All |
| Status | ASSIGNED |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | 3.6.0 |
| Reporter | [Brent Easton](mailto:b.easton@exemail.com.au) |
| Assignee | [Brent Easton](mailto:b.easton@exemail.com.au) |
| See Also | http://www.vassalengine.org/tracker/show_bug.cgi?id=14578 |

**Comment by BrentEaston** [comment]
See #10289. Sort Key added and new Deck Send Key added that are not stored in the Deck, but always follow the module config.

Can potentially add new versions of all existing in-deck KeyCommands and obsolete them out of existence. Then perhaps provide designer an option to Convert to the new versions.

**Comment by BrentEaston** [comment]
This is not longer required once 9063 is implementing providing a fully functioning Deck Refresher. Decks will able to be refreshed, including position and all attributed, by refreshing a save game.
