### ISSUE TITLE
ABR: [Waterloo Napoleon's Last Battle] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10199]
| Bugzilla |  |
|----------|----------|
| ID | BZ14598 |
| Reported | 2021-06-27 00:09:00 +0200 |
| Modified | 2021-06-27 00:09:12 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | 3.5.7 |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

| Attachments | |
|-------|-------|
| [errorLog](http://www.vassalengine.org/files/bz/13063) | [Joel Uckelman](mailto:uckelman@nomic.net) 2021-06-27 00:09:00 +0200 text/plain 6645 the errorLog |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2021-06-27 00:09:11 +0200
<pre>tdchistorian@gmail.com

I was adding an icon graphic to the server button

Waterloo Napoleon's Last Battle vv2.0 3.5.7

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3424)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3410)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:425)</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2021-06-27 00:09:12 +0200
<pre>Created attachment 13063
the errorLog</pre>

**Comment by Cattlesquat** [comment]
Error log missing & looks un-useful anyway
