### ISSUE TITLE
[Across the Pacific] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\LUISCAPC\AppData\Roaming\VASSAL\tiles\556d671a70591091561a95188252729515c397e6\c\c8\c8db0529deebefa3e90536458432dcc7010c724e

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10219]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [21432 bytes](http://www.vassalengine.org/files/gh/f7214b62a045a6273e6bdd6e9712d0c4219c8935) |

<pre>

Across the Pacific v1.01a 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\LUISCAPC\AppData\Roaming\VASSAL\tiles\556d671a70591091561a95188252729515c397e6\c\c8\c8db0529deebefa3e90536458432dcc7010c724e
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
Dupe #9957
