### ISSUE TITLE
[SWWAS] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Chris\AppData\Roaming\VASSAL\tiles\cd02d7ccce8081fdb97550f59a60a3c3f9cb98b2\7\70\70cb06cbc3c4420dc5c52bd00a94eb8a60bf34ab

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10217]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | Restarting a module under development after loading arather large file into a chart area. |
| Error Log | [61312 bytes](http://www.vassalengine.org/files/gh/4434b6bc5e6bc2181401c20335ee83aa954394ba) |

<pre>

SWWAS v0.0 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Chris\AppData\Roaming\VASSAL\tiles\cd02d7ccce8081fdb97550f59a60a3c3f9cb98b2\7\70\70cb06cbc3c4420dc5c52bd00a94eb8a60bf34ab
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:319)
</pre>

**Comment by Cattlesquat** [comment]
Dupe #9957
