### ISSUE TITLE
[France 1944 Designer's Edition] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\User01\AppData\Roaming\VASSAL\tiles\75dc03a93e7b82230e6318505b1b4ae27e421173\9\96\965dee3c643d46382e2081ddd6ac81f5d48312b5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10216]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | maurikios@web.de |
| Error Log | [13573 bytes](http://www.vassalengine.org/files/gh/78b8c7e946bfdc2b3845b10106cdb5db4c13a645) |

<pre>Hallo,

sadly the map is not loaded - any help would be nice.

With kind regards
Johannes

France 1944 Designer's Edition v1.0 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\User01\AppData\Roaming\VASSAL\tiles\75dc03a93e7b82230e6318505b1b4ae27e421173\9\96\965dee3c643d46382e2081ddd6ac81f5d48312b5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
Dupe #9957
