### ISSUE TITLE
[Blue Cross White Ensign] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /Users/anthonydangelojr./Library/Application Support/VASSAL/tiles/6084ef0b8515365f4d57b844fad307d8b18ed4cf/0/07/0725d067448a5f7226392f1dd535c76af1d06a05

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10211]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [13903 bytes](http://www.vassalengine.org/files/gh/aac8bb43792fc19e0fc7a005ebc229a72d46872d) |

<pre>

Blue Cross White Ensign v1.1 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /Users/anthonydangelojr./Library/Application Support/VASSAL/tiles/6084ef0b8515365f4d57b844fad307d8b18ed4cf/0/07/0725d067448a5f7226392f1dd535c76af1d06a05
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
Dupe #9957
