### ISSUE TITLE
[1862EC] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Alex\AppData\Roaming\VASSAL\tiles\615ab89ff890d8024eae66c099e96ea8bab64749\a\a6\a6dcae6f0999422d145394662b28d19b399628d2

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10235]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | mjryan1@rogers.com |
| Error Log | [13072 bytes](http://www.vassalengine.org/files/gh/a11db0e799828dd3178768aea14620bfb23b546c) |

<pre>Loading a game

1862EC v0.01 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Alex\AppData\Roaming\VASSAL\tiles\615ab89ff890d8024eae66c099e96ea8bab64749\a\a6\a6dcae6f0999422d145394662b28d19b399628d2
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
Dupe #9957
