### ISSUE TITLE
[OCS - CB & GBII] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Jim\AppData\Roaming\VASSAL\tiles\012140c714d0b0643bec94e86fcf46f757d66ae1\f\fe\fe870ad4aa4a7e388ee231a0582fecd97c629d4a

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10237]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | jimhambacher@comcast.net |
| Error Log | [12808 bytes](http://www.vassalengine.org/files/gh/4f207168e6c9199b7d1cb54f1e6e41c666b3c751) |

<pre>Looking at Russian Patrol Zones in OCS CB & GBII module 5.10.01 whikle scrolling.

OCS - CB & GBII v5.10.01 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Jim\AppData\Roaming\VASSAL\tiles\012140c714d0b0643bec94e86fcf46f757d66ae1\f\fe\fe870ad4aa4a7e388ee231a0582fecd97c629d4a
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
Dupe #9957
