### ISSUE TITLE
GetRestorePiecesCommand is getting/receiving a null piece - [Commands & Colors: Napoleonics] NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10251]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [131823 bytes](http://www.vassalengine.org/files/gh/b433c5a14613fd80392e20b7cec8adba6fabfc05) |

<pre>

Commands & Colors: Napoleonics v4.0.2 3.5.8

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null
 at VASSAL.build.module.GameState$10.compare(GameState.java:1076)
 at VASSAL.build.module.GameState$10.compare(GameState.java:1061)
 at java.base/java.util.TimSort.binarySort(TimSort.java:296)
 at java.base/java.util.TimSort.sort(TimSort.java:239)
</pre>

**Comment by Cattlesquat** [comment]
Loading game from wizard & getting "weird result" => probably an unwarned wrong-module-version type error.
