### ISSUE TITLE
[A5A Perryville] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Steve\AppData\Roaming\VASSAL\tiles\0d8b68ca1b4a989b14899187ada5afd1e3cc0207\1\13\1335d9b961cb4df83273b539c5da6b13c223e5cb

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10268]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | srugge@aol.com |
| Error Log | [10251 bytes](http://www.vassalengine.org/files/gh/b63ba7a843865fa4702d32292f75c95c3df61055) |

<pre>Opening up the Across Five Aprils Perryville module.  Tile Cache Error: Tile not found.  Some of the map tiles do not display.

A5A Perryville v1.4.1 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Steve\AppData\Roaming\VASSAL\tiles\0d8b68ca1b4a989b14899187ada5afd1e3cc0207\1\13\1335d9b961cb4df83273b539c5da6b13c223e5cb
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
Dupe #9957
