### ISSUE TITLE
Return To Deck Deck name can be lost when pre 3.6 module is edited using 3.6

### ISSUE THREAD

**Issue by BrentEaston** [vassalengine/vassal#10385]
Occurs when a Return to Deck trait exists in an At-start stack on one map and references a Deck on another Map. Editing the module in 3.6 causes the Deck name to be blanked out. Referencing a Deck on the same map does not cause a problem

**Comment by stanhilinski** [comment]
Just running under 3.6 blanked the name, no 3.6edit needed.
