### ISSUE TITLE
NPE when trying to create new P2P Network

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10402]
| ABR | |
|-----|-----|
| Version | 3.6.0-beta2 |
| Reporter | robinhpeterson@gmail.com |
| Error Log | [17064 bytes](http://www.vassalengine.org/files/gh/ec1f5c08fe826e8a53d5fde7a3c119abd626ad9b) |

<pre>Attempting to press the Add button in the server tab of the preferences dialog. Doing prep work for looking at setting up a private XMPP Multi-Chat server. As I recollect this worked fine in the last version I used - 3.5.5.			

1776 v0.3 3.6.0-beta2

java.lang.NullPointerException: null
 at VASSAL.chat.HttpRequestWrapper.buildGet(HttpRequestWrapper.java:60)
 at VASSAL.chat.HttpRequestWrapper.doGet(HttpRequestWrapper.java:97)
 at VASSAL.chat.HttpRequestWrapper.doGet(HttpRequestWrapper.java:54)
 at VASSAL.chat.ServerAddressBook.discoverMyIpAddressFromRemote(ServerAddressBook.java:143)
</pre>

**Comment by BrentEaston** [comment]
Steps to reproduce:
1. Open preferences
2. Select Server Tab
3. Click on Add button
4. Select P2P Network
5. Boom.

This still creates private server and a P2P Network options. These can be edited and more can be edited. If you remove these and repeat the process, the error happens again.
