### ISSUE TITLE
[Commands & Colors Ancients] IllegalBuildException: failed to load class ancients.Scenario

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10447]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | markben61@gmail.com |
| Error Log | [5066 bytes](https://vassalengine.org/files/gh/9035f3c4ed02f05fad15cc95bb2e2c7bbad4d774) |

<pre>Opened a module that works under v3.5.8 but with custom code changed to complete with Deprecation warning in v3.6.

Possibly an expected error ?

Commands & Colors Ancients v4.1f1 3.5.8

VASSAL.build.IllegalBuildException: failed to load class ancients.Scenario
 at VASSAL.build.Builder.create(Builder.java:132)
 at VASSAL.build.Builder.build(Builder.java:80)
 at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:77)
 at VASSAL.build.GameModule.build(GameModule.java:635)
</pre>

**Comment by uckelman** [comment]
It looks like the Auditable stuff got into this module, so it won't load with 3.5 after that.

**Comment by BrentEaston** [comment]
No, should not happen. 
Ah, I bet they made the changes and recompiled against the 3.6 source instead of 3.5.8 source. I will contact Mark
