### ISSUE TITLE
Need Game Refresher to be "Mat Aware"

### ISSUE THREAD

**Issue by Cattlesquat** [vassalengine/vassal#10468]
http://www.brianreynolds.com/files/Almoravid_1.0.vmod

1. Start new game as either side
2. Right click on one of those "empty squares" to left of map
3. Pick any of the "Lord Mats" to be mustered
4. Run Game Refresher

Expected: Yay, refreshing goodness

Actual: Problems & Exception

**Comment by BrentEaston** [comment]
See also #10452
