### ISSUE TITLE
Pop Out Module Window Controls

### ISSUE THREAD

**Issue by EmilysDad** [vassalengine/vassal#10515]
Allow the Module Window controls (e.g. the Toolbar, the Game Piece Palette, the Chat Log) to separate from the map board and become individual windows. The controls could then be moved to other display monitors, etc. to give an unobstructed, full screen view of the main map board.

**Comment by uckelman** [comment]
Related to #4485.

**Comment by Cattlesquat** [comment]
@EmilysDad If you go to your Preferences and on the first tab uncheck the "Use Combined Application Window" option about halfway down, and then exit VASSAL and restart, I think you will find that it does exactly what you want.

**Comment by Cattlesquat** [comment]
not a bug - capability already exists - at least as far as I understand the report -- go to Preferences and uncheck the "Use Combined Application Window", then exit VASSAL and restart.
