### ISSUE TITLE
[The Binding of Isaac: Four Souls] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Pipe\AppData\Roaming\VASSAL\tiles\f24a19d060c2849ab7a31e00ed5ec9cc49d49920\4\4c\4c0ec5f1abf456e5859ef201ae69a36514871e17

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10693]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [18692 bytes](https://vassalengine.org/files/gh/0c26fbe96a90df2e50db3c8a143bbd8d1cc85cba) |

<pre>

The Binding of Isaac: Four Souls v2.2.0.f 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Pipe\AppData\Roaming\VASSAL\tiles\f24a19d060c2849ab7a31e00ed5ec9cc49d49920\4\4c\4c0ec5f1abf456e5859ef201ae69a36514871e17
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
Duplicate #9957
