### ISSUE TITLE
Not running properly with Debian 11 (openjdk)

### ISSUE THREAD

**Issue by WizardOfWor1969** [vassalengine/vassal#10692]
I am running VASSAL-3.5.8-linux
My java version info:

openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.13+8-post-Debian-1deb11u1, mixed mode, sharing)

The launcher comes up, but when I select a game and try to run it by double clicking, i get nothing but a spinning ball (gnome). I have a mac as well , and all these game files work fine using the Mac version. I notice some java processes are still running after closing and have to kill them. It's like they are hung.

When launching the game directly like this:
java -Xms512M -Xmx512M -Duser.home=/home/adamchall -Duser.dir=/home/adamchall/Applications/VASSAL-3.5.8-linux/VASSAL-3.5.8 -cp /home/adamchall/Applications/VASSAL-3.5.8-linux/VASSAL-3.5.8/lib/Vengine.jar VASSAL.launch.Player --load -- /home/adamchall/Documents/Vassal Modules/Barbarossa To Berlin/BtB_ver2.4.vmod

 I see this error:
VASSAL: File '[Ljava.lang.String;@63eef88a' of unknown type 

Error log is attached
[errorLog-3.5.zip](https://github.com/vassalengine/vassal/files/7478827/errorLog-3.5.zip)

**Comment by uckelman** [comment]
Where do you see the error you mention?

**Comment by WizardOfWor1969** [comment]
From the terminal

**Comment by uckelman** [comment]
You're probably seeing that error in the terminal because the path has spaces in it but you're not quoting it. Try putting single quotes around the path to the module.

**Comment by WizardOfWor1969** [comment]
Yes, you are correct. I put a quote around the module part and I did not get the error. The game did not launch though. I was just left with a blinking cursor.  I eventually pressed CTRL-C after a couple of minutes. I have attached the error log from just now..

[errorLog-3.5.zip](https://github.com/vassalengine/vassal/files/7492679/errorLog-3.5.zip)

**Comment by WizardOfWor1969** [comment]
Could this have anything to do with pulseaudio? After having to hit CTRL-C, I noticed no sound on my system and programs like vlc would not start. I had to reboot and the system was waiting on pulseaudio to quit. This happens when I try to launch the game from launcher and I have to reboot as well. The java processes are stuck as well. Audio usually works fine on my machine otherwise.

**Comment by WizardOfWor1969** [comment]
Ok, I have gotten a little further. The game launches if I disable HDAUDIO from the BIOS. I am running on an Intel NUC Ghost Canyon computer. We might want to close this , as the problem seems to be beyond the game , although other programs with audio work fine.

**Comment by uckelman** [comment]
That's strange. I've been using pulseaudio on my Fedora development system for many years without ever seeing a problem like this.

**Comment by uckelman** [comment]
Can you use a newer version of Java?

**Comment by WizardOfWor1969** [comment]
I think the problem might be with the driver for Intel HD audio, not sure yet. I am not sure what is special with VASSAL, either. I have not tried a newer version of Java. I thought this was the newest version.

**Comment by uckelman** [comment]
Java 11 is quite old. Java 17 is current.

**Comment by WizardOfWor1969** [comment]
I tried Java 17:
openjdk 17-ea 2021-09-14
OpenJDK Runtime Environment (build 17-ea+19-Debian-1)
OpenJDK 64-Bit Server VM (build 17-ea+19-Debian-1, mixed mode, sharing)

Same result. I think the problem is with the driver for HD-Audio (Intel). I am not sure why VASSAL would be different than other apps in this regard, if anyone has any ideas I would be welcome to try it.

**Comment by uckelman** [comment]
Does the problem happen with every module you try?

**Comment by WizardOfWor1969** [comment]
Seems to, yes.

**Comment by WizardOfWor1969** [comment]
I think we can close this one. The problem was solved when I followed the answer on this page:
https://askubuntu.com/questions/1243369/sound-card-not-detected-ubuntu-20-04-sof-audio-pci#1243370

Looks like the problem is that the audio driver detected on my system (sof-audio-pci, despite me having Intel HD audio) does not have "normal firmware" whatever that means. Apparently disabling as the instructions state will make the system fall back to the Intel audio driver , which I would have thought it should have done in the first place considering I am running Intel audio. I don't know why the bug only showed up in VASSAL and not other apps, but I think the root of the problem is fixed. Thanks uckelman for your help.

**Comment by uckelman** [comment]
Sound support is one of those unloved parts of the JDK. It wouldn't surprise me at all if it were doing something odd or broken that only affects some systems.

I'm glad you found a solution. I will also be glad when we're no longer using Java.
