### ISSUE TITLE
[Guild Ball (GBCP)] NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getPosition()" because "gamePiece" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10798]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [8642 bytes](https://vassalengine.org/files/gh/7171c36054e0586c1547a8b62b8e2923f765ae3c) |

<pre>

Guild Ball (GBCP) v9.5.5 3.5.8

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getPosition()" because "gamePiece" is null
 at VASSAL.build.module.Map.drawPiecesInRegion(Map.java:2094)
 at VASSAL.build.module.Map.paintRegion(Map.java:2042)
 at VASSAL.build.module.Map.paintRegion(Map.java:2029)
 at VASSAL.build.module.Map$View.paint(Map.java:3643)
</pre>

**Comment by Cattlesquat** [comment]
Stack with a "null" gamepiece in it. Quite possibly already fixed in 3.6 since we dealt with some of that stuff, but in any event the stack trace doesn't give us anything usable to go on.
