### ISSUE TITLE
[Wing Leader] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /Users/oguzhankarakahya/Library/Application Support/VASSAL/tiles/7d936dc4d7ff1dad74fa44dc4724e2439ab070d7/b/ba/ba020b6d0a2511c3587aedb0c82ef2adde065485

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10829]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [432241 bytes](https://vassalengine.org/files/gh/97d7a0efba4e4cc5baf755cd7748b08a71aa4a7e) |

<pre>

Wing Leader v5.00 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /Users/oguzhankarakahya/Library/Application Support/VASSAL/tiles/7d936dc4d7ff1dad74fa44dc4724e2439ab070d7/b/ba/ba020b6d0a2511c3587aedb0c82ef2adde065485
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
#9957
