### ISSUE TITLE
Make Action Button available on all windows where other buttons are allowed.

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#10820]
Up to v3.6beta7, the Action Button is only available from the top level (module). This request is that the Action Button component should also be available where-ever Multi-Action and GKC buttons are allowed.

Forum thread [here](https://forum.vassalengine.org/t/action-button-to-be-available-on-map-and-player-hand-windows/72706).

**Comment by Cattlesquat** [comment]
This is relatively straightforward to implement, but based on our "version compatibility rules" it missed the boat on 3.6 and so would need to wait until e.g. 3.7
