### ISSUE TITLE
[Full Thrust] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\aun.enowa_ag\AppData\Roaming\VASSAL\tiles\8e610df58c3c606286e4dce27d771bb84176ce83\c\cd\cdc88dddad8df5d12be7d7e0aa5df9f2f7b5e2c7

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10825]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [17043 bytes](https://vassalengine.org/files/gh/e47d0b0b340c1b552fc23ce4fa27b4265329fe85) |

<pre>Selecting a map board for a new game. The tile cache was cleared just before. The selected board is displayed normally in the game/module.

Full Thrust v0.0 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\aun.enowa_ag\AppData\Roaming\VASSAL\tiles\8e610df58c3c606286e4dce27d771bb84176ce83\c\cd\cdc88dddad8df5d12be7d7e0aa5df9f2f7b5e2c7
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
#9957
