### ISSUE TITLE
Expand Symbolic Die Button

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#10821]
The Symbolic Die button cannot be fully integrated in the way that Action and GKC buttons can because of the dynamic button image feature inherent to its ability. For example, an Action Button that plays a die rolling sound can not be activated simultaneously when a Symbolic Die button is pressed. 

Solution: If the Symbolic Die button included the ability to "Send Hotkeys" (like the Action Button does), this would be a gateway to integration for any features that the module designer might imagine. 

Extra: If it is deemed worth it, then the ability to play a sound file (to all players) might also be added (again, like the Action Button). This ability would still be possible even if only "Send Hotkey" were supported, but playing a sound file is probably the main use case.

Forum thread [here](https://forum.vassalengine.org/t/symbolic-dice-sound-file/12152/2).

**Comment by Cattlesquat** [comment]
Would need to wait for 3.7 -- the 3.6 feature addition window being closed once 3.6.0 went (really once 3.6-beta7 was released, since we tried to do bugfix-only after that)
