### ISSUE TITLE
"Set Global Property" label inside Available traits pane

### ISSUE THREAD

**Issue by alecrespi78** [vassalengine/vassal#10850]
"Set Global Property" label inside Available traits pane (single piece) shows wrong text "Dynamic Property".
Vassal 3.6.0-beta7

![vassal-bug](https://user-images.githubusercontent.com/89710784/144058071-4490a599-6dff-492c-9f66-4af0c81569c7.jpg)

**Comment by Cattlesquat** [comment]
@alecrespi78 Thanks! "Replace Marker" wasn't showing correctly either. Fixed up for 3.6.1
