### ISSUE TITLE
Images do not load

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#10854]
A module uses HTML in chat and displays images that way.
Very occasionally, users will load a module and it will behave as if the images are not found.
The image HTML strings fully defined in pre-set global properties. If the GPs were not set, that portion of the chat would be null.
This seems like some kind of Vassal module or game initialisation issue.
Workaround: Users should restart the module or re-enter the game and the problem should resolve itself.

![image](https://user-images.githubusercontent.com/58135975/144192651-7c08ba43-6343-479c-a646-159fddae2bf1.png)

**Comment by riverwanderer** [comment]
The module where I have seen this issue starts games from pre-defined files. At least one of the image tags in the above example is set by a one-time startup routine when the game is first opened. Others are just the initial values of the Global Properties and never change.

**Comment by Cattlesquat** [comment]
@riverwanderer Does this happen any more? Could it have been that the html strings had been updated to point to newer image files, and the scenario refresher not run?

**Comment by riverwanderer** [comment]
I have not seen / heard of it recently. I don't think it has anything to do with module updates. If affected, simply restarting the module (perhaps even just re-syncing) will resolve the issue.

**Comment by Cattlesquat** [comment]
Okay, if it ever comes back, open us a new one & we'll see if we can track anything down. We've had some fixes in how internal files get indexed since 2021
