### ISSUE TITLE
Loading VASL maps not possible w/ v. 3.6.1?

### ISSUE THREAD

**Issue by pablogons** [vassalengine/vassal#10884]
When trying to load either a VASL Scenario Setup module or a board from the repository, an error message shows up: 

"Board missing. Your board configuration must match X by X row/column matrix. Use NUL or NULV boards if required"

**Comment by uckelman** [comment]
You're seeing an incompatibility between VASL and Vassal 3.6. There's already a fix for it, but the new version of VASL which was intended to contain that fix was released without it. 

See here for details:  http://www.gamesquad.com/forums/index.php?threads/vasl-patch.165946/#post-2076775

There should be a _new_ fix release soon.

**Comment by uckelman** [comment]
There's a new download at vasl.info for 6.6.3.1 now, which fixes the problem.

**Comment by pablogons** [comment]
It's working fine now! Thank you so much for your prompt feedback and your immediate action to fix the issue.
