### ISSUE TITLE
[Paths of Glory] ClassCastException: class javax.swing.JPanel cannot be cast to class VASSAL.tools.ComponentSplitter$SplitPane (javax.swing.JPanel is in module java.desktop of loader 'bootstrap'; VASSAL.tools.ComponentSplitter$SplitPane is in unnamed module of loader 'app')

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10890]
| ABR | |
|-----|-----|
| Version | 3.6.1 |
| Reporter |  |
| Error Log | [10360 bytes](https://vassalengine.org/files/gh/02fe7fe0e64eafa0f117829506f4facf105a2239) |

<pre>

Paths of Glory v9.7 3.6.1

java.lang.ClassCastException: class javax.swing.JPanel cannot be cast to class VASSAL.tools.ComponentSplitter$SplitPane (javax.swing.JPanel is in module java.desktop of loader 'bootstrap'; VASSAL.tools.ComponentSplitter$SplitPane is in unnamed module of loader 'app')
 at PathsOfGlory.POGChatter.show(POGChatter.java:294)
 at VASSAL.build.module.Chatter$DisplayText.executeCommand(Chatter.java:600)
 at VASSAL.command.Command.execute(Command.java:61)
 at VASSAL.counters.GlobalCommand.apply(GlobalCommand.java:253)
</pre>

**Comment by Cattlesquat** [comment]
Lol, PoG 9.7 
*definitely* not compatible
