### ISSUE TITLE
[World in Flames Collectors Edition] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\WiF8 WEurope.jpg:0,1@0.0625

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10909]
| ABR | |
|-----|-----|
| Version | 3.6.1 |
| Reporter |  |
| Error Log | [296333 bytes](https://vassalengine.org/files/gh/1c10a1ed3bcae4f74c71cda129c85bb99317b3c2) |

<pre>a

World in Flames Collectors Edition v1.06.P 3.6.1

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\WiF8 WEurope.jpg:0,1@0.0625
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
This error looks a bit different from #10900.

**Comment by Cattlesquat** [comment]
#10937
