### ISSUE TITLE
[La Carga de los tres Reyes. Carlos Díaz para NAC Wargames] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Imagen Mano Cristiana 96.png:10,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10912]
| ABR | |
|-----|-----|
| Version | 3.6.1 |
| Reporter | betsunin@gmail.com |
| Error Log | [35565 bytes](https://vassalengine.org/files/gh/fb2b5fa5fb0995426db3d4220dab22a9cbb82f1e) |

<pre>I was trying to refresh the background picture of a Map window

La Carga de los tres Reyes. Carlos Díaz para NAC Wargames v10.07 3.6.1

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Imagen Mano Cristiana 96.png:10,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user for details.

**Comment by Cattlesquat** [comment]
#10937
