### ISSUE TITLE
项目下载下来后如何运行?

### ISSUE THREAD

**Issue by cuijie1203** [vassalengine/vassal#10914]
在IDE上打开后,如何让项目运行起来?第一次接触这个项目

**Comment by uckelman** [comment]
Google Translate: "How to make the project run after opening it on the IDE? First contact with this project"

**Comment by uckelman** [comment]
See here in the developers' guide: https://github.com/vassalengine/vassal/blob/master/developers-guide/developers-guide.adoc#running-vassal
