### ISSUE TITLE
VASL multiplayer online issues (cross-posted to VASSAL.ORG)

### ISSUE THREAD

**Issue by kbernatz** [vassalengine/vassal#10920]
Posted similar comment on the Vassal.org forums

------
We were 3 players trying to start up a new scenario (Hatten in Flames Campaign Game) using the Hatten map (HT), which we had previously played on with no issues in version vasl-6.6.1 and VASSAL version preceding this one (I think we were on 3.5.8, but we might have been on a early 3.6.0 beta).

The issues that occurred were as follows:

We loaded a saved file from the previous version and when we moved counters onto a locked marker, it would give an error about stacking /TO THE OTHER PLAYERS ONLY/. I.e. if I moved the counters onto the locked marker, everything behaved fine on my end and nothing shows up (even as I do it now solo). But for the other two people in the VASSAL room, it gave them errors. If they moved the counters onto the locked marker, then /I/ saw the error message (but they did not).

In a similar ‘it affects others’ issue, if we moved around a counter- say a 9-1 leader - it would leave ghost images /ON THE OTHER PLAYERS GAMES/ wherever we moved it to. But not on the screen of the person moving it. This could be fixed by re-sync’ing with the person, which would then remove those ghost images.

We have not tested either of these with other maps (Hatten map always had an issue that the LOS hasn’t been done: “VASL LOS disabled: java.lang.NullPointerException: Cannot read field “gridWidth” because “map” is null. VASSAL los active”, but that existed prior to any of the updates.

Edit (1): Forgot to add that we also tried creating a brand new scenario (i.e. not using the save from the older version) and that we updated to VASL latest version, as well.  The same issues were still observed after updating to latest VASSAL and VASL, as well as creating a new scenario from scratch.

**Comment by Cattlesquat** [comment]
Reported working okay again (w/ 3.6.2) on forums
