### ISSUE TITLE
Chess Clock show/hide does not undo

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#10930]
To replicate, open a module with the Chess Clock control button. e.g Paths of Glory.
"Show" the chess clocks from the Chess Clock control button.
The chess clock timers are displayed on the toolbar.
UnDo.
The Chess Clock timers remain displayed.

Impact: This UnDo restriction detracts from the ability of Vassal to hide the Chess Clock control button and use of means (GKC/GHK based) to set the chess clocks up.

**Comment by Cattlesquat** [comment]
haha I blame Michael Kiefte :) 

But please give this version a try and see if it straightens that out for you.

**Comment by riverwanderer** [comment]
That version (VASSAL-3.6.3-SNAPSHOT-78ad131-10930) hasn't made any difference to what I see, I'm afraid.  I should see the clocks disappear from the toolbar when I undo, is that right?
