### ISSUE TITLE
Slicey McTilerFace - ExecutionException: java.io.IOException: return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10949]
| ABR | |
|-----|-----|
| Version | 3.6.0 |
| Reporter |  |
| Error Log | [22970 bytes](https://vassalengine.org/files/gh/1cc55248609534063ec7e4147ea1a637ec3826fb) |

<pre>loading Wing Leader module

3.6.0

java.util.concurrent.ExecutionException: java.io.IOException: return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:505)
</pre>

**Comment by uckelman** [comment]
This is from 3.6.0. How did this even get reported?

**Comment by Cattlesquat** [comment]
I'm not sure whether this is of the same family as the "normal tiler bugs" or a different physlum/class/order/family/genus

**Comment by uckelman** [comment]
Something is totally hosed with this one---there are some OS-level error messages in the log that I've never seen before.

**Comment by Cattlesquat** [comment]
Haha, which part of...

faile
d
; error='The 
paging file is too sm
all for this ope
r
ation to complete' (DOS

... wasn't clear? ;)
