### ISSUE TITLE
[Empire of the Sun (2nd Edition)] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10951]
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter | jimhunter57@mac.com |
| Error Log | [447334 bytes](https://vassalengine.org/files/gh/26c619e1d3454c6aaa32876ea423f64d6f1636af) |

<pre>I was editing a new version of the Empire of the Sun module within Vassal 3.6.2. I created a new Map Window called "Deployable Reinforcements Window" and added a GKC to it called "Dispatch Button". I then started edited that GKC as follows:

1) I checked the "Toolbar button can be disabled by a property" checkbox.
2) I pasted the following expression into the "Global Property to disable this button when "true"" window:
    {LastDispatchTurn != GameTurn}

This is the first time that I tried using the "disabled by a property" feature in a GKC, and after consulting the Reference Manual, I think that window expects a simple property name - not an expression.

I have an image of the "Dispatch Button" GKC editing window after the error. I will save it for a few days in case you want to see it.

Cheers,
Jim Hunter.

Empire of the Sun (2nd Edition) v5.10.1r 3.6.2

java.lang.StackOverflowError: null
 at VASSAL.build.AbstractToolbarItem.checkDisabled(AbstractToolbarItem.java:210)
 at VASSAL.build.AbstractToolbarItem.addPropertyGateListener(AbstractToolbarItem.java:175)
 at VASSAL.build.AbstractToolbarItem.checkDisabled(AbstractToolbarItem.java:210)
 at VASSAL.build.AbstractToolbarItem.addPropertyGateListener(AbstractToolbarItem.java:175)
</pre>

**Comment by Cattlesquat** [comment]
#10954 should fix this

Thanks for the very clear description & repro steps!
