### ISSUE TITLE
[Empire of the Sun (2nd Edition)] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10955]
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter | jimhunter57@mac.com |
| Error Log | [90228 bytes](https://vassalengine.org/files/gh/da923738c0e4b9c1d530e38af0f0e0e40850f1ba) |

<pre>This is a vastly simplified way to reproduce the crash that I reported earlier today (#10951).

I first updated my MacOSX from 11.6.1 to 11.6.2 (the latest minor release of macOS Big Sur) - just to eliminate that as an issue.

1. Start vassal 3.6.2.
2. Open the latest released Empire of the Sun module (5.10.1) for editing (acknowledge the pop-up warning due to the module being created under 3.5.8).
3. Add a GKC to the "Allied Reinforcements" Map Window
4. In the newly-appeared GKC definition window, check the "Toolbar button can be disabled by a property" checkbox.
5. In the newly-appeared "Global Property to disable this button when "true"" window, start typing any property name.

Immediately after the first character is typed in the window, this crash occurs (reliably - at least on my Mac).

I see that you already have a fix identified for the StackOverflowError (which I have not tested), but I'm bringing this new info to your attention with a suspicion that there may be an underlying issue with the "disable" GKC feature.

You should be able to use the above recipe to test with your #10954 fix.

Cheers,
Jim Hunter.

Empire of the Sun (2nd Edition) v5.10.1 3.6.2

java.lang.StackOverflowError: null
 at java.base/java.util.HashMap.hash(HashMap.java:338)
 at java.base/java.util.HashMap.getNode(HashMap.java:568)
 at java.base/java.util.HashMap.get(HashMap.java:556)
 at VASSAL.build.module.properties.MutablePropertiesContainer$Impl.getMutableProperty(MutablePropertiesContainer.java:80)
</pre>

**Comment by Cattlesquat** [comment]
Confirmed that the new fix prevents the problem in this scenario - thx!
