### ISSUE TITLE
[Tobruk] IllegalStateException: No state for Decorator=label;84,65;Set Target;22;;0,0,0;b;0;l;0;b;l;$pieceName$ ($label$);Dialog;0;0;TextLabel;Set Target

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10966]
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter | macximus@cox.net |
| Error Log | [103292 bytes](https://vassalengine.org/files/gh/0e0adb01a73e7d5d1aedca083adfead4a8684106) |

<pre>loading saved game, TOBRUK

Tobruk v1.0 3.6.2

java.lang.IllegalStateException: No state for Decorator=label;84,65;Set Target;22;;0,0,0;b;0;l;0;b;l;$pieceName$ ($label$);Dialog;0;0;TextLabel;Set Target
 at VASSAL.counters.Decorator.setState(Decorator.java:348)
 at VASSAL.counters.Decorator.setState(Decorator.java:345)
 at VASSAL.counters.Decorator.setState(Decorator.java:345)
 at VASSAL.counters.Decorator.setState(Decorator.java:345)
</pre>

**Comment by uckelman** [comment]
Corrupt saved game?

**Comment by Cattlesquat** [comment]
This typically happens when a save file is loaded either
(a) into an earlier/different version of the module
(b) into the wrong module entirely

Is this reproducible if you make a new saved game and then load it back into the module?
