### ISSUE TITLE
Movement via arrow keys only allows for up/down and moving the arrow on the model makes no difference

### ISSUE THREAD

**Issue by keepiru1** [vassalengine/vassal#10970]
Hello, all of these relate to Malifaux 3E.

1. select a model, and use the arrow keys to move in the direction indicated by the green arrow in the centre of the model.
Expected: model moves one inch in the arrow direction.
Actual: model moves up one inch.

1. Activate charge lane.
2. turn green arrow in charge direction.
3. use up/down arrow to move model
Expected: model moves one inch in direction of charge lane.
Actual: model moves up and down only.

Please see attached screen images. NOTE that this is occurring on MAC O/S running 3.6.2 and Malifaux 3e Malifaux Burns V3a and was not an issue on vassal 3.5 prior. This is also occurring on my Linux Mint 20 system.

1. Select model
2. press control + arrow up key
Expected: model moves by half inch
Actual: Screen shrinks and shows the names of each monitor.
![Screen Shot 2021-12-21 at 15 30 14](https://user-images.githubusercontent.com/96459487/146873156-507f8026-d6c1-4712-a24c-0f1d4947c46c.png)
![Screen Shot 2021-12-21 at 15 31 08](https://user-images.githubusercontent.com/96459487/146873162-68e101fa-d5ea-4f43-9295-7687ae4f47f4.png)

**Comment by uckelman** [comment]
What's the last version of Vassal where these worked?

**Comment by keepiru1** [comment]
The last version I used where it worked was 3.5.Regards.On 22 Dec 2021 07:43, Joel Uckelman ***@***.***> wrote:
What's the last version of Vassal where these worked?

**Comment by uckelman** [comment]
Yes, but _which_ 3.5 release was the last where it worked?

**Comment by keepiru1** [comment]
The last version I played, and the only 3.5 that I used, was 3.5.6. I hadn't updated in a little while; sorry I can't be more helpful. Love to use vassal by the way, think it's great.


Regards



________________________________

**Comment by uckelman** [comment]
You could be more helpful by finding the last version that worked. :) 

Does the problem happen in 3.5.8? What about 3.6.0?

**Comment by keepiru1** [comment]
I wish that I had the time to play, let alone install different versions and fault find.




________________________________

**Comment by keepiru1** [comment]
So I went and had a look: 3.6.0 beta 6 works, you can arrow and walk around in Malifaux. from 3.6.0 beta 7, you can only move up and down the screen, regardless of which way the arrow is pointing. I hope that helps. 3.5.8 was also good.


Regards

________________________________

**Comment by uckelman** [comment]
Try VASSAL-3.6.3-SNAPSHOT-091eee7-10970: https://vassalengine.org/builds/

Does that fix the problem for you?

**Comment by keepiru1** [comment]
Hello Joel, yes it does! Thanks very much for the super quick service!


Regards

________________________________

**Comment by uckelman** [comment]
Thanks for testing. The fix will be in 3.6.3 within the next few days.
