### ISSUE TITLE
[Liberté] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11040]
| ABR | |
|-----|-----|
| Version | 3.6.3 |
| Reporter | markben61@gmail.com |
| Error Log | [1058188 bytes](https://vassalengine.org/files/gh/d89ca0fb9755bfea366a4f9b33a7656e0dea5ad7) |

<pre>A Movement Trait triggers on map move key command with a movement amount of zero and additional offset of 84 or 0. Worked when the additional offset was just 84 and it was triggered on the same key command that placed it, rather than the map movement.

I will now check for syntax errors in the beanshell.

Liberté v1.0a08 3.6.3

java.lang.StackOverflowError: null
 at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:82)
 at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:102)
 at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:47)
 at bsh.BSHArguments.getArguments(BSHArguments.java:65)
</pre>

**Comment by riverwanderer** [comment]
I worked around this by using the offset in the Send to Location trait rather using Movement trait.
Not sure what caused the problem; I was using CountStack() in the offset beanshell.

**Comment by Cattlesquat** [comment]
What the Stack trace shows is that the Move Fixed Distance trait was firing, and then that would cause the "apply-on-move" key for the map to be sent, and then that would _again_ activate the Move Fixed Distance trait which would _again_ activate the "apply-on-move" key, and so forth. It didn't go on infinitely but it did go on a lot of steps.
