### ISSUE TITLE
[Paths of Glory] ClassCastException: class javax.swing.JPanel cannot be cast to class VASSAL.tools.ComponentSplitter$SplitPane (javax.swing.JPanel is in module java.desktop of loader 'bootstrap'; VASSAL.tools.ComponentSplitter$SplitPane is in unnamed module of loader 'app')

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11046]
| ABR | |
|-----|-----|
| Version | 3.6.3 |
| Reporter |  |
| Error Log | [29224 bytes](https://vassalengine.org/files/gh/32ef13bc625135920c6d3ffa1d7592fceb2ee350) |

<pre>

Paths of Glory v9.7 3.6.3

java.lang.ClassCastException: class javax.swing.JPanel cannot be cast to class VASSAL.tools.ComponentSplitter$SplitPane (javax.swing.JPanel is in module java.desktop of loader 'bootstrap'; VASSAL.tools.ComponentSplitter$SplitPane is in unnamed module of loader 'app')
 at PathsOfGlory.POGChatter.show(POGChatter.java:294)
 at VASSAL.build.module.Chatter$DisplayText.executeCommand(Chatter.java:600)
 at VASSAL.command.Command.execute(Command.java:61)
 at VASSAL.counters.GlobalCommand.apply(GlobalCommand.java:253)
</pre>

**Comment by Cattlesquat** [comment]
Blah blah blah -- Paths of Glory 9.7 is a 3.2.17 version. 

I mean I guess it would be nice if there were a way to have it just announce that instead of failing.
