### ISSUE TITLE
Undocumented "new log file" hotkey - Remove, change or make customisable

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#11100]
Option+W appears to be an (undocumented?), unchangeable hotkey that begins a new log-file.  It doesn't seem like a good key choice for this function and now that Vassal offers the option to open a new log-file whenever a game/log is opened, perhaps a hotkey is redundant.  If it were retained as a hotkey, a better choice would be Cmd+N (Ctrl+N on Windows). See also, request for a hotkey to Close a logfile.

This is observed on MacOs. The equivalent on other platforms would be Alt+W but I have not checked to see if the hotkey works the same way on Windows.

**Comment by Cattlesquat** [comment]
Fixed by #11983
