### ISSUE TITLE
Add support for the Rotate trait to Refresh Counters

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#11104]
Rotate Trait suffers from the same "reset" issue that used to affected Layer and Text Label.
Since v3.5, Layer and Text traits mostly do refresh without resetting.

This is a request to extend the same support to the Rotate Trait.

**Comment by BrentEaston** [comment]
Need a `Use names to match modified Rotate traits` option for Rotate traits that works the same as Layers and Text labels.

**Comment by riverwanderer** [comment]
Tested build VASSAL-3.7.0-SNAPSHOT-eaba3a5-11104-Refresh_Rotate; new functionality works for me (single refresh tested, changed Key Commands for the Rotate commands) - ticked (default) does not reset the trait, unticked does; as expected.

Observation - neither option allows the Rotator name to be changed (from null in the test) to something else, but I suspect that is in line with other traits / expected behaviour (where state is set directly via the trait rather than via a property).
