### ISSUE TITLE
[Unnamed RPG System VASSAL Edition v2]NPE in SortParameterComparator.java:52

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11173]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter |  |
| Error Log | [1798412 bytes](https://vassalengine.org/files/gh/5cdbf5efc6a7abb0a4123f9e530832d4dd0630a8) |

<pre>Using Sort Key Command on a Deck. Command is supposed to sort by decending order of a numeric value.

Unnamed RPG System VASSAL Edition v2 v0.86 3.6.4

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "piece1" is null
 at VASSAL.build.module.map.deck.SortParameterComparator.compare(SortParameterComparator.java:52)
 at VASSAL.build.module.map.deck.SortParameterComparator.compare(SortParameterComparator.java:28)
 at java.base/java.util.TimSort.binarySort(TimSort.java:296)
 at java.base/java.util.TimSort.sort(TimSort.java:221)
</pre>

**Comment by Cattlesquat** [comment]
Hi @BrentEaston it looks like it's trying to compare with a "null" item in the Deck's list of pieces. Deck uses an _array_ `contents` to hold its values, but that array is guarded by an integer `pieceCount` that tells how many of the members of the array are actually valid/current. But it looks like this sort turns the _whole_ contents array into a List and then sorts that list -- which, especially for a deck that has been "shrunk" might well have invalid members now... I think? So I imagine a solution would be to make a list out of only the "pieceCount" amount of pieces and sort that? 

If you're too busy I can probably handle implementing a fix along those lines -- but wanted you to validate that's the right approach?
