### ISSUE TITLE
ObscuredToOthers is created and set false on a Piece without a Mask trait and remains false in a facedown deck

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#11174]
v3.6.5 master build 2dcfccf and earlier.

Pieces which do not have a Mask trait have no ObscuredToOthers property (ObscuredToOthers = null).
If those pieces are in a Deck at start, they also have no ObscuredToOthers property.
However, when such a piece is taken from the Deck it acquires` ObscuredToOthers=false`.

This behaviour can lead to module bugs and additional conditional clauses in expressions.

Also, a piece that is Masked seems to start with `ObscuredToOthers = false` even when in a Deck face-down at Startup. This is also the case if an unmasked piece is returned to a facedown deck.

Demo Module: [ObscuredToOthersBug.zip](https://github.com/vassalengine/vassal/files/7994953/ObscuredToOthersBug.zip)

Possibly I've missed something but I think that the ObscuredToOthers trait should be more closely integrated with Decks and the Mask trait. To resolve completely, the ObscuredToOthers property should always exist on pieces with the Mask trait and only on those pieces, even in a deck.  On a piece with the Mask trait, that state of the ObscuredToOthers should reflect the Mask status of the piece even when the piece is in a Deck.

**Comment by Cattlesquat** [comment]
These are presently behaving "as designed" (insofar as any emergent behavior in Vassal can really be called "designed"). So I have marked this w/ Enhancement tag. Changing the behavior, particularly the one about being in a face down deck, would require very careful examination of possible side effects.
