### ISSUE TITLE
GPIW refresh closes folders where contents have changed

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#11245]
Vassal v3.6

The GPIW Refresh function closes the folder(s) that have been updated.

For example, before update to the red / radical section:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/58135975/155239848-2dd97478-94db-4171-a9db-82343fbd5844.png">

After an update that added an item to one of the cateogiess in that folder, followed by a refresh of the GPIW window:
<img width="234" alt="image" src="https://user-images.githubusercontent.com/58135975/155239976-da742445-c208-4b4e-976d-e877c38acc44.png">

**Comment by Cattlesquat** [comment]
I think #11362 fixes this.
