### ISSUE TITLE
Action Buttons not initially working in a module edited/saved under Vassal v3.6

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#11316]
Action Buttons do not initialise in preset scenarios in a module edited/saved under Vassal v3.6.

For details see this [forum post](https://forum.vassalengine.org/t/action-buttons-not-working-initially-in-module-edited-in-v3-6/74209).

**Comment by riverwanderer** [comment]
In my tests, the issue is provoked by Refresh Counters under Vassal v3.6.5 (and issue replicates still in Vassal v3.6.6 builds). A workaround (for now) if to Refresh Predefined setups under Vassal 3.6.4; the module will then work even under later versions of Vassal.

**Comment by uckelman** [comment]
Fixed by #11327.
