### ISSUE TITLE
[Flying Colors] Game Refresher NPE - piece that wasn't on a map

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11360]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | markben61@gmail.com |
| Error Log | [13147 bytes](https://vassalengine.org/files/gh/b23efd67d616d6cd42d19ce064fa61b153c99f11) |

<pre>Exception (or an out of memory errors) occuring during Refresh Counters after a change to create a Calculated Property that is used to set a Game Piece Layer. May be associated with a module bug introduced during the change.  (Dev version of Flying Colors)

Flying Colors v2.6.1a01-SIDES 3.6.6

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.Map.placeAt(VASSAL.counters.GamePiece, java.awt.Point)" because the return value of "VASSAL.counters.GamePiece.getMap()" is null
 at VASSAL.build.module.map.StackMetrics.merge(StackMetrics.java:648)
 at VASSAL.build.module.Map$Merger.visitDefault(Map.java:3846)
 at VASSAL.counters.PieceVisitorDispatcher.accept(PieceVisitorDispatcher.java:46)
 at VASSAL.counters.DeckVisitorDispatcher.accept(DeckVisitorDispatcher.java:37)
</pre>

**Comment by Cattlesquat** [comment]
Predefined Scenario thing
