### ISSUE TITLE
Refresh Counters results in duplicate pieces in a situation where the updated piece has changed GPL

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#11361]
I want to do a change that involves changing the Game Piece Layer used by the pieces in my development version of Flying Colors.
Having done this change, I've noticed that Refresh Counters is duplicating the pieces.

Here is my hypothesis, fwiw:
1) RC relies somehow on stacking to remove the old piece
2) The Refreshed Piece in fact will occupy a different GPL therefore won't be stacked with the old piece.

Also; in this case, the new GPL is being worked out in a Calculated Property, whereas before is was in a Marker or Dynamic Marker trait.

[Link](https://www.dropbox.com/s/2kpptq79l5nu35t/Flying_Colors_2-6-1%20side.vmod?dl=0) to the dev version with this problem. The scenarios already have duplicate pieces. I predict that further runs of Refresh Counters will result in more duplicates.

An original scenario game file before the problem: [here](https://www.dropbox.com/s/l8fz8c3xocto63b/Minorca.vsav?dl=0). Refresh this with the module to see the problem occuring.

**Comment by riverwanderer** [comment]
See also #11360 - an exception report (and out of memory errors) associated with the same attempts to run RC. However, this happened as I was completing the changes. I'd already changed most counters (ships) and I think the duplication problem was already occurring by then, without the exception/memory issue.

**Comment by Cattlesquat** [comment]
This is for @BrentEaston to decide whether further action is needed.

**Comment by BrentEaston** [comment]
Thanks guys. I am not surprised that a changing GPL causes problems, but am a bit surprised that it duplicates pieces. Will look into it.

**Comment by BrentEaston** [comment]
Hi Mark,

I have tried to reproduce this in a small test module without success. The Refresh Counters happily changes the counters in question to the new layer. The refresh works on a Stack by first removing all pieces in the stack from the board, recreating them and then dropping each piece back onto the board in the stack position as if they had been dropped by Drag-n-Drop. This naturally handles any restacking due to GPL changes. I can't see how this can result in duplicated pieces. It must be a special case

You seem to have removed the linked module, can you replace that so I can reproduce the problem in the debugger?

Thanks,
Brent.

**Comment by BrentEaston** [comment]
Also, is this refresh current game or refreshing a predefined setup?

**Comment by riverwanderer** [comment]
> You seem to have removed the linked module, can you replace that so I can reproduce the problem in the debugger?

Sorry; [here](https://www.icloud.com/iclouddrive/06cmZKzSqtBvqbwG2loJqwX_Q#FC_GPL_refresh_bug) is again. I've moved my bug shares to iCloud, as I have to subject my DropBox to regular pruning.

> Also, is this refresh current game or refreshing a predefined setup?

Both.

To confirm single or double counters in the Flying Colors module, mouseover ship or leader counters. 
The key calculated properties are "layer" and "side".

**Comment by BrentEaston** [comment]
Mark,

Weirder and Weirder. If I start one of your scenarios (e.g. the first duel) and then drag a new ship onto the map, then the Mouse-over viewer shows 2 of them, just like you see after the refresh. The refresh is just changing the old counters to be in a state the same as your new counter definitions, I don't think it's a refresh problem at all, it is a Mouse-over stack view problem.

**Comment by riverwanderer** [comment]
I tried removing "a" and "b" layers. Made no difference (it would have disabled layer/mouseover for small counters but the large counters still show double). So it's not related to lower/upper case layer names.

**Comment by BrentEaston** [comment]
When I drag out a single ship and try and refresh, the refresh crashes with an NPE. I think this is a GPL issue, not the Stack-Viewer, the double view of the counters is another symptom.

I tried replacing the Calculated Property 'layer' in the 'SOL Markers' prototype with a plain Marker that just returns 'A' and as you found, that fixed the problem.  Even changing the CP to just return a string "A" and not reference any properties still caused the problem. I also hacked the module onto V3.5.8 and confirmed it's an issue there as well.

Using the CP as the layer selector seems to be interfering with the GPL selection. I suspect Vassal thinks the pieces are on more than one layer simultaneously.

Ok, I think I have an inkling. A eureka moment even.

From version 3.4.4, Calculated Properties are no longer evaluated if a piece is not on a Map. The insertion of a piece into it's Game Piece Layer happens just before the piece is placed on the map, so at that point it has no layer. Afterwards, it has a calculable layer, but it is not actually in that layer, hence the 2 copies seen by the viewer (I suspect). 

Not sure what we can do about this.

**Comment by riverwanderer** [comment]
`Not sure what we can do about this.`

Maybe nothing, especially if it's not a simple, safe fix. Using a CP to adjust a layer is obviously an outlier case and one I was happy to replace with a Dynamic Property.

**Comment by riverwanderer** [comment]
Tested [VASSAL-3.6.7-SNAPSHOT-8609bb6-11361-CP-GPL and it worked ok.
I have noticed a sudden failure in another part of the FC module that is evident in the build, but I can't see a connection to GPL/CP so I need to test some other v3.6.7 builds (multi-hit function Ctrl+2, 3, 4 etc gives 10x the number of hits it should).
