### ISSUE TITLE
Deck Empty Hotkey repeats per online player instance

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#11429]
Stemming my [forum post](https://forum.vassalengine.org/t/is-this-deck-hotkey-working-as-expected/74547/3), I've developed a canned replication of what I think is a bug with "Hotkey to send when Deck empties" affecting online games (at least). The symptom, as illustrated on the forum is duplicate processing of the hotkey, once per connected player.

To replicate, put the attached module into two or more Vassal instances, start it up on one of them and follow the instructions.
[Empty HK test.zip](https://github.com/vassalengine/vassal/files/8651753/Empty.HK.test.zip)

The bug replicates at least back to Vassal v3.5.8.

**Comment by riverwanderer** [comment]
Updated demo module (v0.2) that illustrates a workaround to the issue and also how the Empty Deck hotkey can be used to trigger independent actions local to other player instances (an Alert in the demo).
[Empty HK test.zip](https://github.com/vassalengine/vassal/files/8672190/Empty.HK.test.zip)

**Comment by Cattlesquat** [comment]
Should be fixed by #11963
