### ISSUE TITLE
[Commands & Colors Ancients] NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11432]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | markben61@gmail.com |
| Error Log | [319593 bytes](https://vassalengine.org/files/gh/c27d84cfc0a93c5096b41b37634319b4a0dedaf4) |

<pre>Custom code scenario chooser. Exception occurred when I clicked on a newly added scenario author (part of the UI for the custom code in the editor).

Not yet installed non-deprecated custom code, so this maybe the reason.

Commands & Colors Ancients v4.1f2 3.6.6

java.lang.NumberFormatException: For input string: ""
 at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
 at java.base/java.lang.Integer.parseInt(Integer.java:678)
 at java.base/java.lang.Integer.parseInt(Integer.java:786)
 at ancients.Scenario.getDate(Scenario.java:205)
</pre>

**Comment by riverwanderer** [comment]
Pretty sure this was down to intolerance for a blank data field in the custom code.

**Comment by Cattlesquat** [comment]
Custom Code, yup ... has bugs too :)
