### ISSUE TITLE
[Commands & Colors Ancients] NullPointerException: Cannot invoke "String.isBlank()" because "file" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11452]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [1469401 bytes](https://vassalengine.org/files/gh/577be5b1b7faa36f35f0735507f89be89a1771a4) |

<pre>had just added a couple of global properties containing HTML.  Looks like the html <img> tag has an error.

Commands & Colors Ancients v4.2.0a05 3.6.6

java.lang.NullPointerException: Cannot invoke "String.isBlank()" because "file" is null
 at VASSAL.tools.swing.DataArchiveHTMLEditorKit$DataArchiveHTMLFactory.create(DataArchiveHTMLEditorKit.java:82)
 at java.desktop/javax.swing.text.CompositeView.loadChildren(CompositeView.java:112)
 at java.desktop/javax.swing.text.FlowView$LogicalView.loadChildren(FlowView.java:722)
 at java.desktop/javax.swing.text.CompositeView.setParent(CompositeView.java:139)
</pre>

**Comment by riverwanderer** [comment]
This exception was caused when I mis-specified some HTML in a property that was subsequently used in a Report Action trait.  I specified `<img=... >` instead of `<img src=...>`

**Comment by BrentEaston** [comment]
Hi Mark (@riverwanderer),

I believe I have fixed this problem.

Could you please give build VASSAL-3.6.10-SNAPSHOT-8b245ac-11452-invalid_src_file a go and see if this resolves the problem (No image should be displayed with no error instead of an NPE).

Thanks,
Brent.

**Comment by riverwanderer** [comment]
Thanks @BrentEaston  - I tested and found as you described - image displayed and no NPE.
