### ISSUE TITLE
[1792 - la patrie en danger !] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Mise en place_France.png:3,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11466]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [11847 bytes](https://vassalengine.org/files/gh/ff95631ada4e4ca77ed9c67834ffd623f64816b2) |

<pre>

1792 - la patrie en danger ! v1.0 (bêta) 3.6.6

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Mise en place_France.png:3,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by riverwanderer** [comment]
TileNotFound - recurrence of https://github.com/vassalengine/vassal/issues/11395/ Need to clear cache (per https://github.com/vassalengine/vassal/issues/11532) ?
