### ISSUE TITLE
Replace selection not supported by report format "Insert" drop down

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#11502]
The "Insert" drop down resets any selection made by the user in the Report Format field and instead inserts text at some unexpected point that field. The reset of a selection is easily missed and the behaviour runs against "the way things usually work".

Demo/example:
1. User selects some text to replace:
<img width="907" alt="Pasted Graphic 6" src="https://user-images.githubusercontent.com/58135975/173221468-63722b29-a4c7-4516-9250-416cef4236e6.png">

2. At the moment of activating the drop down "Insert" menu, the selection is reset:
<img width="915" alt="Pasted Graphic 7" src="https://user-images.githubusercontent.com/58135975/173221474-846e9172-7132-42dd-992d-ce237f1a869c.png">

3. An insert option is chosen and the result is not what the user was expecting:
<img width="908" alt="Pasted Graphic 8" src="https://user-images.githubusercontent.com/58135975/173221485-59e631b4-7b98-4fa0-a281-355d054ae3ae.png">

**Comment by riverwanderer** [comment]
Thanks for fixing this @AsaiToshiya. Works for me too.

**Comment by AsaiToshiya** [comment]
You're welcome @riverwanderer.
