### ISSUE TITLE
[Grand Prix] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Grand Prix_Niedra Ceb-B2.jpg:2,0@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11511]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | hansonlinoh.official@gmail.com |
| Error Log | [29891 bytes](https://vassalengine.org/files/gh/62c14c05e1a8d28d95a256c09ba75410d714b05c) |

<pre>clicking on the niedra cebulskie 

Grand Prix vver 1.00 3.6.7

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Grand Prix_Niedra Ceb-B2.jpg:2,0@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by riverwanderer** [comment]
TileNotFound - recurrence of https://github.com/vassalengine/vassal/issues/11395/ Need to clear cache (per https://github.com/vassalengine/vassal/issues/11532) ?
