### ISSUE TITLE
Piece "disappears" when dragged to grid space with an existing stack and "snap to defined point"

### ISSUE THREAD

**Issue by flivni** [vassalengine/vassal#11513]
This might be a bug. It might be a "quirk". Heck, it might be a feature. (But I think it's a bug.)

Repro:
1. Map has snap to defined point. (E.g. main map in Salerno '43)
2. You are dragging a piece (or stack) onto an existing **expanded** stack.
3. The center of the dragged piece is over the grid space containing the existing stack, but not over any of the pieces in the existing stack (e.g. just below the existing stack.
4. The piece is dropped under the existing stack and seems like it has disappeared.

This happened to me a few times when dragging a piece from an existing stack... then deciding to not move it after all and dragging it back, missing the target and dropping just below the existing stack. Not sure how common it is in the wild.

The piece will reappear if the existing stack is moved.

Here's a video:
https://www.loom.com/share/70eec95301e34574b866b631745597f3

**Comment by uckelman** [comment]
We've had occasional reports of a disappearing piece but nobody's ever been able to reproduce it. You might have spotted the cause here.
