### ISSUE TITLE
[Leonidas Sector] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\R20 MV Live 1.jpg:13,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11512]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [74728 bytes](https://vassalengine.org/files/gh/c780914d61f4760c5ea6c7980af2ead6e41af2f8) |

<pre>Changing the map. after rotating it

Leonidas Sector vK1 3.6.7

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\R20 MV Live 1.jpg:13,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by riverwanderer** [comment]
TileNotFound - recurrence of https://github.com/vassalengine/vassal/issues/11395/ Need to clear cache (per https://github.com/vassalengine/vassal/issues/11532) ?
