### ISSUE TITLE
[OCS - Reluctant Enemies] NullPointerException: Cannot invoke "VASSAL.build.module.properties.MutablePropertiesContainer.addMutableProperty(String, VASSAL.build.module.properties.MutableProperty)" because "this.parent" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11533]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [68852 bytes](https://vassalengine.org/files/gh/2ef6078b67bf7fd0d58966667500ce9cf7ae30e7) |

<pre>

OCS - Reluctant Enemies v3.0 3.6.7

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.properties.MutablePropertiesContainer.addMutableProperty(String, VASSAL.build.module.properties.MutableProperty)" because "this.parent" is null
 at VASSAL.build.module.properties.MutableProperty$Impl.addTo(MutableProperty.java:98)
 at VASSAL.build.module.properties.GlobalProperty.addTo(GlobalProperty.java:213)
 at VASSAL.build.Builder.build(Builder.java:82)
 at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)
</pre>

**Comment by Cattlesquat** [comment]
This was fixed when we did post-paste-markups for Global Properties
