### ISSUE TITLE
Notes window doesn't initialise nicely

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#11564]
The Notes window seems to initialise bottom/right-justified. It would be better if it were top/left-justified. To replicate, you need a line of text at the end of your scenario notes that is longer than the window size (which I think is remembered by Vassal).

Bad:
<img width="531" alt="image" src="https://user-images.githubusercontent.com/58135975/177292896-f609d354-c4a3-4e26-b214-3d13f2519ad8.png">

Good:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/58135975/177293522-ba6c04a7-991d-480a-9c9c-497a3a1c9ccf.png">

Scrolling the scenario notes to the desired position and then Saving the Notes seems to temporarily fix the issue, but it re-emerges once the scenario file is saved, closed and re-opened.

**Comment by jonathanrwatts** [comment]
Surely it's simply opening the window with the last character visible (i.e., if you had a shorter line following that long one, it would be left-aligned)?  Is it also placing the text cursor after the last character?

**Comment by riverwanderer** [comment]
Yes, @jonathanrwatts you are right, it is opening with the last character visible (a simple newline is not enough though).
Also, no it is not placing the text cursor at all - the notes window displays but you have to click in it to enter any text and so your cursor starts in the nearest possible place to where you click.

**Comment by jonathanrwatts** [comment]
It would probably be best if the module stored the last cursor position whenever the window is closed, and reopen with that position in view.  That way, it will remember where you left off when last editing text, but you could move the cursor to the top before closing the window when you're done editing.

**Comment by riverwanderer** [comment]
> It would probably be best if the module stored the last cursor position whenever the window is closed, and reopen with that position in view.

Sounds fair enough. I think, to support legacy better, if the module hasn't stored the last cursor position, it should default to the top left.

**Comment by BrentEaston** [comment]
Can you please try the 11564-NotesTextPosition build when it turns up.

**Comment by riverwanderer** [comment]
> try the 11564-NotesTextPosition build

Seems perfect - Notes position is retained whilst in the module session but resets to the top on a fresh open.
I only tested with one session but this should probably be an individual user setting.
