### ISSUE TITLE
Help About module screen: improve formatting of Additional Module info text

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#11587]
In the Help About (module) screen, the Additional Module info 1 & 2 fields display concatenated with module name and Version number (see graphic for an example of the result). This request is that the fields are each separated by a line break (omitted if the field is empty).

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/58135975/179197023-fda18d66-9b58-4792-9cd7-2da6ba5f8890.png">

Issue checked and confirmed in latest v3.6.8 build.

**Comment by riverwanderer** [comment]
Workaround is possible as the html is processed. This is the result when I specify as follows for the C&C Nap module:
<img width="885" alt="image" src="https://user-images.githubusercontent.com/58135975/181861146-2624ccb4-a5d0-444d-ae66-eeb9b3b80c32.png">

<img width="498" alt="image" src="https://user-images.githubusercontent.com/58135975/181861103-7db942ec-02aa-430a-9626-f2a87f097285.png">

The key points are to find some element that sits neatly within the two dash (-) delimiters that the Vassal formatting imposes and then use HTML line breaks to split up what would have been Info1 & Info2 (all in Info2).

**Comment by Cattlesquat** [comment]
I think in this case putting your own html is going to work out far better than any attempt at automatic formatting we'd be likely to make.
