### ISSUE TITLE
Vassal v3.6.8 - notes window editing bug

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#11606]
Editing "Scenario Notes" panel using VASSAL-3.6.8-7deb888-menu-accelerator build, I notice that the cursor is stuck in "insert" mode. I tried this on two different machines after restarting & then rebooting. Replicates across different modules - for example, open any scenario under the Commands & Colors:Ancients module, bring up the Notes window (toolbar - "scroll" icon) and try editing the scenario notes.

Maybe related to the editing changes by @Cattlesquat or Notes window change by @BrentEaston ?

**Comment by Cattlesquat** [comment]
Could not reproduce. Weird MacOS thing?

**Comment by riverwanderer** [comment]
Was a general fault fixed by reverting out a notes window change, if I recall correctly.

**Comment by Cattlesquat** [comment]
Thx!
