### ISSUE TITLE
[Commands & Colors Ancients] NullPointerException: Cannot invoke "VASSAL.build.module.properties.MutablePropertiesContainer.addMutableProperty(String, VASSAL.build.module.properties.MutableProperty)" because "this.parent" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11628]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | markben61@gmail.com |
| Error Log | [151298 bytes](https://vassalengine.org/files/gh/772e6bdf303becd1fe5c04e89477a92824590daa) |

<pre>pasted a folder of map window gp's from one map to another.

Commands & Colors Ancients v4.2.0a74 3.6.7

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.properties.MutablePropertiesContainer.addMutableProperty(String, VASSAL.build.module.properties.MutableProperty)" because "this.parent" is null
 at VASSAL.build.module.properties.MutableProperty$Impl.addTo(MutableProperty.java:98)
 at VASSAL.build.module.properties.GlobalProperty.addTo(GlobalProperty.java:213)
 at VASSAL.build.Builder.build(Builder.java:82)
 at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)
</pre>

**Comment by riverwanderer** [comment]
Recurrence of Cannot invoke "VASSAL.build.module.properties.MutablePropertiesContainer.addMutableProperty(String, VASSAL.build.module.properties.MutableProperty)" because "this.parent" is null #11533
