### ISSUE TITLE
[Commands & Colors Ancients] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/Green Mat.jpg:1,4@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11629]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | markben61@gmail.com |
| Error Log | [1674289 bytes](https://vassalengine.org/files/gh/cd8ef503592cafbde7677e2eea6ecbc38b679f17) |

<pre>Newly replaced map image failed to load initially - a pop up appeal for an error report appeared and as it did so, the map image loaded, though it looks like the image before it was replaced.

caveat: This was all without reloading the module after changing the image.

Commands & Colors Ancients v4.2.0a74 3.6.7

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/Green Mat.jpg:1,4@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by riverwanderer** [comment]
TileNotFound - recurrence of https://github.com/vassalengine/vassal/issues/11395/ Need to clear cache (per https://github.com/vassalengine/vassal/issues/11532) ?
