### ISSUE TITLE
[Dead of Winter Battle of Stones River] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\DoW_map_C.jpg:2,1@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11631]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | justin.davies00@btinternet.com |
| Error Log | [13172 bytes](https://vassalengine.org/files/gh/94129674edd1287ebd4bc3f6f0c342a2708c52f9) |

<pre>Launched the day of battle scenario from Dead of Winter Battle of Stones River 2.06.  On joining the game when I scroll down I can see that the map tiles haven't drawn in across several parts of the map, all in the lower half.  I've downloaded the scenario again but still the same issue.  My opponent doesn't have the same issue but has the same version of vassal (3.6.7)

Dead of Winter Battle of Stones River v2.06 3.6.7

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\DoW_map_C.jpg:2,1@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by riverwanderer** [comment]
TileNotFound - recurrence of https://github.com/vassalengine/vassal/issues/11395/ Need to clear cache (per https://github.com/vassalengine/vassal/issues/11532) ?
