### ISSUE TITLE
[Real] NullPointerException: Cannot invoke "VASSAL.build.module.properties.MutablePropertiesContainer.addMutableProperty(String, VASSAL.build.module.properties.MutableProperty)" because "this.parent" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11673]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | survivios198@gmail.com |
| Error Log | [26483 bytes](https://vassalengine.org/files/gh/6c1bede842a655e976d2f775d5d66ea4c8a359bc) |

<pre>I was copying a folder full of global properties and trying to past it in the global properties folder. The thing might be flipping out because it sees the creation of multiple properties with the same name.

Real v0.1 3.6.7

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.properties.MutablePropertiesContainer.addMutableProperty(String, VASSAL.build.module.properties.MutableProperty)" because "this.parent" is null
 at VASSAL.build.module.properties.MutableProperty$Impl.addTo(MutableProperty.java:98)
 at VASSAL.build.module.properties.GlobalProperty.addTo(GlobalProperty.java:213)
 at VASSAL.build.Builder.build(Builder.java:82)
 at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)
</pre>

**Comment by riverwanderer** [comment]
Reproduced by attempting a copy of a folder of unique GPs from the Module level to a map level. No duplication of GPs at map level, so that is not the cause.

Duplicating the folder in place and dragging the copy to the new Global Properties location does work.

**Comment by riverwanderer** [comment]
Recurrence of Cannot invoke "VASSAL.build.module.properties.MutablePropertiesContainer.addMutableProperty(String, VASSAL.build.module.properties.MutableProperty)" because "this.parent" is null #11533
