### ISSUE TITLE
Loophole in Deck attribute Send Hotkey when empty prevents processing last card

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#11714]
Vassal appears to prevent using Deck "Send when empty" hotkey to send a command to the last card to be removed from the deck.

When the card is removed, the Hotkey triggers and, at that point, the removed card has no location and is not found by a Global Key Command (even using CurrentMap=="" or a GKC without any search criteria).

Demo module:
[Empty HK test2.zip](https://github.com/vassalengine/vassal/files/9723883/Empty.HK.test2.zip)

**Comment by riverwanderer** [comment]
Workarounds:

1) Processing of the last card has to be deferred to a subsequent *independent* action, by using the deck-empty hotkey to set a flag instead of directly acting on the card. This is not a universal solution.

2) The Deck-Empty action could be checked for on the card itself, but this is will require extra logic on the cards.

**Comment by Cattlesquat** [comment]
The empty-deck function is fired off in a gnarly way at a gnarly place -- as Mark describes, it happens *instantly* at the moment when the last card has been unlinked from the deck -- before it complete its move. Really this command should get "queued up" at that point, and then fired off when the card/piece is *finished* moving (e.g. right after it possibly fires its apply-on-move key, etc, and definitely after it has been linked back to a map somewhere). 

Of course that would mean adding something in each of the many places a piece can be moved (PieceMover, SendToLocation, FreeRotator, Translate, Return to Deck, Deck's SendToDeck, and the Deck Send Key command. I can't remember if there are... even more? 

It's definitely pretty scary and messy though to be initiating new commands/hotkeys while a piece is unlinked.

```
protected void removePieceAt(int index, boolean suppressDeckCounts) {
    final int startCount = pieceCount;
    if (!suppressDeckCounts) {
      updateCounts(index);
    }
    super.removePieceAt(index, suppressDeckCounts);
    if (!suppressDeckCounts) {
      fireNumCardsProperty();
      // Do NOT fire a Deck Empty key if it has been caused by an Undo Command
      if (hotkeyOnEmpty && emptyKey != null && startCount > 0 && pieceCount == 0 && ! GameModule.getGameModule().getBasicLogger().isUndoInProgress()) {
        gameModule.fireKeyStroke(emptyKey);
      }
    }
  }
```

**Comment by BrentEaston** [comment]
GameModule.fireKeyStroke(key) is really sucky. It doesn't return a Command, it just blasts out the hotkey and lets whoever handle it do a SendAndLog(c)o you get multiple undos.  That's got nothing to do with this problem though, just needed a rant :) 

Yes, I agree, this is very bad and I agree that the best solution is to have a pending hotkey buffer to hold extra hotkeys generated during a Move. Yes, we would need to check for this in every bit of movement code, essentially every place we check for the Map afterburner key. For now, I would just use this for this specific case so we don't change too much. I don't see anyway around it.
