### ISSUE TITLE
[The Spanish Ulcer 1808-1814] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Battle & Attrition Table.png:0,5@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11729]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | pvt_dix@yahoo.com |
| Error Log | [26970 bytes](https://vassalengine.org/files/gh/6a91b8014053b59b2cee548d34cbba69c54457fb) |

<pre>Was trying to check the 'Battle and Attrition Table' in the playtest module of The Spanish Ulcer 1808-1814 v7 2.  Expected to see another  version of the table, but got this error instead...

The Spanish Ulcer 1808-1814 vv7 Map with Provinces 3.6.7

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Battle & Attrition Table.png:0,5@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment]
emailed user to clear tile cache
