### ISSUE TITLE
[OCS - Burma] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\burma_map B 111619.png:1,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11739]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | igormotyka6@gmail.com |
| Error Log | [26150 bytes](https://vassalengine.org/files/gh/612cf7f3fe7a177b024e2071fe9464964c58e154) |

<pre>I've started local tutorial scenario by myself in Burma module version 2.11. Immidietly after starting the game this error occured

OCS - Burma v2.11 3.6.7

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\burma_map B 111619.png:1,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment]
emailed user to clear tile cache
