### ISSUE TITLE
NPE at PrototypeFolder.java:37 when cut and paste a folder of prototypes

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11748]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | fcolmenarez@gmail.com |
| Error Log | [28305 bytes](https://vassalengine.org/files/gh/dcecc7e364df1540bb6ed9db6101c0c9bc3c6a3c) |

<pre>I was copying a folder from the Game Piece Prototype Definition that contained three prototype definitions. I attempted to paste it in the game piece prototype definitions as a second folder. In a nutshell I was trying to duplicate the folder with the same three pieces since my next set of definitions were very similar and only needed a different layer.

Rebel Fury v1.0 3.6.7

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.PrototypesContainer.addDefinition(VASSAL.build.module.PrototypeDefinition)" because "protos" is null
 at VASSAL.build.module.folder.PrototypeFolder.add(PrototypeFolder.java:37)
 at VASSAL.build.Builder.build(Builder.java:83)
 at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)
 at VASSAL.configure.ConfigureTree$5.actionPerformed(ConfigureTree.java:654)
</pre>

**Comment by BrentEaston** [comment]
Hi @Cattlesquat,
Can you have a look at this one? Easy to reproduce, just cut and paste any folder of in the prototypes container.
Brent.

**Comment by Cattlesquat** [comment]
@BrentEaston Should be fixed by #11877 -- the "duplicate" function on Prototype Folders was working, but the copy/paste sequence did things in a different order & I needed to add a "post paste fixup"
