### ISSUE TITLE
[Hell's Paradise] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\TXE-605b (calliope) Map.jpg:6,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11747]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | Kevin.at.phoenix@gmail.com |
| Error Log | [79216 bytes](https://vassalengine.org/files/gh/cb3229064f3cdc9fad431b8b42b8eeeaeb5a6bdc) |

<pre>I was swapping 3 maps out to twice the size image. After rezizing the multi-zone grid and hex-grid. I reciecev the error when pasting the first zone and grid into the other resized maps 

Hell's Paradise vK1 3.6.7

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\TXE-605b (calliope) Map.jpg:6,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:311)
</pre>

**Comment by BrentEaston** [comment]
Emailed user to clear tile cache
