### ISSUE TITLE
[Co-Ops] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\infanterie FAMAS.jpg:0,5@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11786]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | vandenbosch.christian@gmail.com |
| Error Log | [11692 bytes](https://vassalengine.org/files/gh/a5bd6f2a4f26ab25a91a266c6f76a675b96daa13) |

<pre>I work on a new module
I have changed a board from 1753/1300 to 1753/1600.
i save, and start game
the bug come when I open the board infanterie FAMAS.jpg

Co-Ops v0.0 3.6.7

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\infanterie FAMAS.jpg:0,5@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:311)
</pre>

**Comment by BrentEaston** [comment]
Emailed user to clear tile cache
