### ISSUE TITLE
[Skies Above the Reich] NullPointerException: Cannot invoke "String.isEmpty()" because "currentTitle" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11810]
| ABR | |
|-----|-----|
| Version | 3.6.8 |
| Reporter | rarubin79@gmail.com |
| Error Log | [5515 bytes](https://vassalengine.org/files/gh/6926b9b164c26081d8cd50d001c14a935127ca73) |

<pre>1. Vassal 3.6.8, Skies Above teh Reich 1.01, Windows 10 (up to date).
I have not used this module previously. I Started Vassal and opened it from the Module Library window. The setup window opened (password etc) which I canceled.
Then I clicked "Counters" and the tabs showed, and I clicked on a couple of them, not sure which, and the error happened. 

Professionally, I am a software developer, and I routinely discover latent bugs by using programs in unexpected ways.

Skies Above the Reich v1.01 3.6.8

java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "currentTitle" is null
 at VASSAL.build.widget.TabWidget.refreshTabs(TabWidget.java:116)
 at VASSAL.build.widget.TabWidget.getComponent(TabWidget.java:136)
 at VASSAL.build.widget.TabWidget.stateChanged(TabWidget.java:55)
 at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:446)
</pre>

**Comment by BrentEaston** [comment]
This issue appears to have already been addressed by @uckelman  in commit 5d32fcc186d0907406a9f2739e4b7891b203b600 and included in 3.6.9. Have emailed reporter and asked them to see if 3.6.9 resolves the issue.
