### ISSUE TITLE
[Notes] in 3.6.8

### ISSUE THREAD

**Issue by billsimoni** [vassalengine/vassal#11818]
Since release of 3.6.8, notes put into the notes feature of modules are entered right-to-left instead of right-to-left.

Validated with 3 users across several modules (Next War Indian Pakistan, Combat Commander Europe, and Commands and Colors Ancients). Have not tested beyond that.

**Comment by uckelman** [comment]
We're aware of the problem. It's already been fixed in PR 11805, which will appear in the 3.6.9 release. Thanks!
