### ISSUE TITLE
[Talon] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\vassal separate impulse tracker bar3.png:1,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11816]
| ABR | |
|-----|-----|
| Version | 3.6.8 |
| Reporter | chris@suffern.com.au |
| Error Log | [11811 bytes](https://vassalengine.org/files/gh/610909d35c619ccdb1eddb95bce375f7a5c60381) |

<pre>Information when bug occured:

Vassal 3.6.8
Talon.v1.4.vmod
Talon1000.v1.4.vmdx

Press the "show floating impulse round tracker" button.

Works for my friend. But I get an error.

Talon v1.4 3.6.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\vassal separate impulse tracker bar3.png:1,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment]
Emailed user to clear tile cache
