### ISSUE TITLE
[Liberté] Error: Invalid escape character at line 1 column 14.

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11847]
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter | markben61@gmail.com |
| Error Log | [567073 bytes](https://vassalengine.org/files/gh/53b2cf44e37df82636976c72094e44b608639e3f) |

<pre>Tried inserting an escaped unicode character (computed) into a mouseover text string. 

Liberté v1.0.6 3.6.9

java.lang.Error: Invalid escape character at line 1 column 14.
 at bsh.JavaCharStream.readChar(JavaCharStream.java:331)
 at bsh.ParserTokenManager.jjMoveNfa_0(ParserTokenManager.java:1899)
 at bsh.ParserTokenManager.jjMoveStringLiteralDfa0_0(ParserTokenManager.java:271)
 at bsh.ParserTokenManager.getNextToken(ParserTokenManager.java:2102)
</pre>

**Comment by riverwanderer** [comment]
worked around the issue by encapsulating the entire html in a series of global properties and calculating which GP to use, rather than calculating the HTML string itself.

**Comment by riverwanderer** [comment]
I would say this was a user error or just something that beanshell can't / won't support.
