### ISSUE TITLE
Having cargo on a mat disables the mat's Return to Deck - intended behavior?

### ISSUE THREAD

**Issue by assaultdoor** [vassalengine/vassal#11885]
If a mat has cargo and also a Return to Deck property, the Return to Deck property is disabled. I can see why this might be intended behavior, but I'm assuming it is unintended because I can't find a mention of it in documentation for Return to Deck, Mat, or Mat Cargo.

**Comment by BrentEaston** [comment]
Yes it is intended. Mats with loaded cargo cannot be added to Decks, only empty Mats can be added to Decks,

**Comment by BrentEaston** [comment]
@assaultdoor Are you happy if I close this issue?

**Comment by assaultdoor** [comment]
Yeah, that seems to be reasonable behavior. I just wish it hadn't taken me so long to figure it out.
