### ISSUE TITLE
[Memoir '44] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11923]
| ABR | |
|-----|-----|
| Version | 3.6.10 |
| Reporter | jeronimon@live.nl |
| Error Log | [18724 bytes](https://vassalengine.org/files/gh/151cb1480dcb891d03fa34fac6d8fc736add6bac) |

<pre>I was looking at a scenario of Memoir'44. (Vassal 3.6.10 Memoir modules 10.15 )And I did not see the picture op the unit. I did see the outline and the number of figures it should comprise of. Then I pend the UNit window and did not see any units depicted (yet?) and this window popped up

Memoir '44 v10.15 3.6.10

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3419)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3405)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:446)
</pre>

**Comment by AsaiToshiya** [comment]
Duplicate #10886.
