### ISSUE TITLE
[Campaign for North Africa] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\CNA Map Vassal Mitch Guthrie 2021.png:4,4@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11952]
| ABR | |
|-----|-----|
| Version | 3.6.11 |
| Reporter | minebololxd@gmail.com |
| Error Log | [190746 bytes](https://vassalengine.org/files/gh/b2a6b5aacf39210dc482b930d332d6e597f3d59a) |

<pre>I was basically doing the setup for the Campaign for North Africa (desert fox) and I saw this error. It occures whenever I try to finish the setup.

Campaign for North Africa v1 3.6.11

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\CNA Map Vassal Mitch Guthrie 2021.png:4,4@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
#10937
