### ISSUE TITLE
[Pax Renaissance (Solo)] NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "piece1" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11955]
| ABR | |
|-----|-----|
| Version | 3.6.11 |
| Reporter |  |
| Error Log | [83551 bytes](https://vassalengine.org/files/gh/64d9003651d480a8111cc33bbdb030bfa1088985) |

<pre>This is my second report on this issue. My problem is with the deck SORT element. It crashes every time I try to sort a deck.

Each piece in the deck has a dynamic property called "sort," which has values ranging from 0 to 2.
When I set up the Sort element, I specified integer, ascending, and in separate test the sort property as:
sort
"sort"
{"sort"}
$sort$

All crashed. I even tried specifying a global property called "sort" which contained "sort" as a value, and I specified the field as both sort and $sort$. All crashed.

Finally, I tried sorting on a marker instead of a dynamic property. Nothing worked, and I have no idea what to try next.

Pax Renaissance (Solo) v4.1 3.6.11

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "piece1" is null
 at VASSAL.build.module.map.deck.SortParameterComparator.compare(SortParameterComparator.java:52)
 at VASSAL.build.module.map.deck.SortParameterComparator.compare(SortParameterComparator.java:28)
 at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
 at java.base/java.util.TimSort.sort(TimSort.java:220)
</pre>

**Comment by Cattlesquat** [comment]
Brent could you check this one out -- it looks like it's trying to compare "null objects"  in the Deck sort... and it *looks* like maybe could it possibly get using the whole `contents` *array* rather than "only the active bits of it"? Since Deck's contents are stored in an old-fashioned array instead of a List that definitely wouldn't have null elements?
