### ISSUE TITLE
[Root by Merk Fixed] NullPointerException: Cannot invoke "VASSAL.build.module.Map.getEdgeBuffer()" because "map" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12042]
| ABR | |
|-----|-----|
| Version | 3.6.12 |
| Reporter |  |
| Error Log | [96419 bytes](https://vassalengine.org/files/gh/46ee1257f5771997346fa5539423035caf9353cb) |

<pre>copied a folder 4 folders containing 1 deck and a piece that count the suits of deck's contents each from a window(decree) to a different window(retainers), deleted the 4th folder, manually replaced the word "decree" with the word "retainer" in each deck's name, the counter's name and the text labels of the counter's, started a new game to test it, i did not reposition any of the decks yet

Root by Merk Fixed v2.8.2 3.6.12

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.Map.getEdgeBuffer()" because "map" is null
 at VASSAL.build.module.map.SetupStack.setup(SetupStack.java:269)
 at VASSAL.build.module.map.DrawPile.setup(DrawPile.java:1225)
 at VASSAL.build.module.GameState.setup(GameState.java:542)
 at VASSAL.build.module.PredefinedSetup.launch(PredefinedSetup.java:225)
</pre>

**Comment by MiROOOOOOOOOOOO** [comment]
funnily enough the decks and counters work, even though it error'ed and gave me the bug reporter window
