### ISSUE TITLE
Inaccurate Hex Grid location reports

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12070]
A hex grid set up with $gridLocation$ reporting will report an inaccurate LocationName. Initial investigation suggests that Vassal is determining the $gridLocation$ on the basis of a rectangular grid.

Perhaps this problem only affects mouse-over most of the time, as typical grids will have snap-to-location turned on. Impact on Mouse-over is typically that the mouse-over will seem difficult to trigger but also the mouse-over will be liable to trigger on the adjacent location instead. As shown by this simple example; a hexgrid with locations drawn in and a mouse-over reporting the LocationName incorrectly:
![image](https://user-images.githubusercontent.com/58135975/222720226-f7936bbd-26d5-4f49-967d-28e2ed2a88ac.png)

Confirmed in Vassal v3.6.14 and in v3.2.17.

Demo module, with maps for both orientations of hex grid: 
[test hexgrid locations.zip](https://github.com/vassalengine/vassal/files/10881994/test.hexgrid.locations.zip)

**Comment by BrentEaston** [comment]
Hi Mark (@riverwanderer),

The viewer was designed assuming the mouse is held over a counter and the location information is taken from that counter. The no-counter behaviour counter was added later and uses a heuristic to determine the 'best guess' for the location which does not work well in the hex corners The calculations to get that exact would be complex and expensive.

However, even given that, something is off in your module, the hex grid co-ords being reported are off by about 1/4 hex, an issue that I cannot reproduce in my noddy test module. Will investigate further,

Brent,

**Comment by riverwanderer** [comment]
I have tested #12340 and done some further investigation. To start off with, it seems there are two distinct problem areas visible from the demo. These are illustrated below for "pointy top" (Vauchamps in the demo) and "flat top" (Montmirail in the demo).

![image](https://github.com/vassalengine/vassal/assets/58135975/4bb0e18c-2241-4157-83d2-08792a2b1078) ![image](https://github.com/vassalengine/vassal/assets/58135975/2720fb72-b366-468e-849f-d6b632269619)

The blue area (essentially a right or upwards shift of the detected location) is FIXED by #12340. The yellow areas also have a problem and this persists in the PR.

The blue problem area was not visible at all in the module (C&C Nap) that triggered my initial awareness of the issue. So I looked into the difference. It seems that the blue issue is caused when the Hex Grid is set to snap to edges. This may explain why @BrentEaston was unable to reproduce in his own test module. My demo is based on a module where edges and vertices snap.

The yellow area problem exists regardless of snap configuration but the extent and nature of the error varies with combinations of snap to edges/snap to vertices, including (as in C&C Nap) when both are turned off. This can be seen in the demo module by editing the Hex Grid configuration. 

Example using the PR build with demo (Vauchamps) but with Snap to Edges and Vertices turned OFF; in both cases the cursor sits below the LocationName display, and well within hex 2007.
![image](https://github.com/vassalengine/vassal/assets/58135975/b4baf397-f2e7-4720-bf85-ccc9961a1eb7)

**Comment by riverwanderer** [comment]
I tested latest #12340 fix and it works perfectly in the test module and also in empty locations in the C&CNap module. I also tried some piece movement on & across edges/vertices in the test module and that also seems to work fine - i.e. decent enough estimate of where I was trying to put the piece.

I still have the main issue in the C&C Nap module and on re-reading @BrentEaston's original response I can see that it may have a different cause. That is, Vassal fails to rigger a **piece** mouseover in some peripheral areas of a hex. As @BrentEaston points out "the location information is taken from that counter", but something is preventing this and the pattern of failure seems very similar to the one exhibited in the "empty hex" that #12340 certainly fixes.

Example, from C&CNap (current dev):

This mouseover should display when the cursor is over any part of the hill terrain except where the overlying unit is. In this case, the cursor is approximately at the lower right have corner of the light brown text box (the mouseover box). However, that is well inside the hex and this is about as near to the right hand edge as I can go and still get the mouseover:
<img width="100" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/c447d444-1428-4a24-ab2d-0e2cfed2f159">

Further away (here about half way between the righthand edge of the hex and the edge of the unit (blue) piece, and a default LocationName mouse-over triggers, indicating that Vassal has failed to detect the underlying terrain piece.
<img width="79" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/02b8ecfa-3e37-4b5e-985d-68dae978dcb5">

 Increasing the virtual piece size with a zoomed up [Non-Rectangular](https://vassalengine.org/doc/latest/ReferenceManual/NonRectangular.html#top) trait does mitigate the issue but I'm not sure that this is a reliable solution (too much and it ends up triggering the mouse-over on adjacent pieces).

**Comment by riverwanderer** [comment]
Turns out the original cause of my report, expounded on in my previous update, was simply that the Non-Rectangular trait on the terrain tiles was smaller than the tile itself. Thanks to @yetanotherdevaccount for helping me find this out. I can now address it in the affected module(s).

It was coincidental that my test case demo'd a general vassal issue, now fixed by #12340.
