### ISSUE TITLE
[Pendragon] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/Card Display.jpg:0,5@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12081]
| ABR | |
|-----|-----|
| Version | 3.6.14 |
| Reporter | mrkptrs1@yahoo.com |
| Error Log | [10553 bytes](https://vassalengine.org/files/gh/6a6cc1f04dd84673e2ff8ec3f7f65477fc7b7dda) |

<pre>opening PENDGRAGON Save File

Pendragon v1.2 3.6.14

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/Card Display.jpg:0,5@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Fixed by #12231.

**Comment by Cattlesquat** [comment]
Fixed by #12231
