### ISSUE TITLE
[Sandstorm: WW2 in North Africa] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Additions.jpg:7,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12099]
| ABR | |
|-----|-----|
| Version | 3.6.14 |
| Reporter | hmarrighi@gmail.com |
| Error Log | [16188 bytes](https://vassalengine.org/files/gh/b065d1d7ba4385624d7e5441eef7f0bd276f7202) |

<pre>Editing a module, attempting to reposition a newly created deck in a map window. I had opend another deck properties to ensure the current deck had teh same properties.

Sandstorm: WW2 in North Africa v0.193.2 3.6.14

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Additions.jpg:7,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:321)
</pre>

**Comment by uckelman** [comment]
Fixed by #12231.

**Comment by Cattlesquat** [comment]
Fixed by #12231
