### ISSUE TITLE
Piece that moves to a new map window as a result of a GKC can get the GKC multiple times

### ISSUE THREAD

**Issue by assaultdoor** [vassalengine/vassal#12116]
The attached module contains exactly one piece, which is on Main Map. Right-clicking and selecting Do The Thing causes it to send a GKC (DoTheThing) to all pieces in the game. When the only piece gets that GKC, it does two things. First, it moves to Other Map. Second, it reports its current map in the chat. I would assume that sending it to Other Map would cause exactly one report to show up in the chat. However, we get two of them.

If you tell it to Do The Thing while it is on Other Map, you only get one report.

Also, if you edit the module so the piece starts on Other Map and is sent to Main Map, you only get one report.

If you open the attached module in the editor, Main Map comes before Other Map in the list of stuff. However, if you edit the module so that Other Map is the piece comes before Main Map, the situation is reversed. You get one message moving the piece from Main Map to Other Map, and two messages moving it from Other Map to Main Map.

I assume from this that VASSAL starts with the top map in the editor window, makes a list of pieces on that map that should get the GKC, sends the GKC to each of those pieces, and then repeats this for the next window down.

Enabling fast matching doesn't seem to alter this behavior, in case you were wondering. I set the GKC to filter by BasicName and got the same results.

I can imagine some creative uses for this, but I assume it is not intended behavior.

[blank.zip](https://github.com/vassalengine/vassal/files/11012077/blank.zip)

**Comment by riverwanderer** [comment]
Seems sensible that a given piece should only process a given GKC command once, especially as the duplicate processing is order-dependent.

If I've understood the problem right, then to operate with current Vassal, would need the GKC split into one for each map, perhaps with a Dynamic Property on pieces that can be used to prevent processing a piece that has been moved by the first GKC.
