### ISSUE TITLE
Change-Property null reports generate a spurious newline.

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12155]
PR #12004 fixed the issue of blank Action Button reports generating a new line.

Could the same be applied to Change-Property ?

e.g. to put out a report when a property change reaches a certain threshold (e.g. zero) requires a Beanshell conditional, on which the false side is a null report. At the moment this will generate a spurious newline.

**Comment by Cattlesquat** [comment]
I'm afraid I don't actually understand what trait or item we're talking about here, and where I would find one in the module?

**Comment by riverwanderer** [comment]
> I'm afraid I don't actually understand what trait or item we're talking about here, and where I would find one in the module?

It's the Change-property Toolbar menu item;
<img width="357" alt="image" src="https://user-images.githubusercontent.com/58135975/228775463-1b656080-2e47-4ae3-93a8-03541324d210.png">

Here is a menu module:  [DemoIssue12155.zip](https://github.com/vassalengine/vassal/files/11109446/DemoIssue12155.zip)
