### ISSUE TITLE
Chat image distortion

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12167]
Vassal v3.7 (from pre-release to beta2) distorts graphics from html tags.

Example, pre v3.7:
<img width="136" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/58135975/229266831-80478cbe-2900-4d34-9756-ad88febb7377.png">

Same output under v3.7-beta 2:
<img width="175" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/58135975/229266845-4c674138-f2de-4fb6-b3d2-262272744efe.png">

Clocks image is encoded in this html: `<img src="nap clocks button.png" width="39.9" height="22">`
Others are similarly encoded.

**Comment by Cattlesquat** [comment]
(also, a link to a good version of module to test with, and how to produce at least one of these from starting up)
