### ISSUE TITLE
[Imperial Struggle] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Bottom Strip.png:5,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12190]
| ABR | |
|-----|-----|
| Version | 3.6.15 |
| Reporter | emmanuele.kizito@gmail.com |
| Error Log | [12119 bytes](https://vassalengine.org/files/gh/4e3c5004edf22de093560bf57d1ea74fd3b00f91) |

<pre>Scrolling down the map. I tried to install both v3.6.15 and 3.6.16 but nothing change.

Imperial Struggle v3.0 3.6.15

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Bottom Strip.png:5,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
Fixed by #12231
