### ISSUE TITLE
[VASL] IllegalStateException: No state for Decorator=label;76,130;Label;14;;0,0,0;c;-8;c;0;c;c;$label$;Dialog;0;0;TextLabel;;false

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12228]
| ABR | |
|-----|-----|
| Version | 3.6.15 |
| Reporter |  |
| Error Log | [21468 bytes](https://vassalengine.org/files/gh/b59769bcd20e4f3933477f042001900c48291140) |

<pre>I was trying to open a saved game file

VASL v6.6.6.1 3.6.15

java.lang.IllegalStateException: No state for Decorator=label;76,130;Label;14;;0,0,0;c;-8;c;0;c;c;$label$;Dialog;0;0;TextLabel;;false
 at VASSAL.counters.Decorator.setState(Decorator.java:346)
 at VASSAL.counters.Decorator.setState(Decorator.java:343)
 at VASSAL.counters.Decorator.setState(Decorator.java:343)
 at VASSAL.counters.Decorator.setState(Decorator.java:343)
</pre>

**Comment by Cattlesquat** [comment]
>>This save was created with Module version '6.6.6' but you are running '6.6.6.1'

Loading saved game from earlier version of the module.
