### ISSUE TITLE
[Fire in the Lake] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\FITL Map VASSAL.jpg:12,12@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12269]
| ABR | |
|-----|-----|
| Version | 3.7.0-beta2 |
| Reporter |  |
| Error Log | [38502 bytes](https://vassalengine.org/files/gh/1074c718acb182c195ad8fd700077706a33cfc5a) |

<pre>

Fire in the Lake v3.0 3.7.0-beta2

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\FITL Map VASSAL.jpg:12,12@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:321)
</pre>

**Comment by Cattlesquat** [comment]
I'm not sure Beta2 even has the fix for that

**Comment by uckelman** [comment]
3.7.0-beta2 didn't. The fix was in 3.6.16, but that went out after 3.7.0-beta2.
