### ISSUE TITLE
Editing Irregular Grid can corrupt the ordering of grids in a [Zone]

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12261]
When an Irregular Grid is edited, whether to add a new Region or amend position of an existing Region, the order of the Irregular Grid may change in the module, which in turn may cause positioning errors when the module is used.
[](url)
Example where I have seen this:

<img width="199" alt="image" src="https://user-images.githubusercontent.com/58135975/234511339-0c6c9279-877b-4b58-9a4f-d09babe7cb60.png">

When I edited some of the Regions shown in the Right [Zone] [Irregular Grid], I found that the [Hex Grid] gets moved below the [Irregular Grid].  This was causing Sent to Location to the Region points to be over-ridden by the [Hex Grid]'s "Snap to Grid".

It's quite possible that I could re-configure my grids to avoid this issue but nonetheless it seems like a bug that the editor shifts the grids around after an edit of other components.

This occurs in current v3.7 snapshots but I've seen it in earlier versions too. Example module,  [Commands & Colors: Napoleonics](https://vassalengine.org/wiki/Module:Commands_%26_Colors:_Napoleonics). Zone "Right" can be found on the Main Map.

**Comment by BrentEaston** [comment]
It should actually be illegal to have both a hex grid and an Irregular grid in the same Zone. It's like having both a hex grid and a square grid, it doesn't make any sense. 

The correct fix is actually to generate a 'No more than one [MapGrid] allowed in xxx [Zone]'  error when you save the module.

If this has resulted in any sort of useful functionality it is completely by chance and totally unintended.

What functionality are you using? From your description, sounds like you are using the Irregular grid to create hidden named points over the top of a hex grid that you use in SendToLocation as Named goto points? If this is the case, then try creating a second grid Right2 below Right that is the same size and put the irregular grid points in that.

**Comment by riverwanderer** [comment]
Thanks @BrentEaston. I think you grasped my overall aim which is to have these points defined (mainly for StL) but other parts of the zone snapping to the hex grid.  I will re-look at what I'm doing and compare with another module where I may have done similar but without the issues (perhaps I did it the way you suggest there) - starting to think that I stumbled into error; so, yes a warning would help.

**Comment by riverwanderer** [comment]
In C&C Napoleonics, that Right/Right2 idea doesn't work in the end because the hex grid snap-to-grid kicks when Send to Location drops the marker onto a Region point.  Thanks for advising because I can now see that I just need to drop the Hex Grid and add in some Region Points that approximate to the Hex Grid, that will give me the outcome I need.

In another module (Liberté), an Irregular Grid is defined across the board, overlaid on zones which contain other irregular or rectangular grids.  It all works but I now understand that I could have put the board-level irregular grid points ("regions") into related zones.  There are about 3 Regions defined  in locations that fall into or close to Regular Grids; I recall that that is where I had difficulty when developing the module, and it's likely that I stumbled my way around this issue until I got something that worked. 

If you were to introduce an error message, I'd probably be able to re-design the grids to be compliant and working.

![image](https://user-images.githubusercontent.com/58135975/235292671-a951bab2-af8a-4a4d-b538-91978478f1a0.png)

**Comment by BrentEaston** [comment]
I have added the error message to 3.7beta via build 12261-MultiGridError

**Comment by riverwanderer** [comment]
Works for me, adding this hex grid,
<img width="212" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/550c8b6d-04a8-4eaa-9bdd-1ecb19397e4b">

 I get this error message on save, which will be a good reminder not to try this in future.

<img width="392" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/e95a4fdf-4c53-496f-a00d-78440df03cba">
