### ISSUE TITLE
Items selected & dragged from one Function Builder field to another are not reflected in the resulting expression

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12287]
Example:

LocationName was original in the in the Property Name field. It was selected and dragged the fields below. However, this UI action has not been reflected within the Function Builder result.

<img width="815" alt="image" src="https://user-images.githubusercontent.com/58135975/236878145-806bc9a6-210f-4ace-ad86-10eeeaeac76e.png">

This error shows up in other Function Builders too, including ones prior to the v3.7 development.

**Comment by BrentEaston** [comment]
I don't believe text drag and drop functionality has been enabled anywhere in Vassal.

**Comment by riverwanderer** [comment]
It may be a Mac thing but generally I find that text drag & drop works in the editor and the player. After a bit more experimentation I find that the problem is with the **_Expression Builder_** as a whole and then only if nothing else is typed into either of the two fields that were changed by the drag & drop operation.

It is as if the Expression Builder doesn't react to the text drag & drop event, so internally it keeps the same representation of the text panel contents that it had before.

**Comment by BrentEaston** [comment]
Hi @riverwanderer ,

Can you please try the latest master? I added a change to turn on text DnD and it seems to work in Windows. Can you see if this resolves your issue with the Expression Builder on Macs?

Thanks,
Brent.

**Comment by riverwanderer** [comment]
Hi @BrentEaston, you might have missed my comment on Discord when you did the original DND build...

_"I tried the new build but it makes no difference, good or bad. I wonder if the Drag & Drop thing that I am seeing is a native MacOS feature (if that makes any sense). Such that the Java / Vassal code is unaware of it but that mostly happens to work, except in a special case like the expression builder result field ?"_

I just tried the latest FR build, which I think is built on the latest master and that is the same, no difference on MacOS.

If you still need me to test that last master specifically, let me know.

**Comment by BrentEaston** [comment]
Hi @riverwanderer,

Latest FR build is about 3 weeks behind master and doesn't have the DnD change. Can you please try the latest master build? It definitely turned text drag and drop on for Windows when it wasn't there at all before. I agree, what you are seeing now is a MacOs level thing, interested to see what this change does for you.

**Comment by riverwanderer** [comment]
@BrentEaston - tested master VASSAL-3.7.0-SNAPSHOT-d7be23f-master-macos-x86_64.dmg ; same result, i.e. I can still drag and drop text fields but the RESULT field still does not update unless I go into the field(s) affected by the drag/drop operation and do some edit in each - e.g. add / delete a character... then the drag/drop change is effected.

I conclude that the Vassal editor knows what is in the fields but there's no trigger from the original drag/drop operation to get the result field to update. As well as drag/drop text working; does you also observe this last bit working ok on Windows ?

**Comment by BrentEaston** [comment]
@riverwanderer,
In the latest Master, test drag and drop now works as expected under windows including in the Function Builder fields, whereas it did not work at all before. It seems that you are seeing some sort of interaction/fight between Java Swing text Dnd and Macos level Dnd.

**Comment by BrentEaston** [comment]
Hi @riverwanderer ,

Can you please check if this is resolved for you on MacOS in the latest master?

Thanks.

**Comment by riverwanderer** [comment]
Tested in VASSAL 3.7.0-SNAPSHOT-8c4bdf8-master. Still fails to update the "results" field purely from DnD.

**Comment by BrentEaston** [comment]
@riverwanderer Is this usable on MacOS (just doesn't work well), or does it break your experience and we need to pull this change out?

**Comment by riverwanderer** [comment]
The change made no difference to me so if it's good for Windows or elsewhere, go for it, as far as I'm concerned.

The original issue is not a big deal either, once you know to expect it.

**Comment by BrentEaston** [comment]
Thanks Mark.
