### ISSUE TITLE
Rotate trait "Rotate direct to" doesn't work on a Piece Palette

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12309]
Perhaps intentional but other rotate features do work on a Piece Palette.

Example usage where a Rotate Direct command is ignored:
<img width="913" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/d36cdfb7-41a6-4467-9a5f-ab2a9ee8f311">

I tried the same trait with $gTmp$ changed for a literal number (4) and the problem still occurs.

Noticed under a recent v3.7 dev build but probably occurs since Rotate direct became a feature.

**Comment by Cattlesquat** [comment]
Rotate direct should work (by itself) in a piece palette but of course cannot evaluate any kind of property which won't exist in the piece at that point. What sends "adjPos" trigger? That might likewise be something that can't happen in a piece palette where the piece doesn't "really" exist yet. If you changed the key command to e.g. Alt+R and the rotate direct field to e.g. 45 I imagine it would work

**Comment by riverwanderer** [comment]
That'll be it, thanks @Cattlesquat.
