### ISSUE TITLE
Contents of Global Option tabs with null names not initialised - at least for CheckBox

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12363]
Two demos show the issue; one identical apart from the Global Option tab in one is blank and this seems to cause the CheckBox property to be left null (when defined unchecked). It should initialise to "false", as seems to be the cause if the tab is named.

Run the pre-defined game under file menu in both modules, observe the reported values/mouseover a piece and compare results.

[cat & mouse-overOK.zip](https://github.com/vassalengine/vassal/files/11692659/cat.mouse-overOK.zip)
[cat & mouse-overNOK.zip](https://github.com/vassalengine/vassal/files/11692660/cat.mouse-overNOK.zip)

**Comment by BrentEaston** [comment]
Reproduced.

At the moment, Global Options that do not have a tab name do not get created at all as they are meant to be implemented as preferences in tab,

Is the purpose of not having a Tab name to create 'Invisible' Global Options that cannot be changed during the game?

There is a provision for creating invisible preferences, so I believe I can make this work as you expect,

**Comment by riverwanderer** [comment]
> Is the purpose of not having a Tab name to create 'Invisible' Global Options that cannot be changed during the game?

Correct.  Therefore the module can store player-specific data that can't be edited by the players. A simple example would be a formatted player name. Players may indirectly change this data, of course.

These 'invisible' global options do work, at least when initialised via the "Set Global Property" trait.

**Comment by BrentEaston** [comment]
Hi @riverwanderer,

Please try the new 12363-GlobalOptionsinitialisation build.

**Comment by riverwanderer** [comment]
Tested ok both with the demo failure (now succeeds) and a full module that was global option properties on a blank tab.
