### ISSUE TITLE
UnDo breaks Auto Attach

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12393]
Incident in [CCN v4.2 dev module](https://www.dropbox.com/s/ulffyqbpfgv4m6n/CCNapoleonics4_2_0.vmod?dl=0), using Vassal 3.7beta4.

In the module, auto Attachment `oppMkr` is created between Attacker and Target marker. These markers are created as unique instances and normally, when both are in the game, `oppMkr_AttachCount` is 1 on each marker.

However, following the creation of the second marker an UnDo of that creation leaves `oppMkr_AttachCount` at 1. Subsequent marker creation bumps `oppMkr_AttachCount` to 2. Associated with this, module functionality fails as it relies on the 1-1 attachment structure between these markers.   Further similar UnDos generate increments in `oppMkr_AttachCount`.

A normal delete of one of the markers does reduce the `oppMkr_AttachCount`.

To demo in the above module:
1. Start module; set the Diagnostics checkbox on the Preferences...Game Options panel.
2. Start a scenario, connecting as Solitaire, one of the player hand's will have an active "Deal Cards" button. Press it and then click/play a card.
3. Now drag any Infantry or Cavalry piece adjacent to an opposing piece; click on both those pieces; the yellow and red markers should appear. Once both markers are in place for a valid combat, the Combat Assist widget to the right of the board will display a number (as opposed to "X").
4. Mouseover on the red and yellow pieces. Note the value of `oppMkr_AttachCount` is reported as 1 on both pieces.
5. Now UNDO. The last marker placed should disappear. Mouser on the remaining piece;  `oppMkr_AttachCount` is still 1.
6. Bring another opposing piece adjacent, if not already there. Click on that. The marker will appear but the Combat Assist widget still displays "X".  Mouseover now shows `oppMkr_AttachCount` as 2 but there is only 1 marker (the opposite side) attached!

**Comment by riverwanderer** [comment]
Workaround: UnDo issue doesn't seem to arise when I substitute the Auto-Attach traits with a reciprocal pair in the following form (this is for the red dot piece to attach to the yellow dot piece, the  yellow dot piece has similar with different search criteria):

<img width="901" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/867c9dd0-6876-4464-95be-5f8089b154a8">

**Comment by BrentEaston** [comment]
Thanks Mark,
I have reproduced it in a simple way.
- Create a counter with Auto-attach on that displays its' current attach count.
- Pull out 3 counters (attach count=3), then undo(attach count=2), then pull out a new counter. attach count goes to 4.
