### ISSUE TITLE
Replace With Other retains existing Marker values when Match Current State is checked

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12392]
Example, the following trait replaces a piece that includes a Marker called MaxStrength with value 3 with a similar piece where MaxStrength has value 4. The new piece however retains value 3.

I was not expecting this because a Marker has a fixed value, so the idea of that being in scope of "Match Current State" seems a little off. Doubly so, because a workaround of replacing the Marker trait with the equivalent Dynamic Property appears to resolve the issue. The DP is simply set to initial values of 3 and 4 respectively, with no other attributes defined.

<img width="757" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/480432a6-21b7-40bf-9197-9702fe4e1af8">

**Comment by BrentEaston** [comment]
This is expected behaviour. The value of the marker is the Marker's state. Even though it is fixed for that piece. it can vary between different pieces that have the same Marker defined, so it has to be defined in the piece's state. 

The mystery to me is why the DP version works for you. I suspect this is by chance because the Type is different between the DP's possibly a different description? If the DP in the before and after counter where identical (except for value), I suspect you would have the same problem,

Given that the you want the value to change, the workaround is to use DP's with different descriptions in the main counter and the replacement counter.

**Comment by riverwanderer** [comment]
Thanks @BrentEaston . Yes, the description of the Dynamic Property does indeed differ slightly, so I guess that is why it works.

In case I didn't explained clearly enough. Let's say Piece A is the piece with a "Replace with Other" trait, and Piece B is that Other piece. Suppose the pieces are defined with these traits:
Piece A, Marker X = 1, Dynamic Property Y initial value 1
Piece B, Marker X = 2, Dynamic Property Y initial value 2

When Piece A does its "Replace with Other" using Piece B, Piece B is created with Marker X = 1 and DP Y = 2

As I said the DP description does differ. On the other hand, the DP's **initial Value** is also different between the pieces. Wouldn't that also be enough for Replace with Other to ignore it when preserving the "state" ?

I understand how the Marker trait can have a different value between pieces, in fact that is the case here. I missed that the Marker's value, with no other identifying feature on a Marker Trait, would qualify to be changed (ie preserved) courtesy of Replace with Other. I guess I was expecting the Marker trait to be just excluded from the whole process.

**Comment by BrentEaston** [comment]
> As I said the DP description does differ. On the other hand, the DP's initial Value is also different between the pieces. Wouldn't that also be enough for Replace with Other to ignore it when preserving the "state" ?

No, Because the value is 'state', the definition of the DP is 'type'. The initial value of the DP is just loaded directly into the 'state', it does not appear in the 'type', so the replace can't check this. The initialValue is just over-written the next time the DP is set.

The ReplaceWithOther matchState probably should skip Markers and DP's

**Comment by BrentEaston** [comment]
@riverwanderer I've created a new build 12392-ReplaceWithOtherOption that defaults to not copying Marker or DP values. There is a new option in Replace with Other if you want this functionality.

We may have to reverse the default though. While coding, I realised there is a good use case for copying DP values. If you set your DP up in the replacement exactly, then the replacement currently gets a copy of the existing value of the DP without having to fluff around with transmitting it. I suspect there will be modules that depend on this functionality.

I actually don;t think there is ever a case for copying Marker values, so I'm thinking the best way forward is:

1. Markers never copy state under any circumstances.
2. By default, DP's do copy state, but can be turned off by the new Replace With Other option 'Do not copy value of Dynamic Properties'.

I think that gives us the best of all worlds. Your original coding using Markers will work, existing behaviour is maintained for DP's, but can be over-ridden.

I am pushing that change now.

**Comment by BrentEaston** [comment]
New version building.

**Comment by riverwanderer** [comment]
A [module](https://www.dropbox.com/s/8novddbg1zcxw9c/CCNapoleonics4_2_0.vmod?dl=0) previously saved in Vassal v3.7-beta4 does not fully open with the new build.  Vassal log file follows.

The startup gets as far as displaying the main module menu but no other application menus or windows appear:
<img width="746" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/85d3c8eb-8476-4d3d-8c26-77eed1a81f7c">

This module does still open under beta4.
A previous version of the module, saved under V3.6.19, does open normally. When that version is saved under beta4, it still opens under the new build.

```
2023-06-26 22:35:07,714 [18815-main] INFO  VASSAL.launch.StartUp - Starting
2023-06-26 22:35:07,723 [18815-main] INFO  VASSAL.launch.StartUp - OS Mac OS X 13.4.1 x86_64
2023-06-26 22:35:07,723 [18815-main] INFO  VASSAL.launch.StartUp - Java version 20.0.1
2023-06-26 22:35:07,723 [18815-main] INFO  VASSAL.launch.StartUp - Java home /Applications/VASSAL-3.7.0-SNAPSHOT-b29a484-12392-ReplaceWithOtherOption.app/Contents/MacOS/jre
2023-06-26 22:35:07,723 [18815-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.7.0-SNAPSHOT-b29a484-12392-ReplaceWithOtherOption
2023-06-26 22:35:07,946 [18815-AWT-EventQueue-0] INFO  VASSAL.launch.ModuleManager - Manager
2023-06-26 22:35:13,419 [18815-SwingWorker-pool-1-thread-1] INFO  VASSAL.launch.AbstractLaunchAction - Loading module file /Users/Mark/Library/CloudStorage/Dropbox/Vassal Test Releases/CCN4/CCNapoleonics4_2_0a22.vmod
2023-06-26 22:35:13,619 [18815-SwingWorker-pool-1-thread-1] INFO  VASSAL.launch.TilingHandler - No images to tile.
2023-06-26 22:35:13,620 [18815-SwingWorker-pool-1-thread-1] INFO  VASSAL.launch.AbstractLaunchAction - Loading module Commands & Colors: Napoleonics
2023-06-26 22:35:13,623 [18815-SwingWorker-pool-1-thread-1] INFO  VASSAL.tools.io.ProcessLauncher - launching /Applications/VASSAL-3.7.0-SNAPSHOT-b29a484-12392-ReplaceWithOtherOption.app/Contents/MacOS/jre/bin/java -Xms1024M -Xmx1024M -Duser.home=/Users/Mark -Duser.dir=/Applications/VASSAL-3.7.0-SNAPSHOT-b29a484-12392-ReplaceWithOtherOption.app -cp Contents/Resources/Java/Vengine.jar -Xdock:name=Commands & Colors: Napoleonics -Xdock:icon=/Applications/VASSAL-3.7.0-SNAPSHOT-b29a484-12392-ReplaceWithOtherOption.app/Contents/Resources/VASSAL.icns -Dsun.java2d.opengl=true -Dsun.java2d.opengl.fbobject=false VASSAL.launch.Editor --edit -- /Users/Mark/Library/CloudStorage/Dropbox/Vassal Test Releases/CCN4/CCNapoleonics4_2_0a22.vmod
2023-06-26 22:35:14,072 [18817-main] INFO  VASSAL.launch.StartUp - Starting
2023-06-26 22:35:14,081 [18817-main] INFO  VASSAL.launch.StartUp - OS Mac OS X 13.4.1 x86_64
2023-06-26 22:35:14,081 [18817-main] INFO  VASSAL.launch.StartUp - Java version 20.0.1
2023-06-26 22:35:14,081 [18817-main] INFO  VASSAL.launch.StartUp - Java home /Applications/VASSAL-3.7.0-SNAPSHOT-b29a484-12392-ReplaceWithOtherOption.app/Contents/MacOS/jre
2023-06-26 22:35:14,081 [18817-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.7.0-SNAPSHOT-b29a484-12392-ReplaceWithOtherOption
2023-06-26 22:35:14,081 [18817-main] INFO  VASSAL.launch.Launcher - Editor
```

**Comment by BrentEaston** [comment]
Scrap that version, It's going into an infinite loop.

**Comment by BrentEaston** [comment]
Ok, On a completely fresh look at this, I could not even reproduce the problem!

Turns out that the Match current state option of Replace only actually works if the matching traits in the replacement are in EXACTLY the same order as they are on the source piece. Any that are out of order get skipped. So, for example, I had a Text Label as the last trait in the source and first in the target. The Text label gets state matched, then everything else is ignored because it is out of order. This means that the results people are seeing vary widely from not working to partly working to completely working depending on trait order.

So, I see three separate issues:

1. The trait order dependency is completely wrong . If there is a trait in the target that matches exactly a trait in the source, then if match traits is selected, we should do the match, regardless of trait order.

2. Markers (assuming trait order is correct) get their state copied from the original piece if match current state is selected. This is definitely wrong, Markers should never be state matched, we will always want the 'Replace' piece to have the new value of the marker it defines.

3. Dynamic properties need to be handled specially:
    3.1 If match current state is selected, we should 'match' just on Property name, not on the full type. The Property name uniquely identifies a DP, regardless if any of the other options have been changed.
    3.2 By default, I think DP's should be excluded from the state match process. The replacement piece should be created with the value specified in the replacement definition.
    3.3 Being able to copy the existing value of a DP over to a replacement piece is a really useful thing to do, saves a mass of mucking around, so I believe this should be enabled by a new Replace trait option. If you select to 'Match current state', then you get a new option 'Copy values of Dynamic Properties to replacement piece' (default no). This will need to be turned on specifically.

Thoughts?
Cc @Cattlesquat

**Comment by riverwanderer** [comment]
I was going to come on to the general twitchiness of state matching. I could not figure out whether it was me or a bug; you've now explained it, to test these changes, I can go back to where I was trying and failing to copy several traits in on of the new CCN module features!

1 & 2 are what I expected and got confused when it didn't happen that way. 

3.1 - Great! I was feeling that the match was too fussy, you've identified that it doesn't need to be for DPs. Guess you run into issues with other traits where the property name is allowed to be non-unique (at least if it's null, in my experience. e.g. Layer), which presumably is why the extensive matching exists.

3.2/3.3 Up to now, I would have used the "match above this trait only" option to exclude a DP. That can be awkward. However, I think DPs are often a mix of match/don't match - in which case, it's the only way, unless you have a flag on each DP trait which seems overkill.  I'm not sure 3.2 is really needed, but I'm just one user.  Also, I don't think 3.2 can become the default, as existing modules will be relying on 3.3 (or perhaps you handle this in conversion ?).

For sure, apart from not being sure about 3.2/3.3, the other changes will - for me at least - make state preservation much more predictable and easy to use.

Do these changes fall into the category of fixing bugs that modules might have been - perhaps unknowingly - relying on ?

**Comment by BrentEaston** [comment]
The problem with 3.2/3.3 is that current modules may or may not be dependent 3.3, dependent on whether or not they have fallen foul of issue 1.  Implementing 3.1 will also potentially affect the way it works now.

I think the best we can do is make something logical and consistent for all users. I am happy to reverse the option to make copying values of DP's the default, which does make sense,

**Comment by BrentEaston** [comment]
Ok @riverwanderer , new build 12392-ReplaceFix.

I have just done the basics
 - Matching no longer depends on trait order
 - Markers never matched
 - Dynamic Properties match on property name only (and will copy value as it does now).
I have not added a new option to Replace to handle DP matching specifically. I'm not sure it's needed (as you noted). DP's will match on property name and copy values by default. If you don;t want that, but want to match other traits, you can move the DP below the Replace trait in the source piece and turn on 'Only match traits below'.

Give it a try.

**Comment by riverwanderer** [comment]
Tested build 6f4ab11-12392-ReplaceFix.

Trait order doesn't affect matching - based on a simple test (swapping the order of a DP and a layer to be different in a pair of Replace with Other pieces).

Marker value is not matched (new value retained)

In my test case, the Dynamic Property trait does not initialise to the new piece's value and instead is set to the current value on the old piece. This is as expected now but I think it highlights a common case of straightforward inherited DP values  that will start failing if this change goes into v3.7 unabated.  Perhaps, the DP should at least match on Initial Value as well ?

One further adverse effect of this, is that the DP will even adopt a value that is outside the Min-Max range of the DP trait on the new piece.

In fact, from my experience - which may be mis-guided due to the confusing behaviour from the trait-ordering issues - the unwanted match-fails come from the "Key Commands" section. If this section is in fact not using for Typing, then I wonder if there really is a problem with existing DP matching behaviour ?

**Comment by BrentEaston** [comment]
Ok, 2 steps forward, one back. Guilty again of trying to fix problems that don't exist.

Unfortunately, the 'Initial Value' is only ever stored as the value (the 'state') of the property when the DP is created. It is lost as soon as the value changes.

The 'Type' of a DP includes everything EXCEPT the initial value:
 - Property Name
 - Isnumeric/max/min/wrap
 - Full details of Key Commands
 - Description

For compatibility, I agree, it is probably best if we leave it as is, that a replacement DP will only get the value copied over if it is an exact replica of the DP in the source piece.

**Comment by riverwanderer** [comment]
I wonder if Property Name and Isnumeric/max/min/wrap would be enough to uniquely characterise a DP ?
I suppose the issue is that most often the additional fields are not used and in some modules the additional checks allow the module to work as intended.

Even so,  Description is an identifier of last resort; at face value it should exert no influence on anything, and presents a likely snag, as it is the field that users are very likely to change between pieces.

Key Commands, may also be different between pieces when the initial value you want to inherit, even non-existent on the target piece. Due to the matching restriction,  all KCs have to be listed on both pieces.

How about, the DP trait gets a new checkbox - effective on the "Other" piece -   along the lines, "Replace with Other: match on property name alone"  ? (default clear). This would be backward compatible and would be more flexible for future module work. 

If pursuing this aspect is more hassle that seems worth it, fair enough. I am sure that the main problems I have ever had with Replace with Other were down to the trait ordering restriction.

**Comment by BrentEaston** [comment]
I think it is worthwhile adding that option. It allows you to just turn on a single option and have all DP's automatically transfer over (well , 2 options 'Match' plus 'DP by Name'). Or if you want more control, turn that option off, and then manipulate the Types and/or above/below options to control exactly which DP's transfer over.

Perhaps:
Copy Dynamic Property values where Property name matches?

I'm updating the documentation page as well with extra usage details.

**Comment by BrentEaston** [comment]
Ok, New version of build 12392-ReplaceFix going up now with the addition of the 'Copy Dynamic Property values where Property name matches?' option, No other changes

**Comment by riverwanderer** [comment]
> I think any more complicated than 1. Match name only or 2. Match everything exactly just becomes too complicated.

Fair enough. It's another tool in the kit bag that could be useful.

Tested build 12392-ReplaceFix - looks good. Specifically, in my test:

1. Defaults to not matching a DP with different value for Max (current behaviour).
2. The new checkbox forces the same DP to match.
