### ISSUE TITLE
Drag & Drop changes between folders in Extension are not saved

### ISSUE THREAD

**Issue by BrentEaston** [vassalengine/vassal#12403]
See forum discussion https://forum.vassalengine.org/t/editing-extensions/77363/15

Drag and drop of an entry is not updating the target path in the ExtensionElement XML in the buildfile. This causes the moved items to magically disappear from the target location and re-appear in the original location when the extension is saved and re-loaded

Ctrl-X/Ctrl-V is creating the correct new entry, but not deleting the old entry.

Issue present in both 3.6.19 and 3.7 beta

**Comment by BrentEaston** [comment]
See also #11337 where Drag and drop of Scenarios between folders causes them to become non-editable.

**Comment by BrentEaston** [comment]
New build VASSAL-3.7.0-SNAPSHOT-139ce7c-12403-ExtensionCutPaste available for testing

**Comment by riverwanderer** [comment]
This particular build zip file gives me this error. Others are ok, as usual.

<img width="378" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/1c66ef65-4f10-4144-bbb7-ff2343338b7f">

**Comment by BrentEaston** [comment]
Thanks Mark, I had some problems with the build. I have set off a new one. Should be ready in about 15 minutes,

**Comment by riverwanderer** [comment]
Pre-defined setup can now be edited once it is moved into an Extension [Pre-defined Setup] parent, also if it is duplicated within the parent.  However, on saving, the moved or duplicate PDS is lost.

**Comment by BrentEaston** [comment]
Lost? Or moved down below the C3i folders? When I tested, I thought they where lost initially as well.

![image](https://github.com/vassalengine/vassal/assets/1622667/c7023043-a227-48e9-b1f1-710ec3ec34b1)

**Comment by riverwanderer** [comment]
Ah! That was it. All good then.

**Comment by BrentEaston** [comment]
There is a limitation when editing extensions that you have very little control over where the items go when the parent is in the base module. Notice how none of the Extension items in the Fleet Actions folder have a Move option. 

You can edit the extension buildfile and move these around. 

I'm looking to see if I can get the DnD working to move them around.
