### ISSUE TITLE
Expression parameter for SumStack / CountStack

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12426]
Might SumStack() / CountStack() be augmented with the same Expression parameter options as their v3.7 Sum/CountLocation counterparts ?

Comparison of current functions:

![image](https://github.com/vassalengine/vassal/assets/58135975/2735e65d-88a5-4569-987d-75ffeba9d2f5)

**Comment by BrentEaston** [comment]
Thanks Mark, I had planned to add those for consistency, but it slipped my mind.

**Comment by BrentEaston** [comment]
Also Sum/Count Mat and Sum/Count Attachment.

**Comment by BrentEaston** [comment]
Implemented into 3,7 master
