### ISSUE TITLE
GKC to Current Attachments ignore deck limits

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12434]
In a test, the following GKC unexpectedly processed pieces in a deck that shared an attachment name on the calling piece:

<img width="708" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/6ef3cdf5-e6fd-470f-8600-47a1360f76af">

**Comment by BrentEaston** [comment]
Thanks Mark.

Have checked the code and FastMatch for Current Attachments ignores Decks completely. Attachments can potentially be spread between multiple Decks, so we will need to check the Deck Policy limits for each Deck that may contain the Attachments.

It looks like the other Location based FastMatch option will have the same problem:
 X, Y Location
 Location
 Current Location
 Current Zone
 Range

These can potentially involve multiple Decks as well.

I added most of these Fast matches as part of the Indexing project, so I will build a generic solution that can be used in all these options.

Code block starting at GlobalCommand@523.

**Comment by BrentEaston** [comment]
@riverwanderer New build 12434-FastMatchDeckPolicy going up now which should resolve this issue for all Fastmatch Location based options.

**Comment by riverwanderer** [comment]
I tested this out ok in build 12433-AttachmentFMIssues, or so I thought. Is that right?

**Comment by BrentEaston** [comment]
Yes, That's fine. The 12433 fixes are also in 12434 build, so testing either confirms 12433. Thanks.
