### ISSUE TITLE
Document Beanshell inline comments

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12455]
It would be useful to add a row to the [Beanshell Expressions](https://vassalengine.org/doc/latest/ReferenceManual/Expression.html#beanshell) table in the Reference Manual drawing attention to the ability of Beanshell Expressions to accept inline comments.

e.g.
**In-line Comment**   ` /*.../*` Comments may be entered within a Beanshell expression. Any enclosed text will be stripped from the expression before first execution.

**Comment by BrentEaston** [comment]
I will be adding these to the Function Builder Meny as well.
