### ISSUE TITLE
Mouse-over Stack View 'Text underneath each piece' should support Trait-specific functions like SumStack

### ISSUE THREAD

**Issue by BrentEaston** [vassalengine/vassal#12462]
May require changing this field to be expression.

What other Formatted text fields should have the Beanshell editor added?

**Comment by riverwanderer** [comment]
Two possible candidates on the `Text Label` field, though I've only ever wanted to use Beanshell for `Label text` (and it works even without the editor).
![image](https://github.com/vassalengine/vassal/assets/58135975/2d892e99-c5f3-43a2-ad91-12306c47d58f)

This option in the Report trait (rarely used ??)...
<img width="858" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/d7007f5f-9c0c-44bf-aefc-8c3e1883e22f">

Then there's my request #12235 which might be stretching the scope of what you intended here.
