### ISSUE TITLE
[Commands  & Colors: Ancients] deletes pieces from Victory Banner track at end of turn

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12475]
Module: v4.3.9, working under Vassal 3.6.19, not working under latest Vassal build nor v3.7.0beta4.

1. Observed when not working:  At end of turn any blocks on the Victory Banner track are deleted.
2.. Expected (working): At end of turn, no change to blocks on Victory Banner track.

Work in progress to isolate the issue.

**Comment by riverwanderer** [comment]
Caused by #12078 ; the following GKC in the module will now catch non-masked pieces. An additional GKC would be needed to prevent.  The change should perhaps have a compatibility option (default = no change for existing modules).

<img width="710" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/049c8766-5905-41b9-96a5-10b233f15851">

**Comment by riverwanderer** [comment]
I can see from #12078 that it was introduced to address a GPIW issue that I raised. I can relatively easily scan my modules to make then "v3.7 compatible" but I'd re-iterate my concern that other modules out there might get caught and that legacy modules should be protected by an opt-in switch.

The issue caused an obvious bug in this case but only because of shared key commands. Other times, the issue may cause a performance degradation, as potentially many more pieces will have to process the GKC, albeit ignoring it.

**Comment by BrentEaston** [comment]
Hmm.  I think #12078 should actually be reverted, no fix applied and the documentation updated..  All you need to do is check for ObscuredToOthers != true to pick up both Unmasked pieces and pieces with no mask.

**Comment by riverwanderer** [comment]
Fair enough for me @BrentEaston.
