### ISSUE TITLE
Merge 'Set Attachment Property' trait into 'Set Piece property' trait, and remove Constraints.

### ISSUE THREAD

**Issue by BrentEaston** [vassalengine/vassal#12501]
The current  'Set Attachment Property' (SAP) trait is virtually identical to the current 'Set Piece property' (SPP) trait, except for the ability to specify the BasicName or Attachment Index, plus it gives you Deck handling and Range selection that SAP doesn't have.

1. Remove Set Attachment Property' trait altogether.
2. Add 'BasicName or Attachment Index' as an optional FastMatch option for the 'CurrentAttachments' Fastmatch.
3. The Numeric constraints (Is Numeric/min value/max value/wrap) should not be a part of the SPP trait. These are already defined in the Dynamic Property traits that will be the target of SPP. Remove the numeric constraints from SPP and use the already defined numeric constraints of the target property instead.

**Comment by BrentEaston** [comment]
4. Add am option to SAP 'Honor numeric constraints in target property'. If unchecked, just blast the value in, if checked, use any numeric constraints defined on the target DP.

**Comment by riverwanderer** [comment]
Tested VASSAL-3.7.0-SNAPSHOT-32389cb-12501-Merge_SAP_into_SPP. Trait changes show up as expected. Test module (CCN  dev) shows that its SPP traits work equivalent to previous SAP trait functions  (module sets properties for single, unique attachments, so this does not text indexed attachment capability).
