### ISSUE TITLE
CountRange not counting in all cases

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12523]
The development version of C&C Nap relies on a count of opposing pieces adjacent to a particular marker. In some hexes the CountRange() function is not detecting the units.

The function used is in the form `{CountRange(1,1,"Stack","{inBattle && Side == cNot$Side$}")}`

In the screenshot below, two groups of "allied" pieces each surround a French piece. The number below the French piece shows the Count of allied pieces detected using the above expression. In one case it is correct (7). In the other, only one piece (the red "LT" unit) is detected.

<img width="561" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/0cdb6265-0205-42b5-a96e-405e02afdee9">

The screenshot is taken from the attached save game. 
[CountRangeGoesBad.zip](https://github.com/vassalengine/vassal/files/12262329/CountRangeGoesBad.zip)

Development module may be downloaded [here](https://www.dropbox.com/s/suaq6jl95btbojm/CCNapoleonics4_2_0DEV.vmod?dl=0).

**Comment by BrentEaston** [comment]
Other pieces (even terrain) in the same hex where causing the Count process to terminate prematurely.
