### ISSUE TITLE
3.7 Beta - CountLocation function with 3 parameters does not work

### ISSUE THREAD

**Issue by BrentEaston** [vassalengine/vassal#12547]
Error=: Error in method invocation: Method countLocation( java.lang.String, java.lang.String, java.lang.String, VASSAL.counters.Marker ) not found in class'VASSAL.script.ExpressionInterpreter' Error: Expression evaluation error. See the errorlog for more details.
- Expression Audit:
- Source type=Piece Trait
- Source name=Piece: British Foot Artillery (Strength=3)
- Source description=Trait: Restrict Commands - Only a phasing player with click battlefield actions Preference and not whilst there are Combat Assist icons active. - clickBlock
- Source field=Restrict when properties match
- Source Expression={!prefClickBlock || gPhase !~ "2|3" || (PlayerSide != "Solitaire" && PlayerSide != gActiveSide) || CountLocation("CApos","Main Map","{caAux_caStatus != \"Green\"}") > 0}
- prefClickBlock=true
- gPhase=2
- PlayerSide=Solitaire
- gActiveSide=Allies
- Error=: Error in method invocation: Method countLocation( java.lang.String, java.lang.String, java.lang.String, VASSAL.counters.Marker ) not found in class'VASSAL.script.ExpressionInterpreter'

**Comment by riverwanderer** [comment]
4 parameters also fails, if I've got the syntax right here:
` CountLocation("CApos","Main Map","BasicName","{caAux_caStatus != \"Green\"}") > 0}`

`Error=: Error in method invocation: Method countLocation( java.lang.String, java.lang.String, java.lang.String, java.lang.String, VASSAL.counters.Marker ) not found in class'VASSAL.script.ExpressionInterpreter' `

On the other hand, 3 (and presumably 4) parameters is fine in CountZone().

**Comment by riverwanderer** [comment]
Whoops - missed that you already built the fix @BrentEaston. Yes, in VASSAL-3.7.0-SNAPSHOT-e9cf7c2-beta-CountMapLocationIssue CountLocation() works with 3 and 4 parameters.
