### ISSUE TITLE
 GetAttachProperty() causes Unimplemented binary String operator error

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12561]
Vassal 3.7 build: VASSAL-3.7.0-SNAPSHOT-e9cf7c2-beta-CountMapLocationIssue

Use of GetAttachProperty() yielded the following Unimplemented binary String operator error:

```
- 2023-08-12 10:50:38,336 [35221-AWT-EventQueue-0] WARN VASSAL.tools.ErrorDialog - Piece: Charge If Charged Trait: Layer - Track combatPhase - Status Source: {gPhase < 3 ? gPhase : caAux_BasicName=="CA Hits" ? 6 : GetAttachProperty("ldr","dice_Level","{dice_Level > 1}") > 1 ? 10 - GetAttachProperty("ldr","dice_Level","{dice_Level > 1}") : caAux_BasicName=="CA Retreat" ? (caAux_hits_Level == 2 ? 10 : 9) : gCombatSide != "" ? 4 : 2} Error: Expression evaluation error. See the errorlog for more details.
- Expression Audit:
- Source type=Piece Trait
- Source name=Piece: Charge If Charged
- Source description=Trait: Layer - Track combatPhase - Status
- Source field=Follow expression
- Source Expression={gPhase < 3 ? gPhase : caAux_BasicName=="CA Hits" ? 6 : GetAttachProperty("ldr","dice_Level","{dice_Level > 1}") > 1 ? 10 - GetAttachProperty("ldr","dice_Level","{dice_Level > 1}") : caAux_BasicName=="CA Retreat" ? (caAux_hits_Level == 2 ? 10 : 9) : gCombatSide != "" ? 4 : 2}
- gPhase=3
- caAux_BasicName=
- caAux_hits_Level=
- gCombatSide=French
- Error=internal Error: Unimplemented binary String operator
```

Replacing the second use of `GetAttachProperty()` with a literal number or placing the function in a Calculated Property gave the expected result without error.

So, the following works as a combination:

Calculated Property` ldr_dice_Level :  GetAttachProperty("ldr","dice_Level","{dice_Level > 1}")`

Layer expression: `{gPhase < 3 ? gPhase : caAux_BasicName=="CA Hits" ? 6 : ldr_dice_Level > 1 ? 10 - ldr_dice_Level  :  caAux_BasicName=="CA Retreat" ? (caAux_hits_Level == 2 ? 10 : 9) : gCombatSide != "" ? 4 : 2}`

**Comment by BrentEaston** [comment]
Hi @riverwanderer ,

Did the fixes I did for beta 5 resolve this, or is there still a problem? Thanks.

**Comment by riverwanderer** [comment]
Checking.

By the way, in the Expression Audit, I don't understand the value of Source Name. It seems to be coming from a Layer above the trait (also a Layer) that is causing the problem. One level in that Layer has the Name ""Charge if Charged". However, the state of the piece should never generate that value in the PieceName.  The rest of the Audit is correct.

**Comment by riverwanderer** [comment]
Still occurring in Beta5.
Version of the module with the problem trait in (CombatPhase Layer within the Combat Assist-Controller prototype on the CA Controller piece): [here](https://www.icloud.com/iclouddrive/0abUQeMD6Int421zC3IsJONpg#test_12561).

Demo: [test 12561.zip](https://github.com/vassalengine/vassal/files/12392686/test.12561.zip)
To trigger the fault, click on one of the two x3 hits icons.

**Comment by BrentEaston** [comment]
I haven't been able to download this module through iCloud, it keeps timing out and restarting. I had no problems with the other one via Dropbox. Can you redo to dropbox? Thanks

**Comment by riverwanderer** [comment]
Moved to dropbox.... https://www.dropbox.com/s/n2kbtvqjys32q9k/test%2012561.vmod?dl=0

**Comment by BrentEaston** [comment]
Ok, worked this one out. New build going up now

**Comment by riverwanderer** [comment]
Test case passes with build VASSAL-3.7.0-beta5-46457df-12561-Beanshell-function-issue.
