### ISSUE TITLE
Set Piece Property malfunctions with a legacy expression

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12578]
Vassal 3.7 beta5

This SPP trait writes the literal "tcBonus" into the property `tcSetting`. Changing to the equivalent Beanshell expression `{tcBonus} `gives the expected result i.e. the value of property `tcBonus`.

<img width="1424" alt="Pasted Graphic 7" src="https://github.com/vassalengine/vassal/assets/58135975/e8a760b1-d71e-41a4-8973-984882d084fd">

**Comment by BrentEaston** [comment]
Hi Mark,

Does the `tcBonus` property have a value in the Setting piece?  If not then 'tcBonus' is the correct result as $$ properties by convention return the property name (not null) if the property is not found.

In Set Piece Property ( and new parameter passng), $$ variables are pre-evaluated against the source piece, then the result is re-evaluated against the target piece.

**Comment by riverwanderer** [comment]
In the setting piece `tcBonus` is a Dynamic Property; numeric 0 or 1.

My solution must be incorrect too, I guess because `{tcBonus}` is whatever tcBonus is on the target piece, right ? Which is not what I need here.

**Comment by BrentEaston** [comment]
{$tcBonus$} might work for you, but $tcBonus$ should work also as an old-style expression, being replaced by 0/1, same as if you just enter 0 or 1 as the set Value. I didn't try this with a straight $$ property, I may have missed something.

**Comment by riverwanderer** [comment]
💡 Ah... but the expression is evaluated by the target piece!  So there the legacy expression `$tcBonus$ `will evaluate as you describe, since tcBonus is indeed null on that piece. Is that the explanation and what you intended for SPP ?

**Comment by BrentEaston** [comment]
No, it's supposed to be like a GKC. All$$ variables are pre-evaluated by literal replacement using the source piece, then the resulting expression, whatever it is ({}, old-style, simple number etc.) is evaluated on the target piece to generate the final value to be set. 

This aim is so you set the target piece using a calculation based on a mixture of properties from both the source and target piece.

**Comment by BrentEaston** [comment]
Do you still have problems? I tried this:
![image](https://github.com/vassalengine/vassal/assets/1622667/76e46820-e88f-456a-bb12-3e5bb9094a0e)
and both tests worked correctly for me, transferring the value of XYZZY from the source piece to the target piece.

**Comment by riverwanderer** [comment]
Still reproducible for me. To probe my idea I defined a marker tcBonus = 1 on the target piece. It made no difference, just as you suggested.  `{$tcBonus$}` works fine.  However, worryingly, `{tcBonus}` also sets tcSetting to 1 - implying that it is getting its value from the setting piece as well.

Here is a test setup for the [CCN dev module](https://www.dropbox.com/s/suaq6jl95btbojm/CCNapoleonics4_2_0DEV.vmod?dl=0). The SPP for `tcSetting` is in the trait `Combat Assist-Add Art Dice` :
[test 12597.zip](https://github.com/vassalengine/vassal/files/12393945/test.12597.zip)

In the test game, the resulting value of `tcSetting` is displayed as a label below the leftmost red Artillery piece. It starts as "0".

**Comment by BrentEaston** [comment]
I've tried all combos and can't get it to fail in my noddy module. I'll download yours and have a look later. I'll dig into that other expression issue first.

**Comment by BrentEaston** [comment]
What do I do to initiate the SPP?

**Comment by riverwanderer** [comment]
Move the red card marker onto the piece... it results in a GKC sending the key command tcBonus to the yellow (artillery) marker, which is what does the SPP.

<img width="198" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/8fbe2b9f-5de9-413c-b0b8-c7bd3c493b32">

I thought also to see what happens it I put a label on the other artillery piece and move the marker to that piece. That seemed to perform normally. I will try to unpick this one a bit more. 

Also - to make sure you are using the current module's SPP tcSetting value, do a refresh, as I've been playing around with the 3 different expressions.

**Comment by riverwanderer** [comment]
I've defined some direct commands on the yellow artillery piece and added to the label, in an effort to isolate the issue.
Download the module again and use this test setup:
[test 12597-2.zip](https://github.com/vassalengine/vassal/files/12395094/test.12597-2.zip)

There are now three yellow artillery markers to choose from, each has a context menu to change the value of tcBonus and to fire the SPP in each of the three formats. The values displayed beneath each one are tcSetting on the red piece (which may get set blank) and tcBonus (tb=)

Right click on the yellow artillery marker 
<img width="189" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/497c3128-796d-468f-b8fe-6def0d5dbe62">

**Comment by BrentEaston** [comment]
Very difficult to debug, but I believe I found an issue. It was only finding a value for tcBonus if the source piece if the property value was further in than the SPP property. I'm still not sure what I am looking at with the module, but it's definitely slightly better than before with the new version building now.

**Comment by riverwanderer** [comment]
Working now for me in build VASSAL-3.7.0-beta5-ddd218f-12578-SPP-Issue. 

Tested all of three expression forms and yielded these results, as expected:
`$tcBonus$` and `{$tcBonus}` : both now set the target piece property to the value of `tcBonus` on the source piece.
{tcBonus} : sets the target piece property to the value of tcBonus on that piece (tested by creating a Marker tcBonus on the target).
