### ISSUE TITLE
Deleting the first of several expressions to count in a deck causes a rather unfortunate internal error

### ISSUE THREAD

**Issue by assaultdoor** [vassalengine/vassal#12644]
If you are editing expressions to count in a deck and you happen to delete, cut, or paste over any but the last one, several undesirable things happen. First, you get a notification that there has been an internal error. Second, when you follow the advice and try to save your module, you'll find that you can't, because none of the menu options work. It doesn't matter if you use hotkeys or a mouse.

I've tried both delete and Cmd-X to cut. It doesn't seem to happen unless you have more than one expression, and it doesn't seem to happen if you are mucking around with the last expression.

Update: pasting doesn't seem to mess it up as badly. Menu items still work, but I still get an error.

**Comment by BrentEaston** [comment]
Hi, 
Could you let me know what version of Vassal you are using and exact reproduction steps? I can't get this to happen in 3.6 or 3.7 BUT I also don't seem to be able to save any Count Expressions at all, they don't seem to be 'Sticking' when I save the Deck. This feature seems to be completely broken?

**Comment by BrentEaston** [comment]
Ah, don't worry, got it. Forgot about the special format. Have reproduced, thanks.

**Comment by BrentEaston** [comment]
Ha, this bug has been there since 3,5 at least.
