### ISSUE TITLE
[OCS - Case Blue & GB II] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.opcache.OpFailedException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12717]
| ABR | |
|-----|-----|
| Version | 3.7.0 |
| Reporter |  |
| Error Log | [46993 bytes](https://vassalengine.org/files/gh/9439d3e585f37c5ba959e905d1eff04f5cd79f66) |

<pre>

OCS - Case Blue & GB II v6.18 3.7.0

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.opcache.OpFailedException
 at VASSAL.tools.opcache.OpCache.getFuture(OpCache.java:323)
 at VASSAL.tools.opcache.AbstractOpImpl.getFuture(AbstractOpImpl.java:86)
 at VASSAL.tools.imageop.AbstractOpImpl.getFutureImage(AbstractOpImpl.java:108)
 at VASSAL.tools.imageop.AbstractTiledOpImpl.getFutureTile(AbstractTiledOpImpl.java:154)
</pre>

**Comment by BrentEaston** [comment]
`java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space`

Needs to increase heap space from 512MB

**Comment by BrentEaston** [comment]
Out of Heap Space, no reporter specified
