### ISSUE TITLE
Translation panels can be hard to read

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12724]
Red text is illegible on blue background. What does it signify? Can it be white on blue or something else readable? This is on MacOS, in case that makes any difference.

Affects the top item and the currently selected attribute.

Blue on blue is even worse... afffects "Description" component, in the case of Definition of Sides (below):

![image](https://github.com/vassalengine/vassal/assets/58135975/687b5772-ffe5-42d4-b59d-bb1a8dfb9dd4)

**Comment by BrentEaston** [comment]
Ah, Yes. Not very readable. Much 'quieter' on windows.
![image](https://github.com/vassalengine/vassal/assets/1622667/58b1c87a-b53d-40f8-9924-1892d6b496d8)

Blue text = Completely translated
Red Text = Requires translation
Black Text = No text, no translation needed

**Comment by riverwanderer** [comment]
That highlighted it so much better on windows. The highlight colours might be a pervasive Mac/Java issue, as I recall from ages ago that @uckelman looked into something similar I;d complained about re Vassal Module Manager select highlighting. Unfortunately, it didn't seem like it could be fixed.
<img width="413" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/9b16c026-26aa-4c00-af08-7e113ad094c6">

**Comment by BrentEaston** [comment]
I've pushed a Mac friendly version, just using Bold to mark where translations are needed.

**Comment by riverwanderer** [comment]
> I've pushed a Mac friendly version, just using Bold to mark where translations are needed.
This is what is looks like... 

<img width="805" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/5073a621-f3d5-46d2-933b-ea0ff37a39b9">

**Comment by BrentEaston** [comment]
Try the new version I just pushed
