### ISSUE TITLE
Comment in expression corrupts it

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12769]
These steps show the issue in a action button:

1. <img width="510" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/a4c6274d-a934-47c1-99cf-1c2ca2259b54">

2. <img width="1001" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/fa5d3d6b-a814-48e6-962b-da412ab71a5a">

3.  Whoops
<img width="518" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/aacc808f-345a-44f5-be5b-ed1686be8545">

Is this something you can advise on or fix, @BrentEaston ?

**Comment by BrentEaston** [comment]
Doesn't happen on all types of fields, just the Sound Clip one. I will look into it.

**Comment by BrentEaston** [comment]
Can you try the 12769-Expression-Comment-issue build please.

**Comment by riverwanderer** [comment]
> Can you try the 12769-Expression-Comment-issue build please.

Re-tested Sound trait OK. Also tested Layer trait OK.
