### ISSUE TITLE
NPE in VASSAL.configure.Parameter.encode() closing Global Key Command

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12770]
| ABR | |
|-----|-----|
| Version | 3.7.1 |
| Reporter | ryance@sunybroome.edu |
| Error Log | [145230 bytes](https://vassalengine.org/files/gh/e2a0db81f20d0b2595d50768116f22b190722a40) |

<pre>I was editing a piece. I had just accidentally closed a Global Key Command trait by hitting the escape key and had double-clicked on it again to re-open it when I got this.

Spirit Island v4.5 beta 11 (Nature Incarnate+Horizons spirits with automated setup) 3.7.1

java.lang.NullPointerException: Cannot invoke "VASSAL.configure.Parameter.encode()" because "param" is null
 at VASSAL.configure.ParameterListConfigurer.encode(ParameterListConfigurer.java:58)
 at VASSAL.counters.CounterGlobalKeyCommand.myGetType(CounterGlobalKeyCommand.java:142)
 at VASSAL.counters.Decorator.getType(Decorator.java:527)
 at VASSAL.counters.PieceDefiner.edit(PieceDefiner.java:1144)
</pre>

**Comment by BrentEaston** [comment]
Reproduction Steps.
1. Create a new GKC trait with no 'Set Dynamic Properties'
2. Save GKC
3. re-open GKC
4. Click + to add a new Set Dynamic Property entry, do not fill anything in
5. Cancel or Escape to close PieceDefine
6. Try to re-open GKC
