### ISSUE TITLE
Labels are not rendering HTML that reference external images correctly.

### ISSUE THREAD

**Issue by pacman-ghost** [vassalengine/vassal#12784]
Using VASL 6.6.6.

The following renders correctly in VASSAL 3.6.14:
```
﻿<html> 
<head> <style> body { color: red ; } </style> </head>
xxx 
<img src="https://pacman-ghost.com/images/pacman-ghost.png"> 
yyy
```
![vassal-3 6 14](https://github.com/vassalengine/vassal/assets/27834058/cb44994a-693d-4920-b782-ad2e23bc396f)

But incorrectly in VASSAL 3.7.0 and 3.7.1:
![vassal-3 7 0+1](https://github.com/vassalengine/vassal/assets/27834058/44cb341b-34cf-4669-a8c5-dc2cab63b367)

Remove the `<img>` tag and it renders correctly:
![no-img](https://github.com/vassalengine/vassal/assets/27834058/1620f536-465d-4581-99a9-0b6a600b8376)

The `body { color: red ; }` text is CSS, so I suspect the `<head>` and/or `<style>` tags are being removed - broken HTML santitization, triggered by the `<img>` tag...?

**Comment by uckelman** [comment]
In what is that HTML entered? How do we reproduce the problem, step by step?

**Comment by pacman-ghost** [comment]
> In what is that HTML entered? 

A label.

> How do we reproduce the problem, step by step?

https://vasl-templates.org/help/?tab=userguide#add-scenario-details

> What is the last version of Vassal where you don't see the problem?

3.6.14 is the last one I checked.

**Comment by uckelman** [comment]
> 3.6.14 is the last one I checked.

Please let me know what the result is when you check 3.6.19.

**Comment by BrentEaston** [comment]
The HTML renderer built into Java Swing only supports:

>  HTML 3.2 (Wilbur) and a reasonable subset of CSS 1.0.

Vassal does no HTML sanitization at all except in the Chat Window if you don't have the HTML option turned on in Global Options. It's likely the level of HTML/CSS you are trying to use is beyond the level that is supported.

I don't think style sheets are supported, but I believe you can use CSS in in-line styles in <span> tags and some other tags.

**Comment by pacman-ghost** [comment]
> It's likely the level of HTML/CSS you are trying to use is beyond the level that is supported.

The HTML in my example is as simple as it gets, and works in VASSAL 3.6.14, and every version of VASSAL going back to 3.2.17 :-) But sometime recently, it has stopped working. The same VASL `.vmod` is being used, so it looks like something has changed in VASSAL. Or maybe the version of Java being used...?

This is not a simple case of "`<img>` tags are not working". The presence of an `<img>` tag causes the HTML preceding it to be mis-parsed. It looks like the `<head>` and/or `<style>` tags are being ignored, and the CSS is not being processed, and is instead appearing in the output as text. If it's not somebody trying to sanitize the HTML, this is very strange behavior. 

It can't be the HTML being rendered as plain-text, since we would also see the `<head>`, `<style>` and `<img>` tags appearing in the output as text. Instead, we can see the renderer trying to show an image. 

Note that when it's not working, the strings "xxx" and "yyy" are black, not red i.e. the CSS has not been processed. Remove the `<img>` tag from the HTML, and these strings appear in red, indicating that the CSS has been processed. So, the presence of the `<img>` tag is triggering some change in the behavior of the renderer.

**Comment by pacman-ghost** [comment]
A simpler example. This doesn't work (broken image):
```
<html> 
<img src="http://vasl-templates.org/services/static-images/flags/russian.png"> 
```

I just remembered that VASSAL sometimes has problems with TLS, but it's still broken.

**Comment by BrentEaston** [comment]
Thanks for the simple repeat case, I totally missed your advice that it was working in 3.6.14!

I've confirmed that this worked in 3.7.1-beta1, but fails in 3.7.1-beta2, I'll do a full bisect and track down the offending change.

**Comment by BrentEaston** [comment]
Ok, the offending commit is 942791f617483ccc4274e5dc187ec0258105fe8c which implements a change to support referencing images inside the module in img tags in labels.  Pr/Issue #12100. This has been implemented in a way that has removed the ability to reference external images.

Question, why are you referencing external images in your label img tags? Is this because in 3.6, it was not possible to reference an image from the module in a label tag? Obviously, referencing external images will fail if a player trys to use your extension with no internet connection.

Regardless, it does need to be fixed. Might need to get Brian involved as it was his fix.

Thanks for the report.

**Comment by pacman-ghost** [comment]
> Question, why are you referencing external images in your label img tags?

I am the author of [`vasl-templates`](https://vasl-templates.org), a tool that adds labels to a VASL scenario containing information that is useful to have at hand during the course of a game. These labels contain images e.g. flags and counters e.g.
![ob](https://github.com/vassalengine/vassal/assets/27834058/2562ca60-1f84-4b97-b4f1-89e35decafee)

Also, I know that people like to add their own images, even if they're not using `vasl-templates` e.g. photos from the scenario card.

> Obviously, referencing external images will fail if a player trys to use your extension with no internet connection.

`vasl-templates` can load these images from the internet, but they can also be loaded from localhost (`vasl-templates` runs a web server to serve such requests). But yes, this is a constant source of support requests :-/

> Is this because in 3.6, it was not possible to reference an image from the module in a label tag?

This is intriguing. Are you saying that it is now possible to load images from the module i.e. no internet connection nor local web server required? I've been proposing such a feature for ages.

Thanks for the quick response.

**Comment by BrentEaston** [comment]
> This is intriguing. Are you saying that it is now possible to load images from the module i.e. no internet connection nor local web server required? I've been proposing such a feature for ages.

Yes, that's correct. You been able to do this pre 3.7 in HTML displayed in a HTML Chart Component, and in the Chatter, but not in labels. Issue 12100 added this feature for Labels, but unfortunately broke the ability to reference external images.

`<html><img src="Russian.png"/>`

will look for Russian.png in the images folder of the current module, then check for it in the images folder of each loaded extension. The first found will be returned. It's up to you to manage name clashes.

**Comment by pacman-ghost** [comment]
Hmmm, I had something a little more extensive in mind :-)

A `.vmod` is just a ZIP file, so we allow modules to include extra files in there e.g.
```
    +
    +-- buildFile
    +-- moduledata
    +-- etc...
    +-- flags/
    |   +-- german.png
    |   +-- russian.png
    |   +-- etc...
    +-- css/
        +-- blah.css
```

Labels recognize a pseudo-protocol ```vassal://```, which get replaced with a localhost URL e.g.
```
    <img src="vassal://flags/german.png">
```
becomes
```
    <img src="http://localhost:1234/flags/german.png">
```

And VASSAL runs a local webserver that serves files from the `.vmod` file. There are ways to avoid having to run a local webserver, but it's probably the better solution.

This is a lot more flexible, since it allows anything to be served, not just images. VASSAL doesn't currently support Javascript or CSS stylesheets (?), but I know Doug Rimmer was looking at using a more modern HTML control for VASL, and this kind of thing opens up a lot of possibilities... :-)

**Comment by BrentEaston** [comment]
Currently, you can do the following:

`<img src="flags/german.png">`

which will load the image from images/flags/german.png in the module or extension. More is probably outside the scope of V3.

**Comment by uckelman** [comment]
Please try one of the VASSAL-3.7.2-SNAPSHOT-303ab7c-12784 builds in our [builds archive](https://vassalengine.org/builds/build/969646138). Does that fix the problem for you?

**Comment by pacman-ghost** [comment]
The 2 posted examples now render correctly, using VASL 6.6.6 and 6.6.7-beta5.

Thanks.
