### ISSUE TITLE
ConcurrentModificationException selecting predefined setup in wizard

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12912]
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter | scrolling throught the scenario menu with the up arrow |
| Error Log | [11487 bytes](https://vassalengine.org/files/gh/9fa8d183c0a14c07aa7f20808fcedd36f2b6cd36) |

<pre>

Atlantic Chase v2.0 3.7.5

java.util.ConcurrentModificationException: null
 at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1229)
 at VASSAL.build.module.index.IndexManager.getIndex(IndexManager.java:56)
 at VASSAL.build.module.index.IndexManager.pieceMoved(IndexManager.java:95)
 at VASSAL.build.module.Map.addPiece(Map.java:3254)
</pre>

**Comment by BrentEaston** [comment]
The Wizard code is firing off a SavedGameLoader in a new thread EVERY TIME a saved game is selected in the saved game drop-down. This should not happen until the Next button is clicked. If a player is quickly arrowing through the drop-down, multiple threads try an load saved games at one and crash each other.
