### ISSUE TITLE
Undo corrupts a set of Attachments

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12967]
A new feature in C&C Napoleonics v4.2 creates 0-3 attachment pairs from a static control peice, depending on card play.

One of pair of attachments is getting corrupted following a series of undos. The corrupted attachments are picking up a couple of unrelated pieces from another map window.

The distinguishing feature seems to be the position of the attached pieces, indicating to me that perhaps, following the UnDo sequence, the Attachment trait is somehow ignoring the map window/zone constraints of the attachment trait.

As a workaround, I have found I can include an additional criterion in the Additional Properties field on the Attachment trait, which excludes the random pieces regardless of map window.

Further investigation and a demo to follow.

**Comment by BrentEaston** [comment]
Hi @riverwanderer ,

Was this issue fixed by the fix for #13073?

**Comment by riverwanderer** [comment]
I didn't manage to characterise this one and I don't recall it involving stacking.  However, it's not causing me a problem at the moment. If I come across it again, I can re-open this issue.
