### ISSUE TITLE
NullPointerException Copying folder containing a Dice Button

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13044]
| ABR | |
|-----|-----|
| Version | 3.7.6 |
| Reporter |  |
| Error Log | [100072 bytes](https://vassalengine.org/files/gh/f5cf860f01ba02b199271e3048b29bb3884d09a6) |

<pre>Was trying to copy and paste a folder with Global Key Commands in it.

Downfall 1.5 v1.5 3.7.6

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.properties.MutablePropertiesContainer.addMutableProperty(String, VASSAL.build.module.properties.MutableProperty)" because "this.parent" is null
 at VASSAL.build.module.properties.MutableProperty$Impl.addTo(MutableProperty.java:99)
 at VASSAL.build.module.DiceButton.addTo(DiceButton.java:504)
 at VASSAL.build.Builder.build(Builder.java:82)
 at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)
</pre>

**Comment by BrentEaston** [comment]
Create a Folder containing a Dice Button
Copy Folder and paste to a different folder

**Comment by BrentEaston** [comment]
Symptom of more general problem - #13106
