### ISSUE TITLE
Cargo pieces do not follow Mat's Move Fixed Distance Trait

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#13072]
A instance of this problem is described on this [forum post](https://forum.vassalengine.org/t/possible-bug-mat-cargo-move-fixed-distance-trait/78721).  I replicated the issue.

The [Reference Manual ](https://vassalengine.org/doc/latest/ReferenceManual/Mat.html#top)is explicit that Cargo will follow Mat whenever Send to Location or Moved Fixed Distance traits are applied to the Mat.

Workaround: Send to Location works as documented and can be configured to give the same basic result as a Move Fixed Distance trait.

I can't think of a use case where Move Fixed Distance trait shouldn't keep the Cargo with the mat.

**Comment by BrentEaston** [comment]
Reproduced issue with a simple test case.

Also saw a second, possibly related issue. After applying MFD to a Mat so that it left its cargo behind, applying a second MFD to the same Mat and it refused to Move at all.

**Comment by BrentEaston** [comment]
There's a fix build up for this one as well.
