### ISSUE TITLE
Send to Location generates spurious movement trail

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#13071]
A module contains a "go back" Send to Location trait that triggers when a piece is dragged to another window.
The resulting effect is a movement trail from the piece to an unrelated location (a location which itself is not grid-centred).

In the example, the pieces have been dragged to the overlaying "French Hand" window. The second screen shot shows a piece that had an existing movement trail - showing that the existing movement trail has been replaced with a spurious one.

<img width="410" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/ce9ff2e9-c37f-4653-93d8-32edadce3ad0">

<img width="370" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/4e777264-68cf-4819-914b-ac89dc8bd303">

The effect occurs regardless of this Global Option setting:
<img width="448" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/24d0d403-dcdc-4db2-853c-f1a3085dd43d">

The Send to Location trait:
<img width="420" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/fdb189a7-c1de-4588-8242-773ced225687">

**Comment by BrentEaston** [comment]
I haven't been able to reproduce this in a simple module.

**Comment by riverwanderer** [comment]
> I haven't been able to reproduce this in a simple module.

Thanks for looking @BrentEaston. It dawns on me that I might have some other processing is over-writing X/Y before "goBack" kicks in. I'll follow that up.

**Comment by riverwanderer** [comment]
Confirmed, this wasn't a bug. There was another Trigger causing movement on the target map, so OldX/OldY were over-written before goBack Trigger kicked in. Sorry for the red herring!
