### ISSUE TITLE
Game Piece Layer paints incorrectly when set by Set Piece Property

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#13115]
i was using a GKC to push a piece temporarily to the lowest GPL in a module, subsequently re-surfacing the piece after a follow-on action. That works fine in the module.  The Piece's GPL is held in a Dynamic Property.

I tried using Set Piece Property to make the same GPL change and - though the Dynamic Property changed correctly, the Piece went to the lower GPL but does not re-surface afterwards.

This is the SPP example that succeeds in setting the Piece's GPL back to the upper level but the piece is not re-painted and remains under the other pieces which sit in an intermediate GPL.

<img width="1530" alt="Pasted Graphic 3" src="https://github.com/vassalengine/vassal/assets/58135975/57e45161-1832-49a2-b62f-04e2f0d2945d">

**Comment by BrentEaston** [comment]
Build up with a fix, please review.

**Comment by riverwanderer** [comment]
> Build up with a fix, please review.

Test success using buid VASSAL-3.8.0-SNAPSHOT-c6b9b36-13115-SPP-GPL.
