### ISSUE TITLE
[SecondaGuerraMondiale] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\areagioco.png:45,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13123]
| ABR | |
|-----|-----|
| Version | 3.7.8 |
| Reporter | tanaorsa@gmail.com |
| Error Log | [541782 bytes](https://vassalengine.org/files/gh/1185d4f5c130d9df262ac00332d701b20b22fa8d) |

<pre>Già in precedenza Open jdk si bloccava per eccessivo consumo Cpu mentre cercavo di definire la griglia multi-zona su una mappa da me caricata. Aggiungo che la mappa è stata da me creata in dwg e poi salvata in png per caricarla sul modulo Vassal.
Il messaggio di errore compare mentre sto facendo di nuovo la stessa cosa, anche se non vi è avviso di eccessivo consumo Cpu o memoria. La mappa di gioco è di 8,5 mb, quindi decisamente inferiore a quella di molti altri moduli.

SecondaGuerraMondiale v1.0 3.7.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\areagioco.png:45,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment]
Duplicate of #13100
