### ISSUE TITLE
CountZone can give an incorrect result

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#13132]
In some circumstances, CountZone() returns the wrong value. It appears to have an incorrect cache. In the same game state, using CountMap() for an equivalent expression, yields a different - and correct - result. 

Found with C&C Napoleonics development mode, in this Send to Location trait:
<img width="1049" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/8ce43b57-e12e-4b16-9c6c-d3cadffd4af5">

In the application, initially zero cards are in the "Battlefield" zone. Two cards are drawn from a deck via successive GKC calls. The Send to Location offset - when working - will put the second next to the right of the first within the Battlefield zone.  One card is selected and moved into a hand window, the other is discarded. These actions remove the cards from the "Battlefield" zone.

The expression initially returns a correct result but on subsequent use, it accumulates results from prior use, so the cards are stacked at the second position.

Workaround: Using an equivalent CountMap() function resolves the issue. In the application, the Send to Location trait is modified to identify the Battlefield zone using a zone property:
<img width="1315" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/1c257195-589f-4fdc-a617-df80b01792d7">

**Comment by BrentEaston** [comment]
I've been trying to reproduce this. Do you have an idea exactly which trait is causing the problem?

**Comment by riverwanderer** [comment]
> I've been trying to reproduce this. Do you have an idea exactly which trait is causing the problem?

As far as I can tell, it's the Send to Location trait where CountZone is used with the X position field where the problem occurs. I used CountZone elsewhere and have not noticed a problem like this.

I'll try putting the expression into a seperate property and see if that makes a difference.

**Comment by riverwanderer** [comment]
Update: Separating the X location from the Send to Location trait into a Dynamic Property made no difference - the error still occurs.

Examining the sequence of events more closely, it seems that a subsequent Send to Location trait is failing to update the CountZone result. Here's a summary of the traits involves:

1. Send to Location based on CountZone() - see above.  Then a manual command to run two more actions:

2. A Send to Location that sends one of the two cards to another window (a player hand).... after this action the CountZone() result should be 1 less, but it is not.
<img width="739" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/6ea5a34e-9af0-4a21-b637-14c6131018d8">


3. A Return to Deck action is also performed. This DOES decrement the CountZone() result as expected.

It does not matter what order 2 & 3 are executed in.

**Comment by BrentEaston** [comment]
Reproduced in my test module. Any sort of movement from one map to another that results in the piece stacking onto an existing piece skips the update of the Zone Index. Moving with the same map is not affected.

**Comment by BrentEaston** [comment]
Build going up now to fix this issue.
