### ISSUE TITLE
IllegalBuildException when importing XML into a component that it is not an allowed child of

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13166]
| ABR | |
|-----|-----|
| Version | 3.7.8 |
| Reporter |  |
| Error Log | [17933 bytes](https://vassalengine.org/files/gh/606ab745e31213215e232a034d5975f7f3508f7e) |

<pre>Import XML

Eylau v0.2 3.7.8

VASSAL.build.IllegalBuildException: failed to load class VASSAL.build.module.map.SetupStack
 at VASSAL.build.Builder.create(Builder.java:145)
 at VASSAL.configure.ConfigureTree.importTreeBranch(ConfigureTree.java:599)
 at VASSAL.configure.ConfigureTree$3.actionPerformed(ConfigureTree.java:716)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by BrentEaston** [comment]
Caused by importing XML into a place it doesn't belong. e.g. Export an At-start stack, then import that XML into the same At-start stack (instead of the Map).

Need to either
a) Check it's an allowed component (best)
or
b) fail gracefully with a suitable message (adequate).

**Comment by BrentEaston** [comment]
Most imports to wrong locations fail. Specifically seems to be an issue importing an At-start stack into another at-start stack.
