### ISSUE TITLE
Crash when saving GKC with empty parameters, then re-edit and re-add

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13268]
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter | markben61@gmail.com |
| Error Log | [224967 bytes](https://vassalengine.org/files/gh/e4e8587733cb71095c5707b0a08c5eb3a580c368) |

<pre>Creating a GKC; I added a blank set property field then closed the GKC configurator.
On re-opening the GKC and attempting to re-add the set property field, the exception occured.		

Commands & Colors: Napoleonics V5 v5.0.0a705 3.7.9

java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
 at java.base/java.util.ArrayList.rangeCheckForAdd(ArrayList.java:838)
 at java.base/java.util.ArrayList.add(ArrayList.java:510)
 at VASSAL.configure.ParameterListConfigurer.addEntry(ParameterListConfigurer.java:195)
 at VASSAL.configure.ConfigurableListController.lambda$new$2(ConfigurableListController.java:51)
</pre>

**Comment by BrentEaston** [comment]
Hi Mark,
 I have created a 1`3268-BlankParameters build that fixes this. Can you please test?

I may have to re-create because of that back-tick in the branch name.

**Comment by BrentEaston** [comment]
New branch 13268-Blank-Params

**Comment by riverwanderer** [comment]
Appears fixed by virtue of fixing #12977.
