### ISSUE TITLE
Broken undo on area of effect

### ISSUE THREAD

**Issue by DatBrute** [vassalengine/vassal#13283]
Vassal 3.7.7

Undoing the "show area of effect" action both doesn't hide the area of effect, and permanently prevents you from hiding the area of effect on that counter the normal way.

I noticed this behavior on both the World in Flames official vassal mod, and the Vietnam 1965-1975 mod.

This makes a counter so unpleasant to use that I would rather abandon the save. It can be fixed in under a minute by the user in mods like WiF official where you can delete the counter and spawn a new counter of its type, but in Vietnam you cannot so it cannot be fixed.

**Comment by jonathanrwatts** [comment]
I believe this bug was already fixed in the latest version of VASSAL, 3.7.10 -- see [forum post here](https://forum.vassalengine.org/t/vassal-3-7-10-released/79412).

**Comment by DatBrute** [comment]
Correct, thank you for convincing me to update haha
