### ISSUE TITLE
[Fantasy Combat System] NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13331]
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter |  |
| Error Log | [15024 bytes](https://vassalengine.org/files/gh/327ea1c23515bde017953fdce8bf5d03cfe7b1af) |

<pre>

Fantasy Combat System v0.1 3.7.12

java.lang.NullPointerException: null
 at java.base/java.io.File.<init>(File.java:278)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.filenameFilterCallback(GtkFileDialogPeer.java:107)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.run(Native Method)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.showNativeDialog(GtkFileDialogPeer.java:195)
</pre>

**Comment by CodeScratcher** [comment]
Hi, I'm the person who actually experienced this crash. I'm realizing I forgot to write a bug report. Here's a quick writeup, I can give more information when I get back home
OS: Manjaro Linux
Steps to reproduce: Create a chart window. Add a chart. Load an image. (probably more specific steps, but I'm not sure which ones lead to the crash)

**Comment by BrentEaston** [comment]
Hi, Thanks for the follow up, very useful..

The error is happening completely within the Linux Java code, there is no Vassal code involved, so there is nothing we can do about this. It is most likely a Java Bug and will potentially be fixed in some later or alternate version of Java.

Regards.
