### ISSUE TITLE
Local language images not always displayed

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#13346]
See this [discord thread](https://discord.com/channels/740127632586178572/742865978395721778/1243204952663265290).

**Comment by riverwanderer** [comment]
The issue turned out to be specific to the Commands & Colors module and - it seems - edits to the buildfile in the past that remove some .gif file extensions from card BasicPiece image file names. Or, less likely, some corruption in a Vassal edit or refresh doing this.  Fix was to insert the missing file types and refresh to module.

The residual Vassal issue is that core Vassal was treating these type-less image file names differently from the language image substitution part of Vassal.  Core Vassal was not affected by the missing file type (even showing the images as .gifs in the editor), implying the .gif is a default somehow. The localisation feature does not apply the same default, so did not find the images.

Assuming that Vassal consistently writes file types into the buildfile, the issue should only be possible is a BuildFile is edited directly so as to remove those file types.

**Comment by BrentEaston** [comment]
Vassal has ancient, ancient. mimimalistic support for being able to reference .gif files without having to specify the .gif on the end. This should NEVER have been thing, but was left over from VASL. 

I don't see any reason to spend time fixing this. Don't use .gif files any all is good. If you do use .gif files, don't reference them without the suffix and all will be good.
