### ISSUE TITLE
Regex comparison operators gives data error on integer number

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#13360]
Regex comparison operator =~ (and presumably !~) generate a data error if the Regex is an integer. For example, the following works if ORDERregex is "2|3" but fails when it is just "2".  ORDERregex.toString() also works.

```
- Bad Data in Module: Piece: banner british Trait: Text Label - {gPhase =~ ORDERregex} Source: {gPhase =~ ORDERregex} Error: Expression evaluation error. See the errorlog for more details.
- /prop show ORDERregex
- [ORDERregex]: 2
```

Is this a Vassal bug ?

**Comment by BrentEaston** [comment]
It's a gray area. Technically, it is 100% correct, you can't perform a regex on a number. But Vassal has more or less shot itself in the foot by internally converting the 2 to an integer in the first place.

I've fixed a few problems like this by adding auto-boxing to some of the Beanshell operators to allow for auto-type conversions. For example, base Beanshell throws a fit if you do 2 + "x", I test for and convert this to "2" + "x" .

This looks like a good candidate for this as the failure is unpredictable, depending on the data.

I'll have a look.

**Comment by BrentEaston** [comment]
Turned out to be fairly straight-forward. 

Please try build 13360-Regex-Numbers

**Comment by riverwanderer** [comment]
> Please try build 13360-Regex-Numbers

Tests out ok for me.
