### ISSUE TITLE
Location indexing failure

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#13408]
Location indexing fails for the Liberté module (v1.0.9). This module has Location Indexing enabled (as that is the default). 
<img width="517" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/d1838f41-a3b2-411d-a4b3-ed07dfbc7672">

The module incorporate a phase where a marker block is moved from 1 province (a Zone) to another, in sequence, evaluating election results based on stacks of blocks within each province. On entry to the province, the marker piece calculates how many stacks there are in the province, with how many blocks and who owns each stack.

An example game file is attached, to demonstrate the problem, key features described here:

Start position:
The Bretagne province is in a correct state. Left click on the black cube to resolve the election in Bretagne and progress to the next province (4-Touraine):
<img width="485" alt="esolve election" src="https://github.com/vassalengine/vassal/assets/58135975/18e73db8-f178-4180-8049-f1b42b4a77e6">

The next expected state is as shown here. This state is obtained prior to Vassal 3.7 and when Location Indexing is disabled in Vassal 3.7:
<img width="310" alt="s=3 idx=1 Orange 2" src="https://github.com/vassalengine/vassal/assets/58135975/5e12b04b-61f9-49a4-aca9-2c256d04700e">

However, with Location Indexing enabled, the state becomes unpredictable and depends on the order in which pieces are moved into or within the province zone. Here is a typical state for the example game file:
<img width="267" alt="Pasted Graphic 2" src="https://github.com/vassalengine/vassal/assets/58135975/8b3814e4-afed-4c8d-ac93-1d27e519d108">

The demo game file: [bad.index.demo.zip](https://github.com/user-attachments/files/16232000/bad.index.demo.zip)
Use the demo file from this test version of the module: [here](https://www.icloud.com/iclouddrive/003SCkuy5O6gMmhwtWZsEapqw#LiberteV1-0-9X-13408) (icloud account needed).

 To demo the issue:
Join as "Orange".
Click on the black cube - it should count the red block in province 3 as a "radical" vote, clearing the stack. This is correct behaviour.
Now undo, and move that stack in provlnce 3 slightly.
Repeat and notice that the stack does not change in province 3.
You can observe the same by moving stacks in other provinces before clicking on the black cube in each one.

I will workaround the issue by disabling indexing.

**Comment by BrentEaston** [comment]
Very, very difficult to debug without a better idea of exactly what is failing. We'll need some more details on the setup of the GKC's you think are failing, presumably one with a particular type of by-location FastMatch. If we can narrow it down to one specific GKC behaving incorrectly, I can probably debug from there.

**Comment by riverwanderer** [comment]
It's a set of 3 GKCs in prototype `chkWinner: Detect Province Winner` that fail here. They all Fast Match in the Current Zone, like this:
<img width="476" alt="image" src="https://github.com/user-attachments/assets/3d83e8ae-db51-40a9-bfa8-f6896d82d941">

I can pinpoint the Zone search as the issue, by instead setting up an Attachment when the marker moves into a Province (Key Command: `chkWinner`) - replacing Current Zone fast match with an additional property search. Then reference that Attachment from the 3 GKCs instead of Current Zone and refresh the example game; now moving stacks (from province 4 onwards) doesn't cause the problem.

**Comment by BrentEaston** [comment]
Ok, there's a test build going up now on branch 13408-IndexIssue.  The property IndexedZone will report the Zone Vassal thinks the piece is in via the index. 

Give that a try. If that looks OK, then I need to look closer at the Fastmatch code for the CurrentZone comparison.

**Comment by riverwanderer** [comment]
OK - well adding that property into a text label gave me an exception and the refreshed stack is offset unexpectedly but read on as maybe there's enough info from this test to help you.

Testing using the test game and module, running under IndexIssue snapshot:

A province with labelled stacks showing as expected... IndexedZoned is labelled "z=":
<img width="216" alt="image" src="https://github.com/user-attachments/assets/62ec74a9-78ea-4064-a927-453b01af9ece">

Now I move the stack on the left and the IndexedZone is lost - presumably replaced by diagnostic text -
<img width="236" alt="image" src="https://github.com/user-attachments/assets/c12d9f97-8b7b-43dd-8d61-a02b2f9d8d7a">

Exception log, should you need it:  [dump from adding IndexedZone to text label.txt](https://github.com/user-attachments/files/16234256/dump.from.adding.IndexedZone.to.text.label.txt)

**Comment by BrentEaston** [comment]
Ok, that's a start. The Index Manager actually keeps 2 references to each piece. One is a index by Zone to look it up, and the other is a reverse index of pieces to be able to quickly find what Zone a given piece is currently in so that it can be removed.  The diagnostic 'Value=. xrefvalue=null' is printing because the two don't match. In this case, null is actually equivalent to "" BUT what this is saying is that some action that just occurred has completely unlinked the piece from the Zone index, but not added it to a new Zone. Is there any chance there is a gap in there between 2 zones?  

Presumably there is whole lot of 'stuff' going on there, more than just a move? If not, the save game at that point before the move is what I need to dig deeper.

When a piece is moved, it is unlinked from one zone, then linked into the new zone it arrives in. 

That error log is being caused by a piece in the Game Palette. I'm guessing you added a reference to IndexedZone to the label of the piece definition? We can ignore that.

**Comment by riverwanderer** [comment]
"Is there any chance there is a gap in there between 2 zones?" - do you mean in the Zone definitions?  It's possible, of course. But the movement the I made in the test was wholly within one zone. I moved the piece only a short distance and it doesn't seem to matter where that movement goes (within the zone at least, I didn't try moving to another zone yet). 

Yes, the movement will be triggering some other actions - I will de-link that extra logic and see what that reveals.

**Comment by riverwanderer** [comment]
OK - movement effects are implicating. All is good if I remove the map movement key command. Now to try and isolate the action.

**Comment by riverwanderer** [comment]
@BrentEaston - Text Label seems to be the only way to get IndexedZone to display - tried debug (/prop sel show IndexedZone) and Report Action trait, but they both report null.  Trouble is that once that I defined that text label and the exception kicks in, I can no longer edit the piece prototype for further debugging.  I will continue when I get some more time - hopefully, tomorrow.

**Comment by BrentEaston** [comment]
There's a new build going up that should fix that bug and make things a bit easier.

**Comment by riverwanderer** [comment]
@BrentEaston  - So far, I've narrowed the cause down to a Game Piece Layer change for on the round counter piece. 

The way the module works, the square shapes (red, blue, white) each stack independently. The round counters "dock" to the stack when it detects that it's been moved close to one (or square stack moved to a counter).

The process is implemented by a Dynamic Property (_Layer_) on the round counter, which is the map's GPL property. In the case of a stack being moved, the round Piece switches to a neutral Layer (not stacking with anything) and later a GKC from the square stack causes the round Piece to switch again to the same Layer as the square stack.

There might be some other interaction going on but I wonder if the piece switching GPL twice during the move could be causing the issue, do you think ?

**Comment by BrentEaston** [comment]
It's possible I guess, though I would not have thought so.  So, let me get this right.

You have a stack of pieces which you move manually , and when it arrives, a Map-afterburner key forces one of the pieces into a different Game Piece Layer, and that piece now has no Zone indexed?

**Comment by riverwanderer** [comment]
> You have a stack of pieces which you move manually , and when it arrives, a Map-afterburner key forces one of the pieces into a different Game Piece Layer, and that piece now has no Zone indexed?

Yes; but the mechanism  on the Map-afterburner triggers _successive_ changes in the piece's GPL:-
1. Change to a GPL that stacks with none of the 3 types of "Faction Block" (red, blue & white pieces).
2. Change to the GPL of the nearby Faction Block stack and then Send to Location (x/y)  to join that stack.

I've now pinpointed that this second move was triggering (via map-afterburner) a further iteration of steps 1-2 (but not a loop, presumably because the move in step 2 doesn't happen as the piece is already at the stack location). If I add code to skip step 1, the issue disappears. It seems to be that particular GPL change that triggers the issue.

**Comment by BrentEaston** [comment]
Ah, I see something now. Dynamic Property changes cause a G PLayer change by doing a mini-move of the piece to the same location, That appears to be removing the piece from the Zone index, but it doesn't get added back in. I know where to look now.

**Comment by BrentEaston** [comment]
Hmm. Seems to be more to it. I can't reproduce it in a noddy module. Must be some specific combination causing problems.

**Comment by BrentEaston** [comment]
Can you send me a log file with the pieces setup and showing the IndexedZone and then the piece moving and losing the IndexedZone? Thanks.

**Comment by riverwanderer** [comment]
Here's a log that demos the error. Due, I presume, to vassal initialisation, the error doesn't immediately show - see the chat log for my comments that indicate when it did show in the original.  However, just at the end, the error does show in the replay as well.

[bad index demo.zip](https://github.com/user-attachments/files/16278736/bad.index.demo.zip)

**Comment by BrentEaston** [comment]
New build 13408-IndexAfterDPChange going up now for this one.

There was a corner case where pieces in a stack that have their property changed causing them to change layer and move to a different Stack don't get properly re-indexed.

**Comment by riverwanderer** [comment]
Build 13408-IndexAfterDPChange tests ok.
