### ISSUE TITLE
Bulk Refresh breaks attachments between items in a stack

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#13447]
Observed during development of C&C Napoleonics v5. An Attachment formed between a Leader and a Unit piece (stacked) is lost if the game is refreshed using the bulk ("Predefined Setup") Refresh tool.  Since PR #13439 the Attachment can be restored by linking the appropriate GKC to the VassalPostRefreshGHK hotkey.

To replicate:
1. Open CCN module (later than beta9)
2. Open scenario B001 (Rolica). Right click on any 2 piece stack on the main board. It should not show the option "Repair Attachment". As a further check, the debug command `/prop select show ap_AttachCount` will show "1" for each piece.
3. Close the scenario and Perform Tools...Refresh Predefined Setups, entering 001 in the filter text box.
4. Reopen the scenario and repeat step 2. The attachments are broken.
5. Repeat step 3 but this time select the post-refresh GHK option as well.
6. Repeat step 4 - notice that the attachments have been restored.

**Comment by riverwanderer** [comment]
I've discovered a possible cause in the module itself.

**Comment by riverwanderer** [comment]
Isolated a demo for this issue. It seems that the "return path" of an Attachment gets nerfed by the a Refresh when run via the Predefined Setups tool, so may have something to do with bypassing normal startup.

The core of the test is this Attachment trait on each piece:

<img width="1063" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/43a88cb1-442f-409c-86f6-9f09aa25d65d">

The two Key Commands are Triggered on a move of the piece - with a Clear followed by an attempt to Attach.

The pieces each display their PieceId and the number of outgoing and incoming attachments - which should be 1 in each case. Move pieces around, unstacking and restacking to see that this is effective.  

An in-game Refresh does not effect the pieces, stacked or not.

However, a standard Predefined Setups Refresh, using default settings, will result in one piece without any attachments (the bottom one, presumably it was moved back first by the refresher). That would be expected, but the top piece should have remade all the attachments because of the setting "Attach to that Piece" on the Attachement trait. However, instead, the top piece has only its outgoing attachment.

The demo module includes a special GHK that forces the pieces to remake their attachments. If this is invokved from the Refresher (VassalPostRefreshGHK), the Predefined Setup Refresh will repair the damage it caused.

Demo module: [StackAttach13447.zip](https://github.com/user-attachments/files/16119895/StackAttach13447.zip)

**Comment by BrentEaston** [comment]
Thanks Mark, I have reproduced this in a no map, 2 counter stack game.

**Comment by BrentEaston** [comment]
Hi Mark, Test build going up for branch 13447-AttachBulkRefresh now. This was basically the same issue as the save/load issue. The PDS refresher was suppressing some of the game startup code and any attachments to later loaded pieces where being lost.

**Comment by riverwanderer** [comment]
Fix confirmed in my test case and, once I remembered that I'd have to do a one-time VassalPostRefreshGHK, it works in my CCN dev module as well. Thanks @BrentEaston.
