### ISSUE TITLE
OldMat is again being cleared after Send To Location if Mat Cargo is below Send To Location (11884 is back)

### ISSUE THREAD

**Issue by assaultdoor** [vassalengine/vassal#13468]
Hi,

I'm using VASSAL 3.7.12 on a Mac running openjdk version "21.0.3" 2024-04-16 LTS.

Bug #11884 just showed up again. I have a piece with Mat Cargo and Send To Location traits, and every time the Send To Location shows up above the Mat Cargo, the OldMat property is cleared. Moving Mat Cargo one space up fixes the problem.

**Comment by BrentEaston** [comment]
This was originally reported in 3.6.9, then supposedly fixed. Can you confirm that this worked in some earlier versions of 3.7? Can you isolate which version it stopped working? Thanks.

**Comment by assaultdoor** [comment]
I checked the initial 3.7 release, plus the 3.7 beta 3 release. It doesn't work in either of those. I checked 3.6.12, where I thought it was fixed, and I still see the error. I assume I moved all the Send to Location traits that I had at the time so everything worked prior to 3.6.12 and just didn't notice. Or there's something else I'm doing wrong, but I don't think so.

**Comment by BrentEaston** [comment]
Ok, sounds like the 'fix' never actually fixed the problem. I can see the change that went into 3.6.12 (and all later revisions) that supposedly fixed the issue, so the code hasn't been dropped off. I am re-visiting.

**Comment by BrentEaston** [comment]
There is a test build 11884-NewOldMatFix going up now that I believe fixes the problem. The original fix never worked. Can you please try it.

**Comment by assaultdoor** [comment]
That seems to work!

Thanks.
