### ISSUE TITLE
Unexpected top level block close - Loading malformed HTML causes RuntimeException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13497]
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter |  |
| Error Log | [778008 bytes](https://vassalengine.org/files/gh/5862df52e288c1c4e09e153df3a91f6cfe2e7860) |

<pre>Was trying to add a html table and got this bug thing.

<html>

<style type="text/css">
	table.main {
		font-size: 80%;
		border: 2px solid black;
		border-collapse: collapse;
		background-color: #D8C1DA;
        width: 100%;
}

	}

	tr.row1 {
		background-color: #BBBBBB;
	}

	tr.row2 {
		background-color: #DDDDDD;
	}

	tr.row1-drm {
		background-color: #C0E3ED;
	}

	tr.row2-drm {
		background-color: #7DD5ED;
	}

	td.title1 {
		font-weight: bold;
		font-size: 125%;
		text-align: center;
		color: #E60000;
		background-color: #EEEEEE;
		border-top-width: 1px;
		border-top-style: solid;
		border-color: black;
		border-bottom-width: 1px;
		border-bottom-style: solid
	}

	div.para1 {
		margin-left: 1em;
		text-indent: -1em;
		background-color: #BBBBBB;
	}

	div.para2 {
		margin-left: 1em;
		text-indent: -1em;
		background-color: #DDDDDD;
	}

	div.para1-drm {
		margin-left: 1em;
		text-indent: -1em;
		background-color: #C0E3ED;
	}

	div.para2-drm {
		margin-left: 1em;
		text-indent: -1em;
		background-color: #7DD5ED;
	}
</style>

<body bgcolor="#9F6CA6">

	<table numcols="3">
		<col width="30%">
		<col width="30%">
		<col width="40%">
		<tr>
			<td style="vertical-align:top">

				<table numcols="1" class="main">
					<tr>
						<td class="title1">RB/RO Cumulative AC drm:</td>
					</tr>

					<tr class="row1-drm">
						<td>
							<div class="para1-drm">
								<b>-1</b> if S? in Hold Attitude is in a VPO Location.
							</div>
						</td>
					</tr>
					<tr class="row2-drm">
						<td>
							<div class="para2-drm">
								<b>-1</b> if S? in Advance Attitude is in or ADJACENT to a FRIENDLY Controlled VPO Location.
							</div>
						</td>
					</tr>
					<tr class="row1-drm">
						<td>
							<div class="para1-drm">
								<b>-1</b> if ? 1 already activated ENEMY unit that is in Advance Attitude is within two hexes/the same building as the S?
							</div>
						</td>
					</tr>
					<tr class="row2-drm">
						<td>
							<div class="para2-drm">
								<b>-1</b> if Russian ENEMY and S? is in/ADJACENT to a Factory or a Fanatic Strongpoint Location.
							</div>
						</td>
					</tr>
					<tr class="row1-drm">
						<td>
							<div class="para1-drm">
								<b>-1</b> if German ENEMY and S? is in a Factory or a level 2 building Location.
							</div>
						</td>
					</tr>

				</table>

</body>

</html>

VASL v6.6.9-beta4 3.7.12

java.lang.RuntimeException: Unexpected top level block close
 at java.desktop/javax.swing.text.html.CSSParser.getNextStatement(CSSParser.java:193)
 at java.desktop/javax.swing.text.html.CSSParser.parse(CSSParser.java:154)
 at java.desktop/javax.swing.text.html.StyleSheet$CssParser.parse(StyleSheet.java:3282)
 at java.desktop/javax.swing.text.html.StyleSheet.addRule(StyleSheet.java:314)
</pre>

**Comment by uckelman** [comment]
The immediate problem is likely to be this line having no ending semicolon:
```
border-bottom-style: solid
```

**Comment by BrentEaston** [comment]
I think the problem is the extra } on line 9.

I'll just trap the RunTimeException and reject the load with an appropriate message.
