### ISSUE TITLE
Export property sheet trait as text

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#4418]
| Bugzilla |  |
|----------|----------|
| ID | BZ1818 |
| Reported | 2004-03-28 12:37:00 +0200 |
| Modified | 2020-06-22 00:12:45 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | medium |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Rodney Kinney](mailto:rodneykinney@comcast.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2010-08-25 14:35:37 +0200
<pre>---- Reported by rodneykinney@comcast.net 2004-03-28 00:37 ----

I am requesting adding the ability to export 
property sheet trait data and spreadsheet trait data as
a function 
of using the text capture tool.

  The issue is that there's only one method for
attaching text to a GamePiece, getName(), which is also
used for auto-reporting moves.  You probably don't want
to dump the entire spreadsheet data with every move, so
you need another way of getting that data.  Perhaps a
LONG_NAME property would do the trick.  The
spreadsheet/property sheet would return the full text
while the default implementation would return getName().

--- Bug imported by uckelman@nomic.net 2010-08-25 14:35 MST  ---

This bug was previously known as _bug_ 924683 at http://www.vassalengine.org/trackershow_bug.cgi?id=924683

Unknown Component 
   Using default product and component set in Parameters 
The original assignee of this bug does not have
   an account here. Reassigning to the default assignee
   for the component, uckelman@nomic.net.
   Previous assignee is unknown.
Missing Resolution. Setting status to NEW
Unknown resolution "".
   Setting resolution to MOVED</pre>

**Comment by Cattlesquat** [comment]
#4535 now the catchall make-Property-Sheet-better listing
