### ISSUE TITLE
Stronger checking of module versions

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#4434]
| Bugzilla |  |
|----------|----------|
| ID | BZ1834 |
| Reported | 2004-03-04 05:37:00 +0100 |
| Modified | 2020-06-22 00:12:56 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | medium |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2010-08-25 14:35:37 +0200
<pre>---- Reported by richard_wein 2004-03-04 17:37 ----

I should be given a strong warning when someone tries 
to join the game with a different version of the module 
from mine. Ditto if I try to open a saved game with a 
different version of the module from the last person who 
opened it.

Version checking should not be limited to checking the 
version number entered in the editor. It should check for 
_any_ change to the module. This could be done by 
having the module editor record the date and time the 
module was last saved or some sort of checksum on the 
module contents.

--- Bug imported by uckelman@nomic.net 2010-08-25 14:35 MST  ---

This bug was previously known as _bug_ 909965 at http://www.vassalengine.org/trackershow_bug.cgi?id=909965

Unknown Component 
   Using default product and component set in Parameters 
The original reporter of this bug does not have
   an account here. Reassigning to the person who moved
   it here: uckelman@nomic.net.
   Previous reporter was richard_wein.
The original assignee of this bug does not have
   an account here. Reassigning to the default assignee
   for the component, uckelman@nomic.net.
   Previous assignee is unknown.
Missing Resolution. Setting status to NEW
Unknown resolution "".
   Setting resolution to MOVED</pre>

**Comment by Cattlesquat** [comment]
I think we actually did this
