### ISSUE TITLE
Allow expansion/mouse-over of stacks in Private Map

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#4440]
| Bugzilla |  |
|----------|----------|
| ID | BZ1843 |
| Reported | 2004-03-04 05:54:00 +0100 |
| Modified | 2020-06-22 00:12:37 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | medium |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2010-08-25 14:35:37 +0200
<pre>---- Reported by richard_wein 2004-03-04 17:54 ----

Sometimes I can see a stack but can't access it. This 
can occur with the Restricted Access trait or with a 
private window when the "visible to all players" checkbox 
is checked. In these situations I should be able to see 
inside the stack, but I can't. Neither double-click-to-
open-stack nor mouse-over works in this situation.

I suspect it has been made this way to allow for games 
where players are only allowed to see the top piece in 
an opponent's stack. But it should be optional, as not all 
games work this way. Sometimes "visible"should really 
mean "visible".  ;-)

---- Additional Comments From richard_wein 2004-03-08 14:17:56 ----

Logged In: YES 
user_id=971538

I've just noticed that it _is_ possible to see inside stacks of 
restricted-access pieces, but it's still not possible to see 
inside stacks within private windows where I don't have 
access.

---- Additional Comments From uckelman@nomic.net 2006-11-27 23:43:14 ----

Logged In: YES 
user_id=245140
Originator: NO

Is this a problem? Maybe I'm not understanding how private maps are supposed to work.

--- Bug imported by uckelman@nomic.net 2010-08-25 14:35 MST  ---

This bug was previously known as _bug_ 909973 at http://www.vassalengine.org/trackershow_bug.cgi?id=909973

Unknown Component 
   Using default product and component set in Parameters 
The original reporter of this bug does not have
   an account here. Reassigning to the person who moved
   it here: uckelman@nomic.net.
   Previous reporter was richard_wein.
The original assignee of this bug does not have
   an account here. Reassigning to the default assignee
   for the component, uckelman@nomic.net.
   Previous assignee is unknown.
Missing Resolution. Setting status to NEW
Unknown resolution "".
   Setting resolution to MOVED</pre>

**Comment by Cattlesquat** [comment]
This is that same other bug I just fixed
