### ISSUE TITLE
update VASSAL documentation

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#4457]
| Bugzilla |  |
|----------|----------|
| ID | BZ1861 |
| Reported | 2007-01-16 10:18:00 +0100 |
| Modified | 2020-06-22 00:12:41 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | medium |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2010-08-25 14:35:37 +0200
<pre>---- Reported by uckelman@nomic.net 2007-01-16 22:18 ----

This RFE would involve making sure that all of the VASSAL documentation reflects the current state of VASSAL, as much as possible.

--- Bug imported by uckelman@nomic.net 2010-08-25 14:35 MST  ---

This bug was previously known as _bug_ 1637166 at http://www.vassalengine.org/trackershow_bug.cgi?id=1637166

Unknown Component 
   Using default product and component set in Parameters 
The original assignee of this bug does not have
   an account here. Reassigning to the default assignee
   for the component, uckelman@nomic.net.
   Previous assignee is unknown.
Missing Resolution. Setting status to NEW
Unknown resolution "".
   Setting resolution to MOVED</pre>

**Comment by Cattlesquat** [comment]
Basically done
