### ISSUE TITLE
Non-Rectangular trait extremely slow on large images

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#4466]
| Bugzilla |  |
|----------|----------|
| ID | BZ1870 |
| Reported | 2007-01-03 08:14:00 +0100 |
| Modified | 2020-06-22 00:13:04 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | medium |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2010-08-25 14:35:37 +0200
<pre>---- Reported by uckelman@nomic.net 2007-01-03 20:14 ----

1. Add the Non-Rectangular trait to a piece.
2. Select a very large image, e.g. the Map_West.gif from the Tour module.
3. Wait forever.

---- Additional Comments From uckelman@nomic.net 2007-01-03 20:22:04 ----

Logged In: YES 
user_id=245140
Originator: YES

Hmm. It only *seems* to hang; actually if you walk off and do something else for a while, it eventually loads the image.

---- Additional Comments From b.easton@exemail.com.au 2007-01-31 01:37:56 ----

Logged In: YES 
user_id=908861
Originator: NO

Changed this to a feature request for improved efficiency when processing large non-rectangular images. You only do this once for a module, so priority is not high. Perhaps a warning message for larger images that this will take a long time?

--- Bug imported by uckelman@nomic.net 2010-08-25 14:35 MST  ---

This bug was previously known as _bug_ 1627304 at http://www.vassalengine.org/trackershow_bug.cgi?id=1627304

The original assignee of this bug does not have
   an account here. Reassigning to the default assignee
   for the component, uckelman@nomic.net.
   Previous assignee is unknown.
Missing Resolution. Setting status to NEW
Unknown resolution "".
   Setting resolution to MOVED</pre>

**Comment by Cattlesquat** [comment]
This seems no longer a problem - I loaded the Almoravid mapboard (e.g. over 3000x5000 pixels) in as a mask and it was virtually instantaneous.
