### ISSUE TITLE
Red indicator to show logfile recording in progress.

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#4487]
| Bugzilla |  |
|----------|----------|
| ID | BZ1892 |
| Reported | 2008-02-08 11:33:00 +0100 |
| Modified | 2020-06-22 00:12:13 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | medium |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2010-08-25 14:35:37 +0200
<pre>---- Reported by nobody 2008-02-08 23:33 ----

I know you can tell if a logfile is being recorded by the Window title text but users are still missing the fact.

I propose a red "thing" somewhere on the main window to make it obvious you have started a logfile.

--- Bug imported by uckelman@nomic.net 2010-08-25 14:35 MST  ---

This bug was previously known as _bug_ 1889921 at http://www.vassalengine.org/trackershow_bug.cgi?id=1889921

Unknown Component 
   Using default product and component set in Parameters 
The original reporter of this bug does not have
   an account here. Reassigning to the person who moved
   it here: uckelman@nomic.net.
   Previous reporter was nobody.
The original assignee of this bug does not have
   an account here. Reassigning to the default assignee
   for the component, uckelman@nomic.net.
   Previous assignee was Joel Uckelman.
Missing Resolution. Setting status to NEW
Unknown resolution "".
   Setting resolution to MOVED</pre>

**Comment by Cattlesquat** [comment]
log file recording is much more obvious now
