### ISSUE TITLE
Turrret Support

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#4503]
| Bugzilla |  |
|----------|----------|
| ID | BZ1910 |
| Reported | 2009-03-30 10:05:00 +0200 |
| Modified | 2020-06-22 00:12:07 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | medium |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2010-08-25 14:35:37 +0200
<pre>---- Reported by nobody 2009-03-30 22:05 ----

Can we get a class for turrets similar to layers, but instead allows the layer arbitrary rotation in fixed local relation to its host piece? Right now it seems its either a cumbersome double rotation on the hull to get the turret to face, or you generate images for each rotation. Neither is really sufficient for a mininature game with infinite rotations.

---- Additional Comments From b.easton@exemail.com.au 2009-03-31 01:43:48 ----

I believe you can already do what you want to do by correctly ordering your traits. Turret outermost, then a free rotate, then your unit.

Please open this discussion on the Vassal Features forum for more detailed assistance.

--- Bug imported by uckelman@nomic.net 2010-08-25 14:35 MST  ---

This bug was previously known as _bug_ 2722571 at http://www.vassalengine.org/trackershow_bug.cgi?id=2722571

Unknown Component 
   Using default product and component set in Parameters 
The original reporter of this bug does not have
   an account here. Reassigning to the person who moved
   it here: uckelman@nomic.net.
   Previous reporter was nobody.
The original assignee of this bug does not have
   an account here. Reassigning to the default assignee
   for the component, uckelman@nomic.net.
   Previous assignee is unknown.
Missing Resolution. Setting status to NEW
Unknown resolution "".
   Setting resolution to MOVED</pre>

**Comment by BrentEaston** [comment]
As stated, this can already be implemented.
