### ISSUE TITLE
instance limits for pieces

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#4507]
| Bugzilla |  |
|----------|----------|
| ID | BZ1914 |
| Reported | 2007-01-17 10:21:00 +0100 |
| Modified | 2020-06-22 00:12:57 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | medium |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2010-08-25 14:35:37 +0200
<pre>---- Reported by uckelman@nomic.net 2007-01-17 22:21 ----

Many games have a limited supply of a particular type of counter as a mechanism for regulating game play. (Examples: population tokens in Civilization, remnant tokens in The Longest Day.) It would be useful if there were a way to instance-limit pieces in order to prevent too many of a particular type from being in play at once.

Quoth Neil Randall:

"Either one of the following: (a) Add a Pieces Palette exactly like the current one, but which can be used like a counter tray - with a fixed number of each piece; OR (b) Allow the current Pieces Palette to have the pieces in it limited, ideally on a piece-by-piece basis. The idea here is that the palette and its organization is FAR more useful than at-start stacks, its only downside being the fact that it has unlimited numbers of pieces."

--- Bug imported by uckelman@nomic.net 2010-08-25 14:35 MST  ---

This bug was previously known as _bug_ 1638104 at http://www.vassalengine.org/trackershow_bug.cgi?id=1638104

Unknown Component 
   Using default product and component set in Parameters 
The original assignee of this bug does not have
   an account here. Reassigning to the default assignee
   for the component, uckelman@nomic.net.
   Previous assignee was Michael Kiefte.
Missing Resolution. Setting status to NEW
Unknown resolution "".
   Setting resolution to MOVED</pre>

**Comment by Cattlesquat** [comment]
A map window with "decks" would be entirely sufficient to implement this, with no additional code needed.
