### ISSUE TITLE
DiceButton - Add variable to report raw rolls

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#4524]
| Bugzilla |  |
|----------|----------|
| ID | BZ1931 |
| Reported | 2009-04-10 09:49:00 +0200 |
| Modified | 2020-06-22 00:12:44 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | medium |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Brent Easton](mailto:b.easton@exemail.com.au) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2010-08-25 14:35:37 +0200
<pre>---- Reported by b.easton@exemail.com.au 2009-04-10 21:49 ----

Well after reading about some of the things people want (all very cool). I hope what I'm asking for should be an easy thing to put in. In the Dice Button Report Format there are vars to report several things, but I'd like to add one that will report the actual number rolled on the die. There is already a $result$ var that will report the total number (dice roll + modifiers), but there isn't a way to get just the number on the dice rolled.

This is useful to me because in the game we are playing rolling a natural 1 on a d6 is always a fail and rolling a natural 6 is always a success. Thus when the report I get back is: 1d6 + 3 = 7 the players have to do subtraction to figure out if they rolled a 1 or a 6. I'd like to have it look like this: 4 + 3 = 7. 

Current reporting format is: <playerName> makes an $name$: $nDice$d$nSides$ + $plus$ = $result$

--- Bug imported by uckelman@nomic.net 2010-08-25 14:35 MST  ---

This bug was previously known as _bug_ 2750887 at http://www.vassalengine.org/trackershow_bug.cgi?id=2750887

Unknown Component 
   Using default product and component set in Parameters 
The original assignee of this bug does not have
   an account here. Reassigning to the default assignee
   for the component, uckelman@nomic.net.
   Previous assignee is unknown.
Missing Resolution. Setting status to NEW
Unknown resolution "".
   Setting resolution to MOVED</pre>

**Comment by Cattlesquat** [comment]
Fixed by #10518
