### ISSUE TITLE
at-start stack facing

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#4551]
| Bugzilla |  |
|----------|----------|
| ID | BZ1958 |
| Reported | 2009-08-29 06:29:00 +0200 |
| Modified | 2020-06-22 00:12:20 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | medium |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2010-08-25 14:35:37 +0200
<pre>---- Reported by jjmurphy 2009-08-29 18:29 ----

Add property to at-start stacks to permit defining the facing of the stack at the start of the game.
This could cause problems unless the pieces in the stack have a 'can rotate' trait with an appropriate resolution for the rotation entered for this new the at-start stack facing, so that is something to work out as part of this feature.

---- Additional Comments From b.easton@exemail.com.au 2009-08-30 23:31:13 ----

I don't believe this is an appropriate feature for an At-Start stack.

If the pieces have the appropriate 'Can Rotate' trait, then just pre-rotate them to the correct facing when you create the pieces in the Stack.

---- Additional Comments From nobody 2009-08-31 12:11:48 ----

When you create a piece in the at-start stack, there is no way to "pre-rotate them to the correct facing", which is the point of this feature request. Unless there is some option that is not obvious from the menu and dialog choices in the module editor, in which case please elaborate.

So you have to build separate classes of pieces pre-rotated then?

Or the player has to rotate all his pieces when starting the game?

Pieces need to be be deployed on the map in particular facings. One option is to use a save game for the setup, another is to use at-start stacks. This would permit at-start stacks to support rotated pieces without appearing any different to the player.

--- Bug imported by uckelman@nomic.net 2010-08-25 14:35 MST  ---

This bug was previously known as _bug_ 2846942 at http://www.vassalengine.org/trackershow_bug.cgi?id=2846942

The original reporter of this bug does not have
   an account here. Reassigning to the person who moved
   it here: uckelman@nomic.net.
   Previous reporter was jjmurphy.
The original assignee of this bug does not have
   an account here. Reassigning to the default assignee
   for the component, uckelman@nomic.net.
   Previous assignee is unknown.
Missing Resolution. Setting status to NEW
Unknown resolution "".
   Setting resolution to MOVED</pre>

**Comment by BrentEaston** [comment]
Pieces in At-start stacks can be 'pre-rotated' , assuming they have the correct Can Rotate trait. In the module, Edit the piece definition in the Stack , right-click on the image and select the command to rotate it. When the scenario starts, the pieces will be already rotated.
