### ISSUE TITLE
Add bug reporting instructions to FAQ

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#5319]
| Bugzilla |  |
|----------|----------|
| ID | BZ2902 |
| Reported | 2010-09-03 04:51:00 +0200 |
| Modified | 2010-09-05 15:08:43 +0200 |
| Product | Website |
| Component | Tracker |
| Version | unspecified |
| Platform | PC |
| OS | All |
| Status | ASSIGNED |
| Resolution | None |
| Priority | high |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Joel Uckelman](mailto:uckelman@nomic.net) |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2010-09-03 04:51:13 +0200
<pre>There are no instructions showing users how to report bugs in the FAQ. There should be.</pre>

**Comment by Cattlesquat** [comment]
https://vassalengine.org/wiki/Faq_bugs

Also linked from the main faq page of course.
