### ISSUE TITLE
Add change log to module template

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#5320]
| Bugzilla |  |
|----------|----------|
| ID | BZ2903 |
| Reported | 2010-09-03 05:51:00 +0200 |
| Modified | 2010-09-05 15:08:44 +0200 |
| Product | Website |
| Component | Modules |
| Version | unspecified |
| Platform | PC |
| OS | All |
| Status | ASSIGNED |
| Resolution | None |
| Priority | low |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Joel Uckelman](mailto:uckelman@nomic.net) |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2010-09-03 05:51:19 +0200
<pre>Says Ken (ken.stevens@sympatico.ca):

> It might be nice to have a Change Log section on module pages.  I added
> one for myself on the TTA page (hope that's okay).  Or there should be
> somewhere where you can see what got fixed/changed in recent version
> updates.</pre>

**Comment by Cattlesquat** [comment]
done
