### ISSUE TITLE
Keep game passwords in local password store

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#5373]
| Bugzilla |  |
|----------|----------|
| ID | BZ2983 |
| Reported | 2010-09-24 02:35:00 +0200 |
| Modified | 2020-06-22 00:12:00 +0200 |
| Product | VASSAL |
| Component | Player |
| Version | 3.1.14 |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | medium |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2010-09-24 02:35:44 +0200
<pre>We frequently get requests from people who have forgotten their passwords to help them get into their saved games. We could largely avoid this problem by storing saved game passwords in a local file. The only way this is a security risk is if your opponent has access to your user account, so I don't see this is as serious problem, and implementing it could save us a lot of headaches and user frustration. We could also eliminate the need for users to type their passwords when they join a side, this way.</pre>

**Comment by Cattlesquat** [comment]
This actually basically dupes #4387
