### ISSUE TITLE
Upload modules larger than file size limit

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#5408]
| Bugzilla |  |
|----------|----------|
| ID | BZ3060 |
| Reported | 2010-10-15 20:14:00 +0200 |
| Modified | 2010-11-27 06:38:24 +0100 |
| Product | Website |
| Component | Modules |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | ASSIGNED |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Tim McCarron](mailto:timothy.mccarron@sbcglobal.net) |
| Assignee | [Joel Uckelman](mailto:uckelman@nomic.net) |
| CC | timothy.mccarron@sbcglobal.net |

#### [Tim McCarron](mailto:timothy.mccarron@sbcglobal.net) 2010-10-15 20:14:43 +0200
<pre>We still have a number of modules to upload that are larger than the 50mb file size limit.
They have been scrutinized - they wont get any smaller. No duplicate graphics etc..

Currently all of these missing modules can be found at: http://www.mediafire.com/vassalpro

the files are in the folder named Joel uploads. File names do not need to be changed, they are already set to match their module page name link

Tim</pre>

#### [Tim McCarron](mailto:timothy.mccarron@sbcglobal.net) 2010-10-15 20:16:53 +0200
<pre>Assigned to Joel</pre>

**Comment by Cattlesquat** [comment]
@uckelman Is this "still a thing"?

**Comment by uckelman** [comment]
I believe we've dealt with all of the modules which were over the limit from way back then.
