### ISSUE TITLE
Prevent non-images from being added to modules as images

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#5483]
| Bugzilla |  |
|----------|----------|
| ID | BZ3198 |
| Reported | 2010-11-28 07:55:00 +0100 |
| Modified | 2020-06-22 00:13:12 +0200 |
| Product | VASSAL |
| Component | Editor |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | medium |
| Severity | major |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |
| CC | wojciech.meyer@gmail.com |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2010-11-28 07:55:13 +0100
<pre>If non-images are added to modules as images, it can become impossible to save modules.

See http://www.vassalengine.org/forum/viewtopic.php?p=19776#p19776 for details.</pre>

#### [Wojciech Meyer](mailto:wojciech.meyer@gmail.com) 2010-12-01 14:45:47 +0100
<pre>Cannot reproduce it on:

  Linux spec-desktop 2.6.32-25-generic #45-Ubuntu SMP Sat Oct 16 19:48:22 UTC 2010 i686 GNU/Linux

with:
  SVN Revision: 7524, (Vassal 3.1.15)

Probably a genuine OS X bug. Need to confirm the behaviour.</pre>

**Comment by Cattlesquat** [comment]
https://forum.vassalengine.org/t/how-do-i-delete-an-image-prior-to-saving-the-module/3259/4

**Comment by Cattlesquat** [comment]
Seems to just produce Bad Module Data now.
