### ISSUE TITLE
Turn off automatic bug reporting after an OutOfMemory

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#5540]
| Bugzilla |  |
|----------|----------|
| ID | BZ3291 |
| Reported | 2011-01-05 18:00:00 +0100 |
| Modified | 2020-11-01 17:19:59 +0100 |
| Product | VASSAL |
| Component | Unknown |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | TRIAGED |
| Resolution | None |
| Priority | low |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2011-01-05 18:00:43 +0100
<pre>We get too many garbage bug reports after OOMEs. We should add a flag to the bug reporter that prevents it from firing after an OOME.</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2012-10-09 05:04:05 +0200
<pre>*** Bug 9379 has been marked as a duplicate of this bug. ***</pre>

**Comment by Cattlesquat** [comment]
Per errordialog.java this seems to already be handled?
