### ISSUE TITLE
Double characters appearing for NamedKeyStroke

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#6001]
| Bugzilla |  |
|----------|----------|
| ID | BZ3976 |
| Reported | 2011-10-01 19:38:00 +0200 |
| Modified | 2012-12-03 11:14:56 +0100 |
| Product | VASSAL |
| Component | Editor |
| Version | 3.2.0 |
| Platform | All |
| OS | All |
| Status | CLOSED |
| Resolution | FIXED |
| Priority | unspecified |
| Severity | normal |
| Milestone | 3.2.0 |
| Reporter | [Brent Easton](mailto:b.easton@exemail.com.au) |
| Assignee | [Brent Easton](mailto:b.easton@exemail.com.au) |
| CC | uckelman@nomic.net |

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2011-10-01 19:38:31 +0200
<pre>When using the new Keyboard Command editor, the second key of a named key command is sometimes doubled up. Happens occaisonally when typing fase.</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2012-02-05 22:19:31 +0100
<pre>I wonder if this is related to Bug 4184. The problem there apparently was that text fields were using a KeyListener, but should have been using a DocumentListener. I'm waiting for confirmation that my change (trunk@8068) fixed the problem.</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2012-09-27 18:19:54 +0200
<pre>I can no longer reproduce this problem, I believe you have fixed it.</pre>

**Comment by BrentEaston** [comment]
#4184
