### ISSUE TITLE
Toolbar button icon during module editing doesn't get removed

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#6040]
| Bugzilla |  |
|----------|----------|
| ID | BZ4062 |
| Reported | 2011-10-16 22:33:00 +0200 |
| Modified | 2020-06-22 00:13:08 +0200 |
| Product | VASSAL |
| Component | Editor |
| Version | 3.1.18 |
| Platform | PC |
| OS | Windows |
| Status | NEW |
| Resolution | None |
| Priority | low |
| Severity | normal |
| Milestone | --- |
| Reporter | [Jon Test](mailto:viewport2heaven@yahoo.com) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Jon Test](mailto:viewport2heaven@yahoo.com) 2011-10-16 22:33:28 +0200
<pre>1. Create a new Map Window.

2. Set Map Window to "Include toolbar button to show/hide".

3. Click OK to save.

4. Set Map Window "Button Icon" to default. Icon gets updated in toolbar. Great real-time edit indication.

5. Click Cancel to cancel setting of button icon.

The icon in the toolbar does not get removed.

Work around requires closing the module and opening it for editing again.</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2012-01-31 22:29:18 +0100
<pre>The properties dialog for Map is automatically generated, I believe by VASSAL.configurable.PropertiesWindow. cancel() appears to reset the old state, so if the old state is indeed being reset, the thing to look into is why the GUI isn't updated when that happens.</pre>

**Comment by Cattlesquat** [comment]
That field in Map Window is currently marked "requires restart"
