### ISSUE TITLE
Map Loss on Network Connection

### ISSUE THREAD

**Issue by LordSwad** [vassalengine/vassal#627]
Just installed this version and when using the module The Dark Valley, everything loaded ok, loaded a saved game, created a room on the network but as my opponent joined the room (approx) I lost the map but kept the log window and toolbar. This was repeatable. Went back to 3.4.10 but the same occurred so went back to 3.4.6 which is the version we last played on and that worked.

Using macOS 10.11.1

**Comment by BrentEaston** [comment]
Hi, thanks for the info.

We don't generally use github issues, our main bug tracker is bugzilla at http://www.vassalengine.org/tracker/. Issues here tend to be overlooked, I just noticed it by chance.

It would be greatly appreciated if you could do two things:-
1. Re-create the issue in bugzilla.
2. Try and reproduce the issue on 3.4.7, 3.4.7 and 3.4.9 to isolate exactly which version the problem appears.

The development team has very limited access to Mac machines for testing.

Thanks,
Brent.
