### ISSUE TITLE
Add text label to decks.

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#6460]
| Bugzilla |  |
|----------|----------|
| ID | BZ4678 |
| Reported | 2012-08-11 12:34:00 +0200 |
| Modified | 2020-06-22 00:13:02 +0200 |
| Product | VASSAL |
| Component | Player |
| Version | 3.2.0 |
| Platform | Other |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | medium |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Thomas Russ](mailto:taruss2000@gmail.com) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Thomas Russ](mailto:taruss2000@gmail.com) 2012-08-11 12:34:58 +0200
<pre>Add the ability to add a text label to decks.

This will allow, for example, an easy way to show the name and number of cards in a deck.

This will solve the issues raised in this thread:
http://www.vassalengine.org/forum/viewtopic.php?f=6&t=5451</pre>

**Comment by Cattlesquat** [comment]
It is already straightforward to make a piece into this kind of text label
