### ISSUE TITLE
Import Cyberboard gameboxes, saves, and logs

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#6526]
| Bugzilla |  |
|----------|----------|
| ID | BZ4761 |
| Reported | 2012-09-05 13:04:00 +0200 |
| Modified | 2020-11-01 17:19:59 +0100 |
| Product | VASSAL |
| Component | Unknown |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | TRIAGED |
| Resolution | None |
| Priority | unspecified |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Michael Kiefte](mailto:mkiefte@gmail.com) |
| CC | uckelman@nomic.net |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2012-09-05 13:04:14 +0200
<pre>Reverse engineer the Cyberboard file formats so we can import CB gameboxes, saves, and logs.</pre>

**Comment by Cattlesquat** [comment]
This seems like a not-likely-to-actually-ever-get-done-even-for-V4 kind of thing, and if someone is into doing it, it won't be because we kept it on the buglist.

**Comment by uckelman** [comment]
I think it could happen if someone were very motivated to do it---CB is open-source now, so it wouldn't even require reverse engineering anymore.
