### ISSUE TITLE
Can VASSAL be run on an Apple IPAD??

### ISSUE THREAD

**Issue by TennesseeRick** [vassalengine/vassal#656]
It is not clear from the various versions of 3.4.13 how to run VASSAL on an IPAD. IPAD can run Java, but is there an easy way to run VASSAL on an IPAD?

**Comment by uckelman** [comment]
How did you manage to install Java on an iPad?

**Comment by draft13** [comment]
This oughta be good...

**Comment by TennesseeRick** [comment]
Joel,

 

I went to the Apple App store and found the following (with several other choices as well):

 

                Jedona Compiler

                RunJavaScript

                Java (but in German? or Scandinavian?)

 

Obviously I do not know very much about Java, but I do very much enjoy playing games on VASSAL. I have a HP tablet (7 inch diagonal screen) that runs Windows 10, but I also have a more convenient (and newer) mini-IPAD with much sharper screen image. 

 

I would like to run VASSAL on the mini-IPAD if possible, and just did not know enough how to ask if it is possible.

 

Thanks for your response thus far. I don’t expect you to educate me, so a simple NO is also an acceptable answer.

 

Rick Virost

**Comment by draft13** [comment]
Sorry @TennesseeRick , I shouldn't been flippant. The Java runtime isn't compatible with iOS, therefore VASSAL doesn't (won't) run on an iPad.

**Comment by Cattlesquat** [comment]
I will admit that I would LOVE if VASSAL ran on my iPhone. As in use-it-hundreds-of-times-a-week amount of love. Alas!
