### ISSUE TITLE
version numbers in macOS broken

### ISSUE THREAD

**Issue by core-code** [vassalengine/vassal#69]
i've downloaded version 3.3.1 but the version numbers viewable in the Finder indicate it is actually version 3.3.0

<img width="377" alt="Screenshot 2020-07-08 at 00 01 48" src="https://user-images.githubusercontent.com/1261954/86848485-60da8e80-c0ae-11ea-88ef-81eb7be52e40.png">
<img width="727" alt="Screenshot 2020-07-08 at 00 01 42" src="https://user-images.githubusercontent.com/1261954/86848487-62a45200-c0ae-11ea-9b57-6cc7070e8dc8.png">
<img width="687" alt="Screenshot 2020-07-08 at 00 01 28" src="https://user-images.githubusercontent.com/1261954/86848488-633ce880-c0ae-11ea-8b11-cd75f341471a.png">

**Comment by core-code** [comment]
in you Info.plist file:

• CFBundleShortVersionString is set to 3.3.0 but should be set to 3.3.1
• CFBundleVersion is set to 0 but should be set to 3.3.1
• CFBundleGetInfoString has been deprecated more than 10 years and should be removed unless you target macOS 10.5 or older.

**Comment by uckelman** [comment]
I have no idea how that happened, as those values are filled in automatically when we do a build. I'm make sure they're as expected before we release 3.3.2.

See PR 72.

Thanks for the bug report.

**Comment by core-code** [comment]
awesome, thanks!

**Comment by uckelman** [comment]
Fixed in 3.3.2.

**Comment by core-code** [comment]
thanks i can confirm it is fixed in 3.3.2
