### ISSUE TITLE
Impossible to remove a LOS thread after log replay

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#7057]
| Bugzilla |  |
|----------|----------|
| ID | BZ9973 |
| Reported | 2013-03-12 18:52:00 +0100 |
| Modified | 2020-06-22 00:11:52 +0200 |
| Product | VASSAL |
| Component | Player |
| Version | 3.2.2 |
| Platform | PC |
| OS | Linux |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Pascal](mailto:downs.bo192@free.fr) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Pascal](mailto:downs.bo192@free.fr) 2013-03-12 18:52:37 +0100
<pre>I went across this bug while preparing a PBEM tutorial, and I didn't find any previous report about it (it may be related to the most frequently reported bug ever, but it's not the same: am I the first one to do such a stupid thing? ;)
 
If you leave a pending LOS thread (not persistent) when you end a log file, then this LOS cannot be removed once the log has been replayed.

1) use the default LOS settings :
   	persistence = "ctrl-clic & drag" (same bug with "never" I think)
	visible to opponents = always
2) start a log, draw a LOS, close the log when the LOS is still on screen
3) replay the log until the end
4) now you're stuck with a LOS on the map (you cannot remove it), and the LOS button is "broken" (impossible to draw any new LOS).

Same bug when persistence="always" and visible="always" (if you end the log without clicking in the map to make the LOS persistent).
No bug when the option visible="when persisting".

Possible causes/solutions:
If my understanding of LOS_Thread.java is right, I think the LOS in the saved log is in a state with mirroring=true (thus visible=true) and persisting=false. Then the button function launch() is inactive until the LOS is cleared (or made persistent).
I guess this is done for "live play", to prevent other players from messing with the player drawing the LOS (anyway I'm not sure what would happen if one click on LOS while another is still dragging another LOS).

Indeed, a quick hack in LOS_Thread.java was enough to unlock my .vlog and its unclearable LOS:
  protected void launch() {
    if (!visible || (!persisting && mirroring)) { //instead of only "!visible"
      setMirroring(false);                        //new
      map.pushMouseListener(this);  //...remaining is left untouched

But this doesn't seem the right way to do it... (I didn't test whether it created problems with other options combinations, but most of all I'm not sure what might happen during "live play")

A better(?) workaround may be to check that there is no network connection to allow "mirroring" to be reset (but I don't know if it makes sense with live play and synchronisation anyway).

Another solution is to always set "visible to opponents = when persisting" ;o)
else to warn the players to always clear their pending LOS before ending a log ! (or to do it automatically by adding a fake command?).

That's all folks, sorry for being soooo long! :)

Pascal.</pre>

**Comment by Cattlesquat** [comment]
This was fixed by issue 14256  (commit #649bfdeb7)
