### ISSUE TITLE
Add a "copy to clipboard" button to the help, show error log dialog

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#8601]
| Bugzilla |  |
|----------|----------|
| ID | BZ12531 |
| Reported | 2016-08-06 05:50:00 +0200 |
| Modified | 2020-06-22 00:12:58 +0200 |
| Product | VASSAL |
| Component | Module Manager |
| Version | 3.2.16 |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | minor |
| Milestone | --- |
| Reporter | [JR VanMechelen](mailto:vassal@jrvdev.com) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [JR VanMechelen](mailto:vassal@jrvdev.com) 2016-08-06 05:50:39 +0200
<pre>It's about 50/50 whether a given user can figure out how to copy out all the text from the show error dialog, especially when the text goes past the bottom of the window. A button labeled "Copy error message to clipboard" would help a lot of users.</pre>

**Comment by Cattlesquat** [comment]
@uckelman Does this still seem like a good idea? It's super-easy to do. I just don't want to accidentally discourage users from actually sending the ABR bug reports (by distracting them with another button). Maybe only in non-reporting versions?

**Comment by uckelman** [comment]
The thing about non-reporting versions is that I intentionally made them non-reporting so that we don't get the reports. Reports from old versions are mostly not useful, and people using test version usually are au fait with copy and paste. So I'm leaning toward No on this one.
