### ISSUE TITLE
Allow At-start Stacks and Decks to be created on Boards

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#9330]
| Bugzilla |  |
|----------|----------|
| ID | BZ13501 |
| Reported | 2020-10-10 08:11:00 +0200 |
| Modified | 2020-10-10 12:14:56 +0200 |
| Product | VASSAL |
| Component | Editor |
| Version | 3.4.5 |
| Platform | All |
| OS | All |
| Status | ASSIGNED |
| Resolution | None |
| Priority | unspecified |
| Severity | enhancement |
| Milestone | 3.5.0 |
| Reporter | [Brent Easton](mailto:b.easton@exemail.com.au) |
| Assignee | [Brent Easton](mailto:b.easton@exemail.com.au) |

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2020-10-10 08:11:52 +0200
<pre>Will work exactly the same as a Map At-start stack/Deck, but with no 'Select Board' option.</pre>

**Comment by Cattlesquat** [comment]
What if the same board is used more than once? For setupstacks that could mean being created twice which could potentially be fine. Two Decks on a map with the same name though?

**Comment by BrentEaston** [comment]
I no longer even know what the original use case for this was. I'm not sure it would be useful for the general Vassal population. This may have been a thought bubble from a single user.

**Comment by jonathanrwatts** [comment]
I believe this one was mine, but the folders feature of 3.6 makes it no longer a priority--in a module with multiple, alternate boards (only 1 loaded at a time), it was annoying having to have a different set of At-Start Stacks/Decks for each alternate board, all listed together in the Map Window.  With Folders, though, we can now visually separate/hide them, so it's no longer a big deal.
